In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import linearmodels as lm
import matplotlib
import math
import statsmodels.formula.api as smf

from linearmodels.panel import PanelOLS
from linearmodels.panel import RandomEffects
from linearmodels.panel import FirstDifferenceOLS
from linearmodels.panel import compare
from matplotlib import pyplot as plt

from pandas.api.types import is_numeric_dtype

pd.set_option('display.max_columns', 500)

%matplotlib inline

In [3]:
df=pd.read_csv('../Factors and Ridership Data/Final Datasets/final_dataset.csv',
                    encoding='utf-8')
df.head()

,Unnamed: 0,Geography,RailBus,Year,CBSA,CBSA Code,UPT,VRM,UPT_ADJ,VRM_ADJ,State,FARE_TOTAL,FARE_per_UPT,POPPT,HUPT,AREAPT,AREALANDPT,UAPOP,UAHU,UAAREA,UAAREALAND,MPOP,MHU,MAREA,MAREALAND,UAPOPPCT,UAHUPCT,UAAREAPCT,UAAREALANDPCT,MPOPPCT,MHUPCT,MAREAPCT,MAREALANDPCT,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,Pop_TSD,Tot_Emp_TSD,Tot_Retail_TSD,gasPrice,JTW_DA,JTW_CARPOOL,JTW_TRANSIT,MEAN_TT,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_Labor_MSA,Unemployment_Labor_MSA,Employment_Labor:MSA,Unemployment_Rate_MSA,TNC_Presence_Month,TNC_Presence_Year,Link,TNC_FLAG
0,0,"Abilene, TX Metro Area",Bus,2005,10180.0,10180.0,507165.0,444176.0,507165.0,444176.0,NaN,213965.0,0.421884,110421.0,46732.0,142744247.0,141756054.0,110421.0,46732.0,142744247.0,141756054.0,165252.0,69721.0,7.142425e+09,7.105575e+09,100.0,100.0,100.0,100.0,66.82,67.03,2.0,1.99,60532.0,2175.0,23133.0,24645.0,7899.0,2680.0,3976.5,5505.0,250.0,2.231750,53169,7865,264,16.7,35535.0,45619.0,49.3,42.5,8.2,146427.0,105269.0,33286.0,2591.0,20297.0,20244.0,21328.0,18960,146258.0,17.6,12.7,69.7,26.9,59.4,13.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,"Abilene, TX Metro Area",Bus,2006,10180.0,10180.0,493638.0,441300.0,493638.0,441300.0,NaN,201795.0,0.408791,110421.0,46732.0,142744247.0,141756054.0,110421.0,46732.0,142744247.0,141756054.0,165252.0,69721.0,7.142425e+09,7.105575e+09,100.0,100.0,100.0,100.0,66.82,67.03,2.0,1.99,59850.0,2356.0,21689.0,25837.0,7647.0,2321.0,3984.0,5469.0,276.0,2.520667,55425,9243,233,17.4,39784.0,52364.0,44.0,46.1,9.9,158548.0,113266.0,37165.0,2023.0,20570.0,19222.0,22110.0,29210,146298.0,15.8,13.3,70.9,25.2,61.2,13.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2,"Abilene, TX Metro Area",Bus,2007,10180.0,10180.0,490254.0,424839.0,490254.0,424839.0,NaN,217336.0,0.443313,110421.0,46732.0,142744247.0,141756054.0,110421.0,46732.0,142744247.0,141756054.0,165252.0,69721.0,7.142425e+09,7.105575e+09,100.0,100.0,100.0,100.0,66.82,67.03,2.0,1.99,60692.0,3218.0,20497.0,25691.0,8228.0,3058.0,3991.5,5735.0,273.0,2.719000,55960,7030,251,16.3,39369.0,51693.0,44.1,46.0,9.9,159439.0,111201.0,37761.0,3496.0,20408.0,18921.0,25843.0,23817,144006.0,15.1,10.8,74.1,24.7,61.6,13.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,3,"Abilene, TX Metro Area",Bus,2008,10180.0,10180.0,473528.0,421757.0,473528.0,421757.0,NaN,254879.0,0.538255,110421.0,46732.0,142744247.0,141756054.0,110421.0,46732.0,142744247.0,141756054.0,165252.0,69721.0,7.142425e+09,7.105575e+09,100.0,100.0,100.0,100.0,66.82,67.03,2.0,1.99,59960.0,2164.0,22931.0,24732.0,7910.0,2223.0,3999.0,5883.0,335.0,3.193333,62316,7358,170,17.9,41961.0,58191.0,39.6,48.3,12.1,160012.0,111912.0,38496.0,3609.0,23692.0,21792.0,29631.0,27383,147245.0,16.1,10.4,73.6,24.6,62.2,13.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,"Abilene, TX Metro Area",Bus,2009,10180.0,10180.0,478743.0,418714.0,478743.0,418714.0,NaN,248600.0,0.519277,110421.0,46732.0,142744247.0,141756054.0,110421.0,46732.0,142744247.0,141756054.0,165252.0,69721.0,7.142425e+09,7.105575e+09,100.0,100.0,100.0,100.0,66.82,67.03,2.0,1.99,58052.0,3724.0,20561.0,21354.0,8712.0,3701.0,4006.5,5831.0,312.0,2.270333,59145,9390,225,16.8,42931.0,54998.0,41.4,46.8,11.8,160266.0,108498.0,38872.0,3335.0,21670.0,20923.0,26456.0,21698,148662.0,14.5,11.6,74.0,24.0,62.7,13.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
df=df.drop(columns=['Unnamed: 0'])

In [9]:
#test=df[df['Cluster_upt']==1]
#test

In [5]:
df2=df[df['RailBus']=='Bus']

In [6]:
new=df2.groupby(['Geography','Year']).mean()

In [7]:
#new=new.drop(columns=['RailBus'])
new.head()

                                CBSA  CBSA Code       UPT       VRM   UPT_ADJ  \
Geography              Year
Abilene, TX Metro Area 2005  10180.0    10180.0  507165.0  444176.0  507165.0
                       2006  10180.0    10180.0  493638.0  441300.0  493638.0
                       2007  10180.0    10180.0  490254.0  424839.0  490254.0
                       2008  10180.0    10180.0  473528.0  421757.0  473528.0
                       2009  10180.0    10180.0  478743.0  418714.0  478743.0

                              VRM_ADJ  FARE_TOTAL  FARE_per_UPT     POPPT  \
Geography              Year
Abilene, TX Metro Area 2005  444176.0    213965.0      0.421884  110421.0
                       2006  441300.0    201795.0      0.408791  110421.0
                       2007  424839.0    217336.0      0.443313  110421.0
                       2008  421757.0    254879.0      0.538255  110421.0
                       2009  418714.0    248600.0      0.519277  110421.0

                                HUPT       AREAPT   AREALANDPT     UAPOP  \
Geography              Year
Abilene, TX Metro Area 2005  46732.0  142744247.0  141756054.0  110421.0
                       2006  46732.0  142744247.0  141756054.0  110421.0
                       2007  46732.0  142744247.0  141756054.0  110421.0
                       2008  46732.0  142744247.0  141756054.0  110421.0
                       2009  46732.0  142744247.0  141756054.0  110421.0

                                UAHU       UAAREA   UAAREALAND      MPOP  \
Geography              Year
Abilene, TX Metro Area 2005  46732.0  142744247.0  141756054.0  165252.0
                       2006  46732.0  142744247.0  141756054.0  165252.0
                       2007  46732.0  142744247.0  141756054.0  165252.0
                       2008  46732.0  142744247.0  141756054.0  165252.0
                       2009  46732.0  142744247.0  141756054.0  165252.0

                                 MHU         MAREA     MAREALAND  UAPOPPCT  \
Geography              Year
Abilene, TX Metro Area 2005  69721.0  7.142425e+09  7.105575e+09     100.0
                       2006  69721.0  7.142425e+09  7.105575e+09     100.0
                       2007  69721.0  7.142425e+09  7.105575e+09     100.0
                       2008  69721.0  7.142425e+09  7.105575e+09     100.0
                       2009  69721.0  7.142425e+09  7.105575e+09     100.0

                             UAHUPCT  UAAREAPCT  UAAREALANDPCT  MPOPPCT  \
Geography              Year
Abilene, TX Metro Area 2005    100.0      100.0          100.0    66.82
                       2006    100.0      100.0          100.0    66.82
                       2007    100.0      100.0          100.0    66.82
                       2008    100.0      100.0          100.0    66.82
                       2009    100.0      100.0          100.0    66.82

                             MHUPCT  MAREAPCT  MAREALANDPCT  Total_HH  \
Geography              Year
Abilene, TX Metro Area 2005   67.03       2.0          1.99   60532.0
                       2006   67.03       2.0          1.99   59850.0
                       2007   67.03       2.0          1.99   60692.0
                       2008   67.03       2.0          1.99   59960.0
                       2009   67.03       2.0          1.99   58052.0

                             HH_0Veh  HH_1Veh  HH_2Veh  HH_3Veh  HH_4+Veh  \
Geography              Year
Abilene, TX Metro Area 2005   2175.0  23133.0  24645.0   7899.0    2680.0
                       2006   2356.0  21689.0  25837.0   7647.0    2321.0
                       2007   3218.0  20497.0  25691.0   8228.0    3058.0
                       2008   2164.0  22931.0  24732.0   7910.0    2223.0
                       2009   3724.0  20561.0  21354.0   8712.0    3701.0

                             Pop_TSD  Tot_Emp_TSD  Tot_Retail_TSD  gasPrice  \
Geography              Year
Abilene, TX Metro Area 2005   3976.5       5505.0           250.0  2.231750
                       2006   3984.0       5469.0           276.0  2.520667
                       2007   3991.5       5735.0           273.0  2.719000
                       2008   3999.0       5883.0           335.0  3.193333
                       2009   4006.5       5831.0           312.0  2.270333

                             HH_MED_INC  HH_MEAN_INC  INC_U35  INC_35_100  \
Geography              Year
Abilene, TX Metro Area 2005     35535.0      45619.0     49.3        42.5
                       2006     39784.0      52364.0     44.0        46.1
                       2007     39369.0      51693.0     44.1        46.0
                       2008     41961.0      58191.0     39.6        48.3
                       2009     42931.0      54998.0     41.4        46.8

                             INC_100P   Tot_Pop  Tot_Instate_Pop  \
Geography              Year
Abilene, TX Metro Area 2005       8.2  146427.0         105269.0
                       2006       9.9  158548.0         113266.0
                       2007       9.9  159439.0         111201.0
                       2008      12.1  160012.0         111912.0
                       2009      11.8  160266.0         108498.0

                             Tot_Outstate_Pop  Tot_NonUSA_POP  \
Geography              Year
Abilene, TX Metro Area 2005           33286.0          2591.0
                       2006           37165.0          2023.0
                       2007           37761.0          3496.0
                       2008           38496.0          3609.0
                       2009           38872.0          3335.0

                             Total_Median_Income_Individual  \
Geography              Year
Abilene, TX Metro Area 2005                         20297.0
                       2006                         20570.0
                       2007                         20408.0
                       2008                         23692.0
                       2009                         21670.0

                             Native_Instate_Med_Inc_Indiv  \
Geography              Year
Abilene, TX Metro Area 2005                       20244.0
                       2006                       19222.0
                       2007                       18921.0
                       2008                       21792.0
                       2009                       20923.0

                             Native_Outstate_Med_Inc_Indiv  Total_Pop_Poverty  \
Geography              Year
Abilene, TX Metro Area 2005                        21328.0           146258.0
                       2006                        22110.0           146298.0
                       2007                        25843.0           144006.0
                       2008                        29631.0           147245.0
                       2009                        26456.0           148662.0

                             Pop_Below100_Poverty  Pop_Below150_Poverty  \
Geography              Year
Abilene, TX Metro Area 2005                  17.6                  12.7
                       2006                  15.8                  13.3
                       2007                  15.1                  10.8
                       2008                  16.1                  10.4
                       2009                  14.5                  11.6

                             Pop_Above150_Poverty  Age_under18  Age_18to64  \
Geography              Year
Abilene, TX Metro Area 2005                  69.7         26.9        59.4
                       2006                  70.9         25.2        61.2
                       2007                  74.1         24.7        61.6
                       2008                  73.6         24.6        62.2
                       2009                  74.0         24.0        62.7

                             Age_over64  Total_Labor_MSA  \
Geography              Year
Abilene, TX Metro Area 2005        13.7              NaN
                       2006        13.6              NaN
                       2007        13.7              NaN
                       2008        13.2              NaN
                       2009        13.3              NaN

                             Unemployment_Labor_MSA  Employment_Labor:MSA  \
Geography              Year
Abilene, TX Metro Area 2005                     NaN                   NaN
                       2006                     NaN                   NaN
                       2007                     NaN                   NaN
                       2008                     NaN                   NaN
                       2009                     NaN                   NaN

                             Unemployment_Rate_MSA  TNC_Presence_Year  \
Geography              Year
Abilene, TX Metro Area 2005                    NaN                NaN
                       2006                    NaN                NaN
                       2007                    NaN                NaN
                       2008                    NaN                NaN
                       2009                    NaN                NaN

                             TNC_FLAG
Geography              Year
Abilene, TX Metro Area 2005       0.0
                       2006       0.0
                       2007       0.0
                       2008       0.0
                       2009       0.0

In [8]:
mod=PanelOLS.from_formula('UPT \
                    ~ VRM \
                    + Tot_Pop \
                    + Pop_TSD \
                    + gasPrice \
                    + Total_HH \
                    + HH_0Veh \
                    + HH_1Veh \
                    + Tot_Emp_TSD \
                    + HH_MED_INC \
                    + INC_U35 \
                    +INC_35_100 \
                    +TNC_FLAG \
                    +Age_over64',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    UPT   R-squared:                        0.9967
Estimator:                   PanelOLS   R-squared (Between):              0.9995
No. Observations:                2789   R-squared (Within):              -0.6686
Date:                Thu, Sep 19 2019   R-squared (Overall):              0.9967
Time:                        00:51:51   Log-likelihood                -5.671e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                   6.403e+04
Entities:                         277   P-value                           0.0000
Avg Obs:                       10.069   Distribution:                 F(13,2776)
Min Obs:                       3.0000
Max Obs:                       11.000   F-statistic (robust):          6.403e+04
                                        P-value                           0.0000
Time periods:                      11   Distribution:                 F(13,2776)
Avg Obs:                       253.55
Min Obs:                       221.00
Max Obs:                       277.00

                              Parameter Estimates
===============================================================================
             Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------
VRM             3.5891     0.0376     95.550     0.0000      3.5154      3.6627
Tot_Pop         97.401     45.493     2.1410     0.0324      8.1970      186.60
Pop_TSD         114.33     40.153     2.8473     0.0044      35.593      193.06
gasPrice     5.351e+06  6.328e+06     0.8456     0.3979  -7.057e+06   1.776e+07
Total_HH       -344.80     182.07    -1.8938     0.0584     -701.80      12.202
HH_0Veh         5430.9     308.16     17.624     0.0000      4826.7      6035.2
HH_1Veh        -1558.8     274.18    -5.6853     0.0000     -2096.4     -1021.2
Tot_Emp_TSD     41.824     78.833     0.5305     0.5958     -112.75      196.40
HH_MED_INC     -3658.0     520.50    -7.0278     0.0000     -4678.6     -2637.4
INC_U35     -1.094e+06  5.141e+05    -2.1289     0.0334  -2.102e+06   -8.64e+04
INC_35_100   4.856e+06  7.355e+05     6.6018     0.0000   3.413e+06   6.298e+06
TNC_FLAG     3.034e+07  1.611e+07     1.8831     0.0598  -1.252e+06   6.193e+07
Age_over64  -4.379e+05  1.184e+06    -0.3700     0.7114  -2.759e+06   1.883e+06
===============================================================================

/anaconda3/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

In [14]:
mod=PanelOLS.from_formula('upt \
                    ~ VRM \
                    + Tot_Pop \
                    + Pop_TSD \
                    + gasPrice \
                    + Total_HH \
                    + HH_0Veh \
                    + HH_1Veh \
                    + Tot_Emp_TSD \
                    + HH_MED_INC \
                    + INC_U35 \
                    +INC_35_100 \
                    +Age_over64',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    upt   R-squared:                        0.9308
Estimator:                   PanelOLS   R-squared (Between):              0.9363
No. Observations:                1684   R-squared (Within):              -2.1518
Date:                Wed, Sep 18 2019   R-squared (Overall):              0.9308
Time:                        14:02:19   Log-likelihood                -3.197e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      1873.1
Entities:                         156   P-value                           0.0000
Avg Obs:                       10.795   Distribution:                 F(12,1672)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):             1873.1
                                        P-value                           0.0000
Time periods:                      11   Distribution:                 F(12,1672)
Avg Obs:                       153.09
Min Obs:                       147.00
Max Obs:                       156.00

                              Parameter Estimates
===============================================================================
             Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------
VRM             139.78     1.1761     118.84     0.0000      137.47      142.08
Tot_Pop         12.364     20.826     0.5937     0.5528     -28.483      53.211
Pop_TSD         184.29     20.556     8.9655     0.0000      143.98      224.61
gasPrice     -5.23e+06  2.137e+06    -2.4474     0.0145  -9.422e+06  -1.039e+06
Total_HH        312.72     90.908     3.4400     0.0006      134.41      491.02
HH_0Veh        -2281.2     234.11    -9.7443     0.0000     -2740.4     -1822.1
HH_1Veh        -157.61     109.67    -1.4371     0.1509     -372.72      57.502
Tot_Emp_TSD    -818.75     35.402    -23.127     0.0000     -888.19     -749.32
HH_MED_INC      1500.9     186.66     8.0410     0.0000      1134.8      1867.0
INC_U35      9.862e+05  1.735e+05     5.6848     0.0000    6.46e+05   1.327e+06
INC_35_100  -2.509e+06   2.67e+05    -9.3973     0.0000  -3.033e+06  -1.985e+06
Age_over64   6.773e+05  4.004e+05     1.6914     0.0909  -1.081e+05   1.463e+06
===============================================================================

/anaconda3/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

In [11]:

#mod=PanelOLS.from_formula('upt \
#                    ~ VRM \
#                    + Tot_Pop \
#                    + Total_Labor_MSA \
#                    + gasPrice \
#                    ',data=new)
#res=mod.fit()
#print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    upt   R-squared:                        0.9508
Estimator:                   PanelOLS   R-squared (Between):              0.9586
No. Observations:                1249   R-squared (Within):              -0.6663
Date:                Tue, Sep 03 2019   R-squared (Overall):              0.9508
Time:                        10:12:31   Log-likelihood                 -1.78e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      6009.7
Entities:                         116   P-value                           0.0000
Avg Obs:                       10.767   Distribution:                  F(4,1245)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):             6009.7
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(4,1245)
Avg Obs:                       113.55
Min Obs:                       108.00
Max Obs:                       116.00

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
VRM                 2.7046     0.0226     119.88     0.0000      2.6603      2.7488
Tot_Pop            -0.0431     0.2091    -0.2060     0.8368     -0.4534      0.3672
Total_Labor_MSA    -0.6326     0.4103    -1.5416     0.1234     -1.4375      0.1724
gasPrice            5143.8     4607.0     1.1165     0.2644     -3894.6   1.418e+04
===================================================================================

/anaconda3/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

In [27]:
#NEW DATA
mod=PanelOLS.from_formula('upt \
                    ~ VRM \
                    + Tot_Pop \
                    + Total_Labor_MSA \
                    + gasPrice \
                    +TNC_FLAG \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    upt   R-squared:                        0.5149
Estimator:                   PanelOLS   R-squared (Between):              0.5186
No. Observations:                1249   R-squared (Within):              -0.8603
Date:                Wed, Sep 18 2019   R-squared (Overall):              0.5149
Time:                        14:16:07   Log-likelihood                -2.366e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      264.06
Entities:                         116   P-value                           0.0000
Avg Obs:                       10.767   Distribution:                  F(5,1244)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):             264.06
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(5,1244)
Avg Obs:                       113.55
Min Obs:                       108.00
Max Obs:                       116.00

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
VRM                 78.968     2.4475     32.265     0.0000      74.167      83.770
Tot_Pop             96.893     22.804     4.2489     0.0000      52.154      141.63
Total_Labor_MSA    -244.05     44.711    -5.4583     0.0000     -331.76     -156.33
gasPrice          1.73e+06   5.06e+05     3.4185     0.0007   7.371e+05   2.723e+06
TNC_FLAG         9.714e+05  4.716e+06     0.2060     0.8368  -8.281e+06   1.022e+07
===================================================================================

In [16]:
for col in new.columns:
    new[col+'_log'] = np.log(new[col]+1)

In [9]:
new.head(15)

                                CBSA  CBSA Code         UPT        VRM  \
Geography              Year
Abilene, TX Metro Area 2005  10180.0    10180.0    507165.0   444176.0
                       2006  10180.0    10180.0    493638.0   441300.0
                       2007  10180.0    10180.0    490254.0   424839.0
                       2008  10180.0    10180.0    473528.0   421757.0
                       2009  10180.0    10180.0    478743.0   418714.0
                       2010  10180.0    10180.0    456753.0   406871.0
                       2011  10180.0    10180.0    472931.0   396021.0
                       2012  10180.0    10180.0         0.0        0.0
                       2013  10180.0    10180.0         0.0        0.0
                       2014  10180.0    10180.0         0.0        0.0
                       2015  10180.0    10180.0         0.0        0.0
                       2016  10180.0        NaN         0.0        0.0
                       2017  10180.0        NaN         0.0        0.0
Akron, OH Metro Area   2005  20840.0    10420.0  13323764.0  8979752.0
                       2006  20840.0    10420.0  13450310.0  8850750.0

                                  UPT_ADJ       VRM_ADJ  FARE_TOTAL  \
Geography              Year
Abilene, TX Metro Area 2005  5.071650e+05  4.441760e+05    213965.0
                       2006  4.936380e+05  4.413000e+05    201795.0
                       2007  4.902540e+05  4.248390e+05    217336.0
                       2008  4.735280e+05  4.217570e+05    254879.0
                       2009  4.787430e+05  4.187140e+05    248600.0
                       2010  4.567530e+05  4.068710e+05    295374.0
                       2011  4.729310e+05  3.960210e+05    375006.0
                       2012  0.000000e+00  0.000000e+00    368226.0
                       2013  0.000000e+00  0.000000e+00    390511.0
                       2014  0.000000e+00  0.000000e+00    408104.0
                       2015  0.000000e+00  0.000000e+00    294009.0
                       2016  0.000000e+00  0.000000e+00    166398.0
                       2017  0.000000e+00  0.000000e+00    191017.0
Akron, OH Metro Area   2005  1.202736e+07  8.106022e+06   3022880.0
                       2006  1.214159e+07  7.989572e+06   3163036.0

                             FARE_per_UPT      POPPT      HUPT        AREAPT  \
Geography              Year
Abilene, TX Metro Area 2005      0.421884   110421.0   46732.0  1.427442e+08
                       2006      0.408791   110421.0   46732.0  1.427442e+08
                       2007      0.443313   110421.0   46732.0  1.427442e+08
                       2008      0.538255   110421.0   46732.0  1.427442e+08
                       2009      0.519277   110421.0   46732.0  1.427442e+08
                       2010      0.646682   110421.0   46732.0  1.427442e+08
                       2011      0.792940   110421.0   46732.0  1.427442e+08
                       2012           inf   110421.0   46732.0  1.427442e+08
                       2013           inf   110421.0   46732.0  1.427442e+08
                       2014           inf   110421.0   46732.0  1.427442e+08
                       2015           inf   110421.0   46732.0  1.427442e+08
                       2016           inf   110421.0   46732.0  1.427442e+08
                       2017           inf   110421.0   46732.0  1.427442e+08
Akron, OH Metro Area   2005      0.453758  1028190.0  470038.0  1.523085e+09
                       2006      0.470329  1028190.0  470038.0  1.523085e+09

                               AREALANDPT      UAPOP      UAHU        UAAREA  \
Geography              Year
Abilene, TX Metro Area 2005  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2006  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2007  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2008  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2009  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2010  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2011  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2012  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2013  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2014  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2015  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2016  1.417561e+08   110421.0   46732.0  1.427442e+08
                       2017  1.417561e+08   110421.0   46732.0  1.427442e+08
Akron, OH Metro Area   2005  1.489269e+09  1138998.0  515318.0  1.720311e+09
                       2006  1.489269e+09  1138998.0  515318.0  1.720311e+09

                               UAAREALAND       MPOP       MHU         MAREA  \
Geography              Year
Abilene, TX Metro Area 2005  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2006  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2007  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2008  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2009  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2010  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2011  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2012  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2013  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2014  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2015  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2016  1.417561e+08   165252.0   69721.0  7.142425e+09
                       2017  1.417561e+08   165252.0   69721.0  7.142425e+09
Akron, OH Metro Area   2005  1.685446e+09  1406400.0  625162.0  4.786916e+09
                       2006  1.685446e+09  1406400.0  625162.0  4.786916e+09

                                MAREALAND  UAPOPPCT  UAHUPCT  UAAREAPCT  \
Geography              Year
Abilene, TX Metro Area 2005  7.105575e+09    100.00   100.00     100.00
                       2006  7.105575e+09    100.00   100.00     100.00
                       2007  7.105575e+09    100.00   100.00     100.00
                       2008  7.105575e+09    100.00   100.00     100.00
                       2009  7.105575e+09    100.00   100.00     100.00
                       2010  7.105575e+09    100.00   100.00     100.00
                       2011  7.105575e+09    100.00   100.00     100.00
                       2012  7.105575e+09    100.00   100.00     100.00
                       2013  7.105575e+09    100.00   100.00     100.00
                       2014  7.105575e+09    100.00   100.00     100.00
                       2015  7.105575e+09    100.00   100.00     100.00
                       2016  7.105575e+09    100.00   100.00     100.00
                       2017  7.105575e+09    100.00   100.00     100.00
Akron, OH Metro Area   2005  4.662647e+09    180.54   182.42     177.08
                       2006  4.662647e+09    180.54   182.42     177.08

                             UAAREALANDPCT  MPOPPCT  MHUPCT  MAREAPCT  \
Geography              Year
Abilene, TX Metro Area 2005         100.00    66.82   67.03      2.00
                       2006         100.00    66.82   67.03      2.00
                       2007         100.00    66.82   67.03      2.00
                       2008         100.00    66.82   67.03      2.00
                       2009         100.00    66.82   67.03      2.00
                       2010         100.00    66.82   67.03      2.00
                       2011         100.00    66.82   67.03      2.00
                       2012         100.00    66.82   67.03      2.00
                       2013         100.00    66.82   67.03      2.00
                       2014         100.00    66.82   67.03      2.00
                       2015         100.00    66.82   67.03      2.00
                       2016         100.00    66.82   67.03      2.00
                       2017         100.00    66.82   67.03      2.00
Akron, OH Metro Area   2005         176.72   146.22  150.38     63.64
                       2006         176.72   146.22  150.38     63.64

                             MAREALANDPCT  Total_HH  HH_0Veh  HH_1Veh  \
Geography              Year
Abilene, TX Metro Area 2005          1.99   60532.0   2175.0  23133.0
                       2006          1.99   59850.0   2356.0  21689.0
                       2007          1.99   60692.0   3218.0  20497.0
                       2008          1.99   59960.0   2164.0  22931.0
                       2009          1.99   58052.0   3724.0  20561.0
                       2010          1.99   59857.0   4672.0  18972.0
                       2011          1.99   58974.0   4119.0  21753.0
                       2012          1.99   60066.0   3268.0  21030.0
                       2013          1.99   60588.0   3361.0  22377.0
                       2014          1.99   59932.0   2056.0  22178.0
                       2015          1.99   59372.0   3004.0  20918.0
                       2016          1.99   59263.0   4162.0  20643.0
                       2017          1.99   61603.0   2935.0  20387.0
Akron, OH Metro Area   2005         63.88  276416.0  20661.0  85198.0
                       2006         63.88  280837.0  19248.0  97567.0

                              HH_2Veh  HH_3Veh  HH_4+Veh   Pop_TSD  \
Geography              Year
Abilene, TX Metro Area 2005   24645.0   7899.0    2680.0    3976.5
                       2006   25837.0   7647.0    2321.0    3984.0
                       2007   25691.0   8228.0    3058.0    3991.5
                       2008   24732.0   7910.0    2223.0    3999.0
                       2009   21354.0   8712.0    3701.0    4006.5
                       2010   24464.0   8253.0    3496.0    4014.0
                       2011   22514.0   8101.0    2487.0    4021.5
                       2012   24744.0   7973.0    3051.0    4029.0
                       2013   22363.0   9673.0    2814.0    4036.5
                       2014   24905.0   8001.0    2792.0    4044.0
                       2015   24663.0   7364.0    3423.0    4051.5
                       2016   24437.0   7454.0    2567.0       NaN
                       2017   26759.0   7306.0    4216.0       NaN
Akron, OH Metro Area   2005  112380.0  40847.0   17330.0  100521.5
                       2006  109326.0  38795.0   15901.0   99593.0

                             Tot_Emp_TSD  Tot_Retail_TSD  gasPrice  \
Geography              Year
Abilene, TX Metro Area 2005       5505.0           250.0  2.231750
                       2006       5469.0           276.0  2.520667
                       2007       5735.0           273.0  2.719000
                       2008       5883.0           335.0  3.193333
                       2009       5831.0           312.0  2.270333
                       2010       5731.0           314.0  2.700417
                       2011       5344.0           301.0  3.422750
                       2012       4982.0           324.0  3.485667
                       2013       4982.0           307.0  3.374167
                       2014       4905.0           305.0  3.223167
                       2015       4847.0           352.0  2.250083
                       2016          NaN             NaN       NaN
                       2017          NaN             NaN       NaN
Akron, OH Metro Area   2005      41364.0          4110.0  2.246667
                       2006      43378.0          3771.0  2.544250

                             HH_MED_INC  HH_MEAN_INC  INC_U35  INC_35_100  \
Geography              Year
Abilene, TX Metro Area 2005     35535.0      45619.0     49.3        42.5
                       2006     39784.0      52364.0     44.0        46.1
                       2007     39369.0      51693.0     44.1        46.0
                       2008     41961.0      58191.0     39.6        48.3
                       2009     42931.0      54998.0     41.4        46.8
                       2010     40630.0      55007.0     41.6        45.2
                       2011     40659.0      52221.0     44.1        44.9
                       2012     43407.0      60465.0     41.0        45.2
                       2013     44149.0      57937.0     40.1        45.9
                       2014     44303.0      61532.0     38.8        46.2
                       2015     47420.0      65183.0     37.1        45.3
                       2016     48016.0      62145.0     35.9        47.8
                       2017     51130.0      68263.0     34.9        42.6
Akron, OH Metro Area   2005     44719.0      58676.0     38.7        46.8
                       2006     44507.0      58859.0     38.8        47.2

                             INC_100P   Tot_Pop  Tot_Instate_Pop  \
Geography              Year
Abilene, TX Metro Area 2005       8.2  146427.0         105269.0
                       2006       9.9  158548.0         113266.0
                       2007       9.9  159439.0         111201.0
                       2008      12.1  160012.0         111912.0
                       2009      11.8  160266.0         108498.0
                       2010      13.2  164941.0         119325.0
                       2011      11.0  165858.0         116692.0
                       2012      13.8  167800.0         120747.0
                       2013      14.0  168144.0         122980.0
                       2014      15.0  166900.0         115664.0
                       2015      17.6  168922.0         114679.0
                       2016      16.3  170860.0         121500.0
                       2017      22.5  169747.0         112306.0
Akron, OH Metro Area   2005      14.5  684459.0         521491.0
                       2006      14.0  700943.0         530777.0

                             Tot_Outstate_Pop  Tot_NonUSA_POP  \
Geography              Year
Abilene, TX Metro Area 2005           33286.0          2591.0
                       2006           37165.0          2023.0
                       2007           37761.0          3496.0
                       2008           38496.0          3609.0
                       2009           38872.0          3335.0
                       2010           34176.0          2316.0
                       2011           38331.0          2204.0
                       2012           36919.0          1478.0
                       2013           35701.0          1501.0
                       2014           42262.0          2071.0
                       2015           42353.0          3164.0
                       2016           38241.0          2054.0
                       2017           42683.0          2935.0
Akron, OH Metro Area   2005          138184.0          2945.0
                       2006          139714.0          4695.0

                             Total_Median_Income_Individual  \
Geography              Year
Abilene, TX Metro Area 2005                         20297.0
                       2006                         20570.0
                       2007                         20408.0
                       2008                         23692.0
                       2009                         21670.0
                       2010                         21125.0
                       2011                         20936.0
                       2012                         22600.0
                       2013                         20994.0
                       2014                         21906.0
                       2015                         23214.0
                       2016                         23641.0
                       2017                         25356.0
Akron, OH Metro Area   2005                         24612.0
                       2006                         23925.0

                             Native_Instate_Med_Inc_Indiv  \
Geography              Year
Abilene, TX Metro Area 2005                       20244.0
                       2006                       19222.0
                       2007                       18921.0
                       2008                       21792.0
                       2009                       20923.0
                       2010                       20803.0
                       2011                       21009.0
                       2012                       22119.0
                       2013                       20714.0
                       2014                       21670.0
                       2015                       22370.0
                       2016                       22515.0
                       2017                       24420.0
Akron, OH Metro Area   2005                       24899.0
                       2006                       24129.0

                             Native_Outstate_Med_Inc_Indiv  Total_Pop_Poverty  \
Geography              Year
Abilene, TX Metro Area 2005                        21328.0           146258.0
                       2006                        22110.0           146298.0
                       2007                        25843.0           144006.0
                       2008                        29631.0           147245.0
                       2009                        26456.0           148662.0
                       2010                        22031.0           150256.0
                       2011                        21496.0           151022.0
                       2012                        25407.0           156020.0
                       2013                        24156.0           154458.0
                       2014                        21892.0           153923.0
                       2015                        25319.0           155267.0
                       2016                        26728.0           156642.0
                       2017                        30638.0           156245.0
Akron, OH Metro Area   2005                        24755.0           683742.0
                       2006                        23644.0           684898.0

                             Pop_Below100_Poverty  Pop_Below150_Poverty  \
Geography              Year
Abilene, TX Metro Area 2005                  17.6                  12.7
                       2006                  15.8                  13.3
                       2007                  15.1                  10.8
                       2008                  16.1                  10.4
                       2009                  14.5                  11.6
                       2010                   NaN                   NaN
                       2011                   NaN                   NaN
                       2012                   NaN                   NaN
                       2013                  16.8                  12.6
                       2014                  16.5                  11.3
                       2015                  13.9                  11.6
                       2016                  17.2                  10.7
                       2017                  15.0                  10.9
Akron, OH Metro Area   2005                  11.3                   8.1
                       2006                  12.7                   7.8

                             Pop_Above150_Poverty  Age_under18  Age_18to64  \
Geography              Year
Abilene, TX Metro Area 2005                  69.7         26.9        59.4
                       2006                  70.9         25.2        61.2
                       2007                  74.1         24.7        61.6
                       2008                  73.6         24.6        62.2
                       2009                  74.0         24.0        62.7

In [17]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + Total_Labor_MSA_log \
                    + gasPrice_log \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9984
Estimator:                   PanelOLS   R-squared (Between):              0.9989
No. Observations:                1249   R-squared (Within):               0.9645
Date:                Tue, Sep 03 2019   R-squared (Overall):              0.9984
Time:                        10:16:59   Log-likelihood                   -862.41
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.954e+05
Entities:                         116   P-value                           0.0000
Avg Obs:                       10.767   Distribution:                  F(4,1245)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):          1.954e+05
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(4,1245)
Avg Obs:                       113.55
Min Obs:                       108.00
Max Obs:                       116.00

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
VRM_log                 1.0602     0.0077     138.54     0.0000      1.0452      1.0753
Tot_Pop_log            -0.9154     0.1160    -7.8925     0.0000     -1.1430     -0.6879
Total_Labor_MSA_log     0.8872     0.1194     7.4323     0.0000      0.6530      1.1214
gasPrice_log            0.4769     0.0934     5.1079     0.0000      0.2937      0.6601
=======================================================================================

In [18]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + Total_Labor_MSA_log \
                    + gasPrice_log \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9984
Estimator:                   PanelOLS   R-squared (Between):              0.9987
No. Observations:                1249   R-squared (Within):               0.9744
Date:                Wed, Sep 18 2019   R-squared (Overall):              0.9984
Time:                        14:03:30   Log-likelihood                   -1118.3
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.941e+05
Entities:                         116   P-value                           0.0000
Avg Obs:                       10.767   Distribution:                  F(4,1245)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):          1.941e+05
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(4,1245)
Avg Obs:                       113.55
Min Obs:                       108.00
Max Obs:                       116.00

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
VRM_log                 1.2631     0.0094     134.47     0.0000      1.2447      1.2815
Tot_Pop_log            -0.4862     0.1424    -3.4153     0.0007     -0.7655     -0.2069
Total_Labor_MSA_log     0.4273     0.1465     2.9161     0.0036      0.1398      0.7147
gasPrice_log            0.7795     0.1146     6.8022     0.0000      0.5547      1.0043
=======================================================================================

In [20]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + gasPrice_log \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9985
Estimator:                   PanelOLS   R-squared (Between):              0.9989
No. Observations:                1684   R-squared (Within):               0.9620
Date:                Tue, Sep 03 2019   R-squared (Overall):              0.9985
Time:                        10:22:28   Log-likelihood                   -1162.3
Cov. Estimator:            Unadjusted
                                        F-statistic:                   3.769e+05
Entities:                         156   P-value                           0.0000
Avg Obs:                       10.795   Distribution:                  F(3,1681)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):          3.769e+05
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(3,1681)
Avg Obs:                       153.09
Min Obs:                       147.00
Max Obs:                       156.00

                              Parameter Estimates
================================================================================
              Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------
VRM_log          1.1022     0.0070     157.86     0.0000      1.0885      1.1158
Tot_Pop_log     -0.0599     0.0100    -5.9902     0.0000     -0.0795     -0.0403
gasPrice_log     0.0387     0.0736     0.5253     0.5994     -0.1057      0.1830
================================================================================

In [19]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + gasPrice_log \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9985
Estimator:                   PanelOLS   R-squared (Between):              0.9987
No. Observations:                1684   R-squared (Within):               0.9740
Date:                Wed, Sep 18 2019   R-squared (Overall):              0.9985
Time:                        14:04:05   Log-likelihood                   -1530.3
Cov. Estimator:            Unadjusted
                                        F-statistic:                   3.629e+05
Entities:                         156   P-value                           0.0000
Avg Obs:                       10.795   Distribution:                  F(3,1681)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):          3.629e+05
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(3,1681)
Avg Obs:                       153.09
Min Obs:                       147.00
Max Obs:                       156.00

                              Parameter Estimates
================================================================================
              Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------
VRM_log          1.2962     0.0087     149.21     0.0000      1.2792      1.3132
Tot_Pop_log     -0.0542     0.0124    -4.3602     0.0000     -0.0786     -0.0298
gasPrice_log     0.3051     0.0916     3.3317     0.0009      0.1255      0.4847
================================================================================

In [21]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + gasPrice_log \
                    + EntityEffects \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9660
Estimator:                   PanelOLS   R-squared (Between):              0.9786
No. Observations:                1684   R-squared (Within):               0.9660
Date:                Tue, Sep 03 2019   R-squared (Overall):              0.9785
Time:                        10:22:51   Log-likelihood                    17.593
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.444e+04
Entities:                         156   P-value                           0.0000
Avg Obs:                       10.795   Distribution:                  F(3,1525)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):          1.444e+04
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(3,1525)
Avg Obs:                       153.09
Min Obs:                       147.00
Max Obs:                       156.00

                              Parameter Estimates
================================================================================
              Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------
VRM_log          1.0381     0.0051     201.93     0.0000      1.0280      1.0482
Tot_Pop_log      0.1019     0.1248     0.8171     0.4140     -0.1428      0.3467
gasPrice_log     0.3629     0.0524     6.9221     0.0000      0.2601      0.4658
================================================================================

F-test for Poolability: 29.490
P-value: 0.0000
Distribution: F(155,1525)

Included effects: Entity

In [20]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + gasPrice_log \
                    + EntityEffects \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9746
Estimator:                   PanelOLS   R-squared (Between):              0.9985
No. Observations:                1684   R-squared (Within):               0.9746
Date:                Wed, Sep 18 2019   R-squared (Overall):              0.9982
Time:                        14:04:33   Log-likelihood                   -56.591
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.951e+04
Entities:                         156   P-value                           0.0000
Avg Obs:                       10.795   Distribution:                  F(3,1525)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):          1.951e+04
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(3,1525)
Avg Obs:                       153.09
Min Obs:                       147.00
Max Obs:                       156.00

                              Parameter Estimates
================================================================================
              Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------
VRM_log          1.2640     0.0054     235.28     0.0000      1.2534      1.2745
Tot_Pop_log     -0.0482     0.1304    -0.3700     0.7114     -0.3040      0.2075
gasPrice_log     0.3638     0.0548     6.6396     0.0000      0.2563      0.4713
================================================================================

F-test for Poolability: 46.612
P-value: 0.0000
Distribution: F(155,1525)

Included effects: Entity

In [22]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + gasPrice_log \
                    + EntityEffects \
                    + TimeEffects \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9626
Estimator:                   PanelOLS   R-squared (Between):              0.9968
No. Observations:                1684   R-squared (Within):               0.9653
Date:                Tue, Sep 03 2019   R-squared (Overall):              0.9965
Time:                        10:24:07   Log-likelihood                    23.413
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.299e+04
Entities:                         156   P-value                           0.0000
Avg Obs:                       10.795   Distribution:                  F(3,1515)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):          1.299e+04
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(3,1515)
Avg Obs:                       153.09
Min Obs:                       147.00
Max Obs:                       156.00

                              Parameter Estimates
================================================================================
              Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------
VRM_log          1.0363     0.0052     197.40     0.0000      1.0260      1.0466
Tot_Pop_log     -0.1080     0.1532    -0.7050     0.4809     -0.4086      0.1925
gasPrice_log     0.6592     0.4704     1.4013     0.1613     -0.2636      1.5820
================================================================================

F-test for Poolability: 27.775
P-value: 0.0000
Distribution: F(165,1515)

Included effects: Entity, Time

In [25]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + gasPrice_log \
                    + Total_Labor_MSA_log \
                    + EntityEffects \
                    + TimeEffects \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9614
Estimator:                   PanelOLS   R-squared (Between):              0.9915
No. Observations:                1249   R-squared (Within):               0.9656
Date:                Tue, Sep 03 2019   R-squared (Overall):              0.9912
Time:                        10:27:32   Log-likelihood                   -130.10
Cov. Estimator:            Unadjusted
                                        F-statistic:                      6961.9
Entities:                         116   P-value                           0.0000
Avg Obs:                       10.767   Distribution:                  F(4,1119)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):             6961.9
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(4,1119)
Avg Obs:                       113.55
Min Obs:                       108.00
Max Obs:                       116.00

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
VRM_log                 1.0311     0.0062     166.64     0.0000      1.0189      1.0432
Tot_Pop_log            -0.2381     0.2081    -1.1442     0.2528     -0.6463      0.1702
gasPrice_log            0.7036     0.5958     1.1810     0.2379     -0.4654      1.8726
Total_Labor_MSA_log     0.0890     0.2830     0.3146     0.7531     -0.4662      0.6443
=======================================================================================

F-test for Poolability: 19.966
P-value: 0.0000
Distribution: F(125,1119)

Included effects: Entity, Time

/anaconda3/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

In [21]:
mod=PanelOLS.from_formula('upt_log \
                    ~ VRM_log \
                    + Tot_Pop_log \
                    + gasPrice_log \
                    + Total_Labor_MSA_log \
                    + EntityEffects \
                    + TimeEffects \
                    ',data=new)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                upt_log   R-squared:                        0.9716
Estimator:                   PanelOLS   R-squared (Between):              0.9552
No. Observations:                1249   R-squared (Within):               0.9748
Date:                Wed, Sep 18 2019   R-squared (Overall):              0.9555
Time:                        14:05:57   Log-likelihood                   -181.77
Cov. Estimator:            Unadjusted
                                        F-statistic:                      9567.7
Entities:                         116   P-value                           0.0000
Avg Obs:                       10.767   Distribution:                  F(4,1119)
Min Obs:                       6.0000
Max Obs:                       11.000   F-statistic (robust):             9567.7
                                        P-value                           0.0000
Time periods:                      11   Distribution:                  F(4,1119)
Avg Obs:                       113.55
Min Obs:                       108.00
Max Obs:                       116.00

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
VRM_log                 1.2596     0.0064     195.34     0.0000      1.2470      1.2723
Tot_Pop_log            -0.2975     0.2169    -1.3720     0.1703     -0.7230      0.1280
gasPrice_log            0.6141     0.6209     0.9889     0.3229     -0.6043      1.8324
Total_Labor_MSA_log    -0.0040     0.2949    -0.0135     0.9893     -0.5826      0.5747
=======================================================================================

F-test for Poolability: 30.925
P-value: 0.0000
Distribution: F(125,1119)

Included effects: Entity, Time