In [2]:
import pandas as pd
import numpy as np
pd.options.display.max_columns=100

In [3]:
est_file=pd.read_csv('../Factors and Ridership Data/Estimation_File/estimation_file.csv')
est_file.head()

/Users/rianajawad/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (139,148) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,CBSA,Mode,Year,MNAME,PROBLEM_FLAG,NOTE,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,FARE_ADJ_ORIGINAL,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,...,Rail_FARE_per_UPT_2018_diff,Rail_FARE_per_UPT_2018_log,PCT_Rail_FARE_per_UPT_2018_rel_diff,Rail_FARE_per_UPT_2018_scale,Rail_AVG_SPEED,Rail_AVG_SPEED_diff,Rail_AVG_SPEED_log,PCT_Rail_AVG_SPEED_rel_diff,Rail_AVG_SPEED_scale,CLUSTER_GT_NEW_11,CLUSTER_GT_ORIGINAL,CLUSTER_GT_8_GROUPS,CLUSTER_APTA,CLUSTER_NOTE,TOTAL_EMPLOYMENT,JTW_DA_PCT,JTW_CARPOOLED_PCT,JTW_TRANSIT_PCT,JTW_WALK_PCT,JTW_BICYCLE_PCT,JTW_OTHER_PCT,JTW_HOME_PCT,NOTE_JTW,min_year,VRM_ADJ_LAGGED_1,VRM_ADJ_LAGGED_2,VRM_ADJ_LAGGED_3,FARE_per_UPT_LAGGED_1,FARE_per_UPT_LAGGED_2,FARE_per_UPT_LAGGED_3,AVG_SPEED_LAGGED_1,AVG_SPEED_LAGGED_2,AVG_SPEED_LAGGED_3,TNC_FLAG_LAGGED_1,TNC_FLAG_LAGGED_2,TNC_FLAG_LAGGED_3,FARE_per_UPT_2018_LAGGED_1,FARE_per_UPT_2018_LAGGED_2,FARE_per_UPT_2018_LAGGED_3,dockCt_LAGGED_1,dockCt_LAGGED_2,dockCt_LAGGED_3,docklessCt_LAGGED_1,docklessCt_LAGGED_2,docklessCt_LAGGED_3,scooterCt_LAGGED_1,scooterCt_LAGGED_2,scooterCt_LAGGED_3,TNC_FLAG_LAGGED_4,TNC_FLAG_LAGGED_5
0,0,10420,Bus,2002,"Akron, OH Metro Area",NaN,NaN,5226385.660,4026372.388,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,2.860637e+06,744634347,646583.7344,496141.0469,137193.6719,-389.53125,25405.20313,26028.32813,26651.07813,7117.03125,682354.11,7.55,8.94,83.85,24.64,62.9,12.46,265452.20,22830.14,58254.52,117083.25,46891.53,20392.77,8.60,43046.82813,55300.5625,39.49,46.56,13.95,21948.42,346147.17,368095.58,5.96,94.04,1.36,NaN,...,0.0,0.0,0.0,-23.689697,0.0,0.0,0.0,0.0,-62,1,1,H,24,NaN,309488.2031,87.4,6.2,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,0.000,0.000,0.000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0
1,1,10420,Bus,2003,"Akron, OH Metro Area",NaN,NaN,5395901.888,3976568.624,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,1.145302e+07,744634347,659397.0625,504631.8125,137582.3125,753.12500,25120.18750,25632.68750,25995.68750,10350.875,682850.56,8.81,8.66,82.79,24.33,63.0,12.68,269144.19,22073.44,67400.94,115443.00,44874.88,19351.94,8.20,43566.68750,56379.7500,39.24,46.66,14.10,23342.50,348574.17,371916.67,6.28,93.72,1.55,NaN,...,0.0,0.0,0.0,-23.689697,0.0,0.0,0.0,0.0,-62,1,1,H,24,NaN,316497.1875,87.2,6.4,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,4026372.388,0.000,0.000,0.5473,0.0000,0.0000,14.88,0.00,0.00,0,0,0,0.766220,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0
2,2,10420,Bus,2004,"Akron, OH Metro Area",NaN,NaN,5907162.281,4315392.555,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,1.101674e+07,744634347,672492.7500,513183.7500,138058.7500,1942.50000,24804.25000,25208.25000,25305.25000,13527.5,683397.75,10.08,8.38,81.73,24.00,63.1,12.90,272892.25,21266.25,76795.25,113694.00,42855.50,18281.25,7.79,44030.25000,57390.0000,39.03,46.78,14.20,23471.75,351723.75,375195.50,6.26,93.74,1.83,NaN,...,0.0,0.0,0.0,-23.689697,0.0,0.0,0.0,0.0,-62,1,1,H,24,NaN,323744.25,86.9,6.7,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,3976568.624,4026372.388,0.000,2.1225,0.5473,0.0000,14.71,14.88,0.00,0,0,0,2.907825,0.766220,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0
3,3,10420,Bus,2005,"Akron, OH Metro Area",NaN,NaN,6013680.881,4053011.065,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,1.342394e+07,744634347,684459.0000,521491.0000,138184.0000,2945.00000,24612.00000,24899.00000,24755.00000,16933,683742.00,11.30,8.10,80.70,23.70,63.2,13.10,276416.00,20661.00,85198.00,112380.00,40847.00,17330.00,7.47,44719.00000,58676.0000,38.70,46.80,14.50,22420.75,358105.92,380526.67,5.90,94.10,2.25,13644.8,...,0.0,0.0,0.0,-23.689697,0.0,0.0,0.0,0.0,-62,1,1,H,24,NaN,330039,86.8,6.8,0.8,1.7,0.1,0.7,3.1,NaN,2002,4315392.555,3976568.624,4026372.388,1.8650,2.1225,0.5473,7.23,14.71,14.88,0,0,0,2.480450,2.907825,0.766220,0,0,0,0,0,0,0,0,0,0.0,0.0
4,4,10420,Bus,2006,"Akron, OH Metro Area",NaN,NaN,6070797.419,3994786.013,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,1.400910e+07,744634347,700943.0000,530777.0000,139714.0000,4695.00000,23925.00000,24129.00000,23644.00000,19423,684898.00,12.70,7.80,79.50,23.30,63.3,13.40,280837.00,19248.00,97567.00,109326.00,38795.00,15901.00,6.85,44507.00000,58859.0000,38.80,47.20,14.00,20348.08,365133.33,385481.42,5.28,94.72,2.54,13644.8,...,0.0,0.0,0.0,-23.689697,0.0,0.0,0.0,0.0,-62,1,1,H,24,NaN,340143,85.8,7.3,1.3,2.2,0,0.9,2.5,NaN,2002,4053011.065,4315392.555,3976568.624,2.2322,1.8650,2.1225,14.40,7.23,14.71,0,0,0,2.879538,2.480450,2.907825,0,0,0,0,0,0,0,0,0,0.0,0.0

In [7]:
rail=est_file[est_file['Mode']=='Rail']
bus=est_file[est_file['Mode']=='Bus']

In [8]:
rail=rail[['CBSA','Year','UPT_ADJ','VRM_ADJ','VRH_ADJ','FARE_ADJ','FARE_per_UPT','AVG_SPEED']]
bus=bus[['CBSA','Year','UPT_ADJ','VRM_ADJ','VRH_ADJ','FARE_ADJ','FARE_per_UPT','AVG_SPEED']]


bus.head()

,CBSA,Year,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,AVG_SPEED
0,10420,2002,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,14.88
1,10420,2003,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,14.71
2,10420,2004,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,7.23
3,10420,2005,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,14.40
4,10420,2006,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,14.19

In [10]:
test=pd.merge(rail,bus,how='outer',indicator=True)
test.head()

,CBSA,Year,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,AVG_SPEED,_merge
0,10740,2009,1351087.0,813885.0,20107.0,18688103.0,13.8319,40.48,left_only
1,10740,2010,1165687.0,1415143.0,37249.0,19923547.0,17.0917,37.99,left_only
2,10740,2011,1242174.0,1370680.0,36676.0,19993841.0,16.0958,37.37,left_only
3,10740,2012,1129303.0,1424748.0,36870.0,18315395.0,16.2183,38.64,left_only
4,10740,2013,1082588.0,1388562.0,36503.0,21020496.0,19.4169,38.04,left_only

In [11]:
test[test['_merge']=='both']

Empty DataFrame
Columns: [CBSA, Year, UPT_ADJ, VRM_ADJ, VRH_ADJ, FARE_ADJ, FARE_per_UPT, AVG_SPEED, _merge]
Index: []

In [13]:
new_est=pd.merge(est_file,rail,on=['CBSA','Year'],suffixes=('','_COMPETING_RAIL'),how='left')
new_est.head()

,Unnamed: 0,CBSA,Mode,Year,MNAME,PROBLEM_FLAG,NOTE,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,FARE_ADJ_ORIGINAL,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,...,Rail_AVG_SPEED_log,PCT_Rail_AVG_SPEED_rel_diff,Rail_AVG_SPEED_scale,CLUSTER_GT_NEW_11,CLUSTER_GT_ORIGINAL,CLUSTER_GT_8_GROUPS,CLUSTER_APTA,CLUSTER_NOTE,TOTAL_EMPLOYMENT,JTW_DA_PCT,JTW_CARPOOLED_PCT,JTW_TRANSIT_PCT,JTW_WALK_PCT,JTW_BICYCLE_PCT,JTW_OTHER_PCT,JTW_HOME_PCT,NOTE_JTW,min_year,VRM_ADJ_LAGGED_1,VRM_ADJ_LAGGED_2,VRM_ADJ_LAGGED_3,FARE_per_UPT_LAGGED_1,FARE_per_UPT_LAGGED_2,FARE_per_UPT_LAGGED_3,AVG_SPEED_LAGGED_1,AVG_SPEED_LAGGED_2,AVG_SPEED_LAGGED_3,TNC_FLAG_LAGGED_1,TNC_FLAG_LAGGED_2,TNC_FLAG_LAGGED_3,FARE_per_UPT_2018_LAGGED_1,FARE_per_UPT_2018_LAGGED_2,FARE_per_UPT_2018_LAGGED_3,dockCt_LAGGED_1,dockCt_LAGGED_2,dockCt_LAGGED_3,docklessCt_LAGGED_1,docklessCt_LAGGED_2,docklessCt_LAGGED_3,scooterCt_LAGGED_1,scooterCt_LAGGED_2,scooterCt_LAGGED_3,TNC_FLAG_LAGGED_4,TNC_FLAG_LAGGED_5,UPT_ADJ_COMPETING_RAIL,VRM_ADJ_COMPETING_RAIL,VRH_ADJ_COMPETING_RAIL,FARE_ADJ_COMPETING_RAIL,FARE_per_UPT_COMPETING_RAIL,AVG_SPEED_COMPETING_RAIL
0,0,10420,Bus,2002,"Akron, OH Metro Area",NaN,NaN,5226385.660,4026372.388,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,2.860637e+06,744634347,646583.7344,496141.0469,137193.6719,-389.53125,25405.20313,26028.32813,26651.07813,7117.03125,682354.11,7.55,8.94,83.85,24.64,62.9,12.46,265452.20,22830.14,58254.52,117083.25,46891.53,20392.77,8.60,43046.82813,55300.5625,39.49,46.56,13.95,21948.42,346147.17,368095.58,5.96,94.04,1.36,NaN,...,0.0,0.0,-62,1,1,H,24,NaN,309488.2031,87.4,6.2,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,0.000,0.000,0.000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,10420,Bus,2003,"Akron, OH Metro Area",NaN,NaN,5395901.888,3976568.624,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,1.145302e+07,744634347,659397.0625,504631.8125,137582.3125,753.12500,25120.18750,25632.68750,25995.68750,10350.875,682850.56,8.81,8.66,82.79,24.33,63.0,12.68,269144.19,22073.44,67400.94,115443.00,44874.88,19351.94,8.20,43566.68750,56379.7500,39.24,46.66,14.10,23342.50,348574.17,371916.67,6.28,93.72,1.55,NaN,...,0.0,0.0,-62,1,1,H,24,NaN,316497.1875,87.2,6.4,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,4026372.388,0.000,0.000,0.5473,0.0000,0.0000,14.88,0.00,0.00,0,0,0,0.766220,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,10420,Bus,2004,"Akron, OH Metro Area",NaN,NaN,5907162.281,4315392.555,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,1.101674e+07,744634347,672492.7500,513183.7500,138058.7500,1942.50000,24804.25000,25208.25000,25305.25000,13527.5,683397.75,10.08,8.38,81.73,24.00,63.1,12.90,272892.25,21266.25,76795.25,113694.00,42855.50,18281.25,7.79,44030.25000,57390.0000,39.03,46.78,14.20,23471.75,351723.75,375195.50,6.26,93.74,1.83,NaN,...,0.0,0.0,-62,1,1,H,24,NaN,323744.25,86.9,6.7,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,3976568.624,4026372.388,0.000,2.1225,0.5473,0.0000,14.71,14.88,0.00,0,0,0,2.907825,0.766220,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10420,Bus,2005,"Akron, OH Metro Area",NaN,NaN,6013680.881,4053011.065,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,1.342394e+07,744634347,684459.0000,521491.0000,138184.0000,2945.00000,24612.00000,24899.00000,24755.00000,16933,683742.00,11.30,8.10,80.70,23.70,63.2,13.10,276416.00,20661.00,85198.00,112380.00,40847.00,17330.00,7.47,44719.00000,58676.0000,38.70,46.80,14.50,22420.75,358105.92,380526.67,5.90,94.10,2.25,13644.8,...,0.0,0.0,-62,1,1,H,24,NaN,330039,86.8,6.8,0.8,1.7,0.1,0.7,3.1,NaN,2002,4315392.555,3976568.624,4026372.388,1.8650,2.1225,0.5473,7.23,14.71,14.88,0,0,0,2.480450,2.907825,0.766220,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,10420,Bus,2006,"Akron, OH Metro Area",NaN,NaN,6070797.419,3994786.013,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,1.400910e+07,744634347,700943.0000,530777.0000,139714.0000,4695.00000,23925.00000,24129.00000,23644.00000,19423,684898.00,12.70,7.80,79.50,23.30,63.3,13.40,280837.00,19248.00,97567.00,109326.00,38795.00,15901.00,6.85,44507.00000,58859.0000,38.80,47.20,14.00,20348.08,365133.33,385481.42,5.28,94.72,2.54,13644.8,...,0.0,0.0,-62,1,1,H,24,NaN,340143,85.8,7.3,1.3,2.2,0,0.9,2.5,NaN,2002,4053011.065,4315392.555,3976568.624,2.2322,1.8650,2.1225,14.40,7.23,14.71,0,0,0,2.879538,2.480450,2.907825,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
new_est2=pd.merge(new_est,bus,on=['CBSA','Year'],suffixes=('','_COMPETING_BUS'),how='left')
new_est2.head()

,Unnamed: 0,CBSA,Mode,Year,MNAME,PROBLEM_FLAG,NOTE,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,FARE_ADJ_ORIGINAL,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,...,CLUSTER_APTA,CLUSTER_NOTE,TOTAL_EMPLOYMENT,JTW_DA_PCT,JTW_CARPOOLED_PCT,JTW_TRANSIT_PCT,JTW_WALK_PCT,JTW_BICYCLE_PCT,JTW_OTHER_PCT,JTW_HOME_PCT,NOTE_JTW,min_year,VRM_ADJ_LAGGED_1,VRM_ADJ_LAGGED_2,VRM_ADJ_LAGGED_3,FARE_per_UPT_LAGGED_1,FARE_per_UPT_LAGGED_2,FARE_per_UPT_LAGGED_3,AVG_SPEED_LAGGED_1,AVG_SPEED_LAGGED_2,AVG_SPEED_LAGGED_3,TNC_FLAG_LAGGED_1,TNC_FLAG_LAGGED_2,TNC_FLAG_LAGGED_3,FARE_per_UPT_2018_LAGGED_1,FARE_per_UPT_2018_LAGGED_2,FARE_per_UPT_2018_LAGGED_3,dockCt_LAGGED_1,dockCt_LAGGED_2,dockCt_LAGGED_3,docklessCt_LAGGED_1,docklessCt_LAGGED_2,docklessCt_LAGGED_3,scooterCt_LAGGED_1,scooterCt_LAGGED_2,scooterCt_LAGGED_3,TNC_FLAG_LAGGED_4,TNC_FLAG_LAGGED_5,UPT_ADJ_COMPETING_RAIL,VRM_ADJ_COMPETING_RAIL,VRH_ADJ_COMPETING_RAIL,FARE_ADJ_COMPETING_RAIL,FARE_per_UPT_COMPETING_RAIL,AVG_SPEED_COMPETING_RAIL,UPT_ADJ_COMPETING_BUS,VRM_ADJ_COMPETING_BUS,VRH_ADJ_COMPETING_BUS,FARE_ADJ_COMPETING_BUS,FARE_per_UPT_COMPETING_BUS,AVG_SPEED_COMPETING_BUS
0,0,10420,Bus,2002,"Akron, OH Metro Area",NaN,NaN,5226385.660,4026372.388,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,2.860637e+06,744634347,646583.7344,496141.0469,137193.6719,-389.53125,25405.20313,26028.32813,26651.07813,7117.03125,682354.11,7.55,8.94,83.85,24.64,62.9,12.46,265452.20,22830.14,58254.52,117083.25,46891.53,20392.77,8.60,43046.82813,55300.5625,39.49,46.56,13.95,21948.42,346147.17,368095.58,5.96,94.04,1.36,NaN,...,24,NaN,309488.2031,87.4,6.2,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,0.000,0.000,0.000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,14.88
1,1,10420,Bus,2003,"Akron, OH Metro Area",NaN,NaN,5395901.888,3976568.624,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,1.145302e+07,744634347,659397.0625,504631.8125,137582.3125,753.12500,25120.18750,25632.68750,25995.68750,10350.875,682850.56,8.81,8.66,82.79,24.33,63.0,12.68,269144.19,22073.44,67400.94,115443.00,44874.88,19351.94,8.20,43566.68750,56379.7500,39.24,46.66,14.10,23342.50,348574.17,371916.67,6.28,93.72,1.55,NaN,...,24,NaN,316497.1875,87.2,6.4,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,4026372.388,0.000,0.000,0.5473,0.0000,0.0000,14.88,0.00,0.00,0,0,0,0.766220,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,14.71
2,2,10420,Bus,2004,"Akron, OH Metro Area",NaN,NaN,5907162.281,4315392.555,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,1.101674e+07,744634347,672492.7500,513183.7500,138058.7500,1942.50000,24804.25000,25208.25000,25305.25000,13527.5,683397.75,10.08,8.38,81.73,24.00,63.1,12.90,272892.25,21266.25,76795.25,113694.00,42855.50,18281.25,7.79,44030.25000,57390.0000,39.03,46.78,14.20,23471.75,351723.75,375195.50,6.26,93.74,1.83,NaN,...,24,NaN,323744.25,86.9,6.7,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,3976568.624,4026372.388,0.000,2.1225,0.5473,0.0000,14.71,14.88,0.00,0,0,0,2.907825,0.766220,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,7.23
3,3,10420,Bus,2005,"Akron, OH Metro Area",NaN,NaN,6013680.881,4053011.065,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,1.342394e+07,744634347,684459.0000,521491.0000,138184.0000,2945.00000,24612.00000,24899.00000,24755.00000,16933,683742.00,11.30,8.10,80.70,23.70,63.2,13.10,276416.00,20661.00,85198.00,112380.00,40847.00,17330.00,7.47,44719.00000,58676.0000,38.70,46.80,14.50,22420.75,358105.92,380526.67,5.90,94.10,2.25,13644.8,...,24,NaN,330039,86.8,6.8,0.8,1.7,0.1,0.7,3.1,NaN,2002,4315392.555,3976568.624,4026372.388,1.8650,2.1225,0.5473,7.23,14.71,14.88,0,0,0,2.480450,2.907825,0.766220,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,14.40
4,4,10420,Bus,2006,"Akron, OH Metro Area",NaN,NaN,6070797.419,3994786.013,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,1.400910e+07,744634347,700943.0000,530777.0000,139714.0000,4695.00000,23925.00000,24129.00000,23644.00000,19423,684898.00,12.70,7.80,79.50,23.30,63.3,13.40,280837.00,19248.00,97567.00,109326.00,38795.00,15901.00,6.85,44507.00000,58859.0000,38.80,47.20,14.00,20348.08,365133.33,385481.42,5.28,94.72,2.54,13644.8,...,24,NaN,340143,85.8,7.3,1.3,2.2,0,0.9,2.5,NaN,2002,4053011.065,4315392.555,3976568.624,2.2322,1.8650,2.1225,14.40,7.23,14.71,0,0,0,2.879538,2.480450,2.907825,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,14.19

In [15]:
list(new_est2)

['Unnamed: 0',
 'CBSA',
 'Mode',
 'Year',
 'MNAME',
 'PROBLEM_FLAG',
 'NOTE',
 'UPT',
 'VRM',
 'UPT_ADJ',
 'VRM_ADJ',
 'VRH_ADJ',
 'FARE_ADJ',
 'FARE_per_UPT',
 'FARE_ADJ_ORIGINAL',
 'AREALANDPT',
 'Tot_Pop',
 'Tot_Instate_Pop',
 'Tot_Outstate_Pop',
 'Tot_NonUSA_POP',
 'Total_Median_Income_Individual',
 'Native_Instate_Med_Inc_Indiv',
 'Native_Outstate_Med_Inc_Indiv',
 'Native_Outcountry_Med_Inc_Indiv',
 'Total_Pop_Poverty',
 'Pop_Below100_Poverty',
 'Pop_Below150_Poverty',
 'Pop_Above150_Poverty',
 'Age_under18',
 'Age_18to64',
 'Age_over64',
 'Total_HH',
 'HH_0Veh',
 'HH_1Veh',
 'HH_2Veh',
 'HH_3Veh',
 'HH_4+Veh',
 'PCT_HH_NO_VEH',
 'HH_MED_INC',
 'HH_MEAN_INC',
 'INC_U35',
 'INC_35_100',
 'INC_100P',
 'TOT_UNEMP_MSA',
 'TOT_EMP_MSA',
 'TOT_LABOR_MSA',
 'UNEMP_RATE_PCT',
 'EMP_RATE_PCT',
 'GasPrice',
 'Area_acre',
 'POP_CENSUSTRACT',
 'AVG_SPEED',
 '2018_Dollar_Multiplier',
 'TNC_ARRIVAL',
 'Link_x',
 'TNC_FLAG',
 'YEARS_SINCE_TNC',
 'FARE_ADJ_2018',
 'TOTAL_MED_INC_INDIV_2018',
 'NATIVE_INSTATE_MED_INC_2018',
 'NATIVE_OUTSTATE_MED_INC_2018',
 'HH_MED_INC_2018',
 'HH_MEAN_INC_2018',
 'GAS_PRICE_2018',
 'FARE_per_UPT_2018',
 'dockCt',
 'docklessCt',
 'scooterCt',
 'PBS_Start',
 'PBS_End',
 'PBS_Flag',
 'Link',
 'walkscore',
 'transit',
 'bike',
 'Bus_UPT_ADJ',
 'Bus_UPT_ADJ_diff',
 'Bus_UPT_ADJ_log',
 'PCT_Bus_UPT_ADJ_rel_diff',
 'Bus_UPT_ADJ_scale',
 'Bus_VRM_ADJ',
 'Bus_VRM_ADJ_diff',
 'Bus_VRM_ADJ_log',
 'PCT_Bus_VRM_ADJ_rel_diff',
 'Bus_VRM_ADJ_scale',
 'Bus_VRH_ADJ',
 'Bus_VRH_ADJ_diff',
 'Bus_VRH_ADJ_log',
 'PCT_Bus_VRH_ADJ_rel_diff',
 'Bus_VRH_ADJ_scale',
 'Bus_FARE_TOTAL',
 'Bus_FARE_TOTAL_diff',
 'Bus_FARE_TOTAL_log',
 'PCT_Bus_FARE_TOTAL_rel_diff',
 'Bus_FARE_TOTAL_scale',
 'Bus_FARE_per_UPT_2018',
 'Bus_FARE_per_UPT_2018_diff',
 'Bus_FARE_per_UPT_2018_log',
 'PCT_Bus_FARE_per_UPT_2018_rel_diff',
 'Bus_FARE_per_UPT_2018_scale',
 'Bus_AVG_SPEED',
 'Bus_AVG_SPEED_diff',
 'Bus_AVG_SPEED_log',
 'PCT_Bus_AVG_SPEED_rel_diff',
 'Bus_AVG_SPEED_scale',
 'Rail_UPT_ADJ',
 'Rail_UPT_ADJ_diff',
 'Rail_UPT_ADJ_log',
 'PCT_Rail_UPT_ADJ_rel_diff',
 'Rail_UPT_ADJ_scale',
 'Rail_VRM_ADJ',
 'Rail_VRM_ADJ_diff',
 'Rail_VRM_ADJ_log',
 'PCT_Rail_VRM_ADJ_rel_diff',
 'Rail_VRM_ADJ_scale',
 'Rail_VRH_ADJ',
 'Rail_VRH_ADJ_diff',
 'Rail_VRH_ADJ_log',
 'PCT_Rail_VRH_ADJ_rel_diff',
 'Rail_VRH_ADJ_scale',
 'Rail_FARE_TOTAL',
 'Rail_FARE_TOTAL_diff',
 'Rail_FARE_TOTAL_log',
 'PCT_Rail_FARE_TOTAL_rel_diff',
 'Rail_FARE_TOTAL_scale',
 'Rail_FARE_per_UPT_2018',
 'Rail_FARE_per_UPT_2018_diff',
 'Rail_FARE_per_UPT_2018_log',
 'PCT_Rail_FARE_per_UPT_2018_rel_diff',
 'Rail_FARE_per_UPT_2018_scale',
 'Rail_AVG_SPEED',
 'Rail_AVG_SPEED_diff',
 'Rail_AVG_SPEED_log',
 'PCT_Rail_AVG_SPEED_rel_diff',
 'Rail_AVG_SPEED_scale',
 'CLUSTER_GT_NEW_11',
 'CLUSTER_GT_ORIGINAL',
 'CLUSTER_GT_8_GROUPS',
 'CLUSTER_APTA',
 'CLUSTER_NOTE',
 'TOTAL_EMPLOYMENT',
 'JTW_DA_PCT',
 'JTW_CARPOOLED_PCT',
 'JTW_TRANSIT_PCT',
 'JTW_WALK_PCT',
 'JTW_BICYCLE_PCT',
 'JTW_OTHER_PCT',
 'JTW_HOME_PCT',
 'NOTE_JTW',
 'min_year',
 'VRM_ADJ_LAGGED_1',
 'VRM_ADJ_LAGGED_2',
 'VRM_ADJ_LAGGED_3',
 'FARE_per_UPT_LAGGED_1',
 'FARE_per_UPT_LAGGED_2',
 'FARE_per_UPT_LAGGED_3',
 'AVG_SPEED_LAGGED_1',
 'AVG_SPEED_LAGGED_2',
 'AVG_SPEED_LAGGED_3',
 'TNC_FLAG_LAGGED_1',
 'TNC_FLAG_LAGGED_2',
 'TNC_FLAG_LAGGED_3',
 'FARE_per_UPT_2018_LAGGED_1',
 'FARE_per_UPT_2018_LAGGED_2',
 'FARE_per_UPT_2018_LAGGED_3',
 'dockCt_LAGGED_1',
 'dockCt_LAGGED_2',
 'dockCt_LAGGED_3',
 'docklessCt_LAGGED_1',
 'docklessCt_LAGGED_2',
 'docklessCt_LAGGED_3',
 'scooterCt_LAGGED_1',
 'scooterCt_LAGGED_2',
 'scooterCt_LAGGED_3',
 'TNC_FLAG_LAGGED_4',
 'TNC_FLAG_LAGGED_5',
 'UPT_ADJ_COMPETING_RAIL',
 'VRM_ADJ_COMPETING_RAIL',
 'VRH_ADJ_COMPETING_RAIL',
 'FARE_ADJ_COMPETING_RAIL',
 'FARE_per_UPT_COMPETING_RAIL',
 'AVG_SPEED_COMPETING_RAIL',
 'UPT_ADJ_COMPETING_BUS',
 'VRM_ADJ_COMPETING_BUS',
 'VRH_ADJ_COMPETING_BUS',
 'FARE_ADJ_COMPETING_BUS',
 'FARE_per_UPT_COMPETING_BUS',
 'AVG_SPEED_COMPETING_BUS']

In [18]:
cross_elas=['UPT_ADJ','VRM_ADJ','VRH_ADJ','FARE_ADJ','FARE_per_UPT','AVG_SPEED']

bus_col=['UPT_ADJ_COMPETING_BUS',
 'VRM_ADJ_COMPETING_BUS',
 'VRH_ADJ_COMPETING_BUS',
 'FARE_ADJ_COMPETING_BUS',
 'FARE_per_UPT_COMPETING_BUS',
 'AVG_SPEED_COMPETING_BUS']
rail_col=['UPT_ADJ_COMPETING_RAIL',
 'VRM_ADJ_COMPETING_RAIL',
 'VRH_ADJ_COMPETING_RAIL',
 'FARE_ADJ_COMPETING_RAIL',
 'FARE_per_UPT_COMPETING_RAIL',
 'AVG_SPEED_COMPETING_RAIL']


if new_est2['Mode']=='Bus':
    new_est2['UPT_ADJ_COMPETING']=new_est2['UPT_ADJ_COMPETING_RAIL']
    new_est2['VRM_ADJ_COMPETING']=new_est2['VRM_ADJ_COMPETING_RAIL']
    new_est2['VRH_ADJ_COMPETING']=new_est2['VRH_ADJ_COMPETING_RAIL']
    new_est2['FARE_ADJ_COMPETING']=new_est2['FARE_ADJ_COMPETING_RAIL']
    new_est2['FARE_per_UPT_COMPETING']=new_est2['FARE_per_UPT_COMPETING_RAIL']
    new_est2['AVG_SPEED_COMPETING']=new_est2['AVG_SPEED_COMPETING_RAIL']
else:
    new_est2['UPT_ADJ_COMPETING']=new_est2['UPT_ADJ_COMPETING_BUS']
    new_est2['VRM_ADJ_COMPETING']=new_est2['VRM_ADJ_COMPETING_BUS']
    new_est2['VRH_ADJ_COMPETING']=new_est2['VRH_ADJ_COMPETING_BUS']
    new_est2['FARE_ADJ_COMPETING']=new_est2['FARE_ADJ_COMPETING_BUS']
    new_est2['FARE_per_UPT_COMPETING']=new_est2['FARE_per_UPT_COMPETING_BUS']
    new_est2['AVG_SPEED_COMPETING']=new_est2['AVG_SPEED_COMPETING_BUS']

new_est2.head()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [20]:
new_est2['UPT_ADJ_COMPETING']=np.where(new_est2['Mode']=='Bus',new_est2['UPT_ADJ_COMPETING_RAIL'],new_est2['UPT_ADJ_COMPETING_BUS'])
new_est2['VRM_ADJ_COMPETING']=np.where(new_est2['Mode']=='Bus',new_est2['VRM_ADJ_COMPETING_RAIL'],new_est2['VRM_ADJ_COMPETING_BUS'])
new_est2['VRH_ADJ_COMPETING']=np.where(new_est2['Mode']=='Bus',new_est2['VRH_ADJ_COMPETING_RAIL'],new_est2['VRH_ADJ_COMPETING_BUS'])
new_est2['FARE_ADJ_COMPETING']=np.where(new_est2['Mode']=='Bus',new_est2['FARE_ADJ_COMPETING_RAIL'],new_est2['FARE_ADJ_COMPETING_BUS'])
new_est2['FARE_per_UPT_COMPETING']=np.where(new_est2['Mode']=='Bus',new_est2['FARE_per_UPT_COMPETING_RAIL'],new_est2['FARE_per_UPT_COMPETING_BUS'])
new_est2['AVG_SPEED_COMPETING']=np.where(new_est2['Mode']=='Bus',new_est2['AVG_SPEED_COMPETING_RAIL'],new_est2['AVG_SPEED_COMPETING_BUS'])
new_est2.head()

,Unnamed: 0,CBSA,Mode,Year,MNAME,PROBLEM_FLAG,NOTE,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,FARE_ADJ_ORIGINAL,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,...,JTW_WALK_PCT,JTW_BICYCLE_PCT,JTW_OTHER_PCT,JTW_HOME_PCT,NOTE_JTW,min_year,VRM_ADJ_LAGGED_1,VRM_ADJ_LAGGED_2,VRM_ADJ_LAGGED_3,FARE_per_UPT_LAGGED_1,FARE_per_UPT_LAGGED_2,FARE_per_UPT_LAGGED_3,AVG_SPEED_LAGGED_1,AVG_SPEED_LAGGED_2,AVG_SPEED_LAGGED_3,TNC_FLAG_LAGGED_1,TNC_FLAG_LAGGED_2,TNC_FLAG_LAGGED_3,FARE_per_UPT_2018_LAGGED_1,FARE_per_UPT_2018_LAGGED_2,FARE_per_UPT_2018_LAGGED_3,dockCt_LAGGED_1,dockCt_LAGGED_2,dockCt_LAGGED_3,docklessCt_LAGGED_1,docklessCt_LAGGED_2,docklessCt_LAGGED_3,scooterCt_LAGGED_1,scooterCt_LAGGED_2,scooterCt_LAGGED_3,TNC_FLAG_LAGGED_4,TNC_FLAG_LAGGED_5,UPT_ADJ_COMPETING_RAIL,VRM_ADJ_COMPETING_RAIL,VRH_ADJ_COMPETING_RAIL,FARE_ADJ_COMPETING_RAIL,FARE_per_UPT_COMPETING_RAIL,AVG_SPEED_COMPETING_RAIL,UPT_ADJ_COMPETING_BUS,VRM_ADJ_COMPETING_BUS,VRH_ADJ_COMPETING_BUS,FARE_ADJ_COMPETING_BUS,FARE_per_UPT_COMPETING_BUS,AVG_SPEED_COMPETING_BUS,UPT_ADJ_COMPETING,VRM_ADJ_COMPETING,VRH_ADJ_COMPETING,FARE_ADJ_COMPETING,FARE_per_UPT_COMPETING,AVG_SPEED_COMPETING
0,0,10420,Bus,2002,"Akron, OH Metro Area",NaN,NaN,5226385.660,4026372.388,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,2.860637e+06,744634347,646583.7344,496141.0469,137193.6719,-389.53125,25405.20313,26028.32813,26651.07813,7117.03125,682354.11,7.55,8.94,83.85,24.64,62.9,12.46,265452.20,22830.14,58254.52,117083.25,46891.53,20392.77,8.60,43046.82813,55300.5625,39.49,46.56,13.95,21948.42,346147.17,368095.58,5.96,94.04,1.36,NaN,...,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,0.000,0.000,0.000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,14.88,NaN,NaN,NaN,NaN,NaN,NaN
1,1,10420,Bus,2003,"Akron, OH Metro Area",NaN,NaN,5395901.888,3976568.624,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,1.145302e+07,744634347,659397.0625,504631.8125,137582.3125,753.12500,25120.18750,25632.68750,25995.68750,10350.875,682850.56,8.81,8.66,82.79,24.33,63.0,12.68,269144.19,22073.44,67400.94,115443.00,44874.88,19351.94,8.20,43566.68750,56379.7500,39.24,46.66,14.10,23342.50,348574.17,371916.67,6.28,93.72,1.55,NaN,...,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,4026372.388,0.000,0.000,0.5473,0.0000,0.0000,14.88,0.00,0.00,0,0,0,0.766220,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,14.71,NaN,NaN,NaN,NaN,NaN,NaN
2,2,10420,Bus,2004,"Akron, OH Metro Area",NaN,NaN,5907162.281,4315392.555,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,1.101674e+07,744634347,672492.7500,513183.7500,138058.7500,1942.50000,24804.25000,25208.25000,25305.25000,13527.5,683397.75,10.08,8.38,81.73,24.00,63.1,12.90,272892.25,21266.25,76795.25,113694.00,42855.50,18281.25,7.79,44030.25000,57390.0000,39.03,46.78,14.20,23471.75,351723.75,375195.50,6.26,93.74,1.83,NaN,...,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,3976568.624,4026372.388,0.000,2.1225,0.5473,0.0000,14.71,14.88,0.00,0,0,0,2.907825,0.766220,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,7.23,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10420,Bus,2005,"Akron, OH Metro Area",NaN,NaN,6013680.881,4053011.065,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,1.342394e+07,744634347,684459.0000,521491.0000,138184.0000,2945.00000,24612.00000,24899.00000,24755.00000,16933,683742.00,11.30,8.10,80.70,23.70,63.2,13.10,276416.00,20661.00,85198.00,112380.00,40847.00,17330.00,7.47,44719.00000,58676.0000,38.70,46.80,14.50,22420.75,358105.92,380526.67,5.90,94.10,2.25,13644.8,...,1.7,0.1,0.7,3.1,NaN,2002,4315392.555,3976568.624,4026372.388,1.8650,2.1225,0.5473,7.23,14.71,14.88,0,0,0,2.480450,2.907825,0.766220,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,14.40,NaN,NaN,NaN,NaN,NaN,NaN
4,4,10420,Bus,2006,"Akron, OH Metro Area",NaN,NaN,6070797.419,3994786.013,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,1.400910e+07,744634347,700943.0000,530777.0000,139714.0000,4695.00000,23925.00000,24129.00000,23644.00000,19423,684898.00,12.70,7.80,79.50,23.30,63.3,13.40,280837.00,19248.00,97567.00,109326.00,38795.00,15901.00,6.85,44507.00000,58859.0000,38.80,47.20,14.00,20348.08,365133.33,385481.42,5.28,94.72,2.54,13644.8,...,2.2,0,0.9,2.5,NaN,2002,4053011.065,4315392.555,3976568.624,2.2322,1.8650,2.1225,14.40,7.23,14.71,0,0,0,2.879538,2.480450,2.907825,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,14.19,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
new_est2.drop(columns=['UPT_ADJ_COMPETING_BUS',
 'VRM_ADJ_COMPETING_BUS',
 'VRH_ADJ_COMPETING_BUS',
 'FARE_ADJ_COMPETING_BUS',
 'FARE_per_UPT_COMPETING_BUS',
 'AVG_SPEED_COMPETING_BUS','UPT_ADJ_COMPETING_RAIL',
 'VRM_ADJ_COMPETING_RAIL',
 'VRH_ADJ_COMPETING_RAIL',
 'FARE_ADJ_COMPETING_RAIL',
 'FARE_per_UPT_COMPETING_RAIL',
 'AVG_SPEED_COMPETING_RAIL'],inplace=True)
new_est2.head()

,Unnamed: 0,CBSA,Mode,Year,MNAME,PROBLEM_FLAG,NOTE,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,FARE_ADJ_ORIGINAL,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,...,Rail_AVG_SPEED_log,PCT_Rail_AVG_SPEED_rel_diff,Rail_AVG_SPEED_scale,CLUSTER_GT_NEW_11,CLUSTER_GT_ORIGINAL,CLUSTER_GT_8_GROUPS,CLUSTER_APTA,CLUSTER_NOTE,TOTAL_EMPLOYMENT,JTW_DA_PCT,JTW_CARPOOLED_PCT,JTW_TRANSIT_PCT,JTW_WALK_PCT,JTW_BICYCLE_PCT,JTW_OTHER_PCT,JTW_HOME_PCT,NOTE_JTW,min_year,VRM_ADJ_LAGGED_1,VRM_ADJ_LAGGED_2,VRM_ADJ_LAGGED_3,FARE_per_UPT_LAGGED_1,FARE_per_UPT_LAGGED_2,FARE_per_UPT_LAGGED_3,AVG_SPEED_LAGGED_1,AVG_SPEED_LAGGED_2,AVG_SPEED_LAGGED_3,TNC_FLAG_LAGGED_1,TNC_FLAG_LAGGED_2,TNC_FLAG_LAGGED_3,FARE_per_UPT_2018_LAGGED_1,FARE_per_UPT_2018_LAGGED_2,FARE_per_UPT_2018_LAGGED_3,dockCt_LAGGED_1,dockCt_LAGGED_2,dockCt_LAGGED_3,docklessCt_LAGGED_1,docklessCt_LAGGED_2,docklessCt_LAGGED_3,scooterCt_LAGGED_1,scooterCt_LAGGED_2,scooterCt_LAGGED_3,TNC_FLAG_LAGGED_4,TNC_FLAG_LAGGED_5,UPT_ADJ_COMPETING,VRM_ADJ_COMPETING,VRH_ADJ_COMPETING,FARE_ADJ_COMPETING,FARE_per_UPT_COMPETING,AVG_SPEED_COMPETING
0,0,10420,Bus,2002,"Akron, OH Metro Area",NaN,NaN,5226385.660,4026372.388,5226385.660,4026372.388,270506.6928,2.860637e+06,0.5473,2.860637e+06,744634347,646583.7344,496141.0469,137193.6719,-389.53125,25405.20313,26028.32813,26651.07813,7117.03125,682354.11,7.55,8.94,83.85,24.64,62.9,12.46,265452.20,22830.14,58254.52,117083.25,46891.53,20392.77,8.60,43046.82813,55300.5625,39.49,46.56,13.95,21948.42,346147.17,368095.58,5.96,94.04,1.36,NaN,...,0.0,0.0,-62,1,1,H,24,NaN,309488.2031,87.4,6.2,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,0.000,0.000,0.000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,10420,Bus,2003,"Akron, OH Metro Area",NaN,NaN,5395901.888,3976568.624,5395901.888,3976568.624,270398.3688,1.145302e+07,2.1225,1.145302e+07,744634347,659397.0625,504631.8125,137582.3125,753.12500,25120.18750,25632.68750,25995.68750,10350.875,682850.56,8.81,8.66,82.79,24.33,63.0,12.68,269144.19,22073.44,67400.94,115443.00,44874.88,19351.94,8.20,43566.68750,56379.7500,39.24,46.66,14.10,23342.50,348574.17,371916.67,6.28,93.72,1.55,NaN,...,0.0,0.0,-62,1,1,H,24,NaN,316497.1875,87.2,6.4,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,4026372.388,0.000,0.000,0.5473,0.0000,0.0000,14.88,0.00,0.00,0,0,0,0.766220,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,10420,Bus,2004,"Akron, OH Metro Area",NaN,NaN,5907162.281,4315392.555,5907162.281,4315392.555,597239.8605,1.101674e+07,1.8650,1.101674e+07,744634347,672492.7500,513183.7500,138058.7500,1942.50000,24804.25000,25208.25000,25305.25000,13527.5,683397.75,10.08,8.38,81.73,24.00,63.1,12.90,272892.25,21266.25,76795.25,113694.00,42855.50,18281.25,7.79,44030.25000,57390.0000,39.03,46.78,14.20,23471.75,351723.75,375195.50,6.26,93.74,1.83,NaN,...,0.0,0.0,-62,1,1,H,24,NaN,323744.25,86.9,6.7,0.8,1.7,0.1,0.7,3.1,Goes to negative when extrapolating. Possible ...,2002,3976568.624,4026372.388,0.000,2.1225,0.5473,0.0000,14.71,14.88,0.00,0,0,0,2.907825,0.766220,0.000000,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10420,Bus,2005,"Akron, OH Metro Area",NaN,NaN,6013680.881,4053011.065,6013680.881,4053011.065,281367.9792,1.342394e+07,2.2322,1.342394e+07,744634347,684459.0000,521491.0000,138184.0000,2945.00000,24612.00000,24899.00000,24755.00000,16933,683742.00,11.30,8.10,80.70,23.70,63.2,13.10,276416.00,20661.00,85198.00,112380.00,40847.00,17330.00,7.47,44719.00000,58676.0000,38.70,46.80,14.50,22420.75,358105.92,380526.67,5.90,94.10,2.25,13644.8,...,0.0,0.0,-62,1,1,H,24,NaN,330039,86.8,6.8,0.8,1.7,0.1,0.7,3.1,NaN,2002,4315392.555,3976568.624,4026372.388,1.8650,2.1225,0.5473,7.23,14.71,14.88,0,0,0,2.480450,2.907825,0.766220,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,10420,Bus,2006,"Akron, OH Metro Area",NaN,NaN,6070797.419,3994786.013,6070797.419,3994786.013,281536.7841,1.400910e+07,2.3076,1.400910e+07,744634347,700943.0000,530777.0000,139714.0000,4695.00000,23925.00000,24129.00000,23644.00000,19423,684898.00,12.70,7.80,79.50,23.30,63.3,13.40,280837.00,19248.00,97567.00,109326.00,38795.00,15901.00,6.85,44507.00000,58859.0000,38.80,47.20,14.00,20348.08,365133.33,385481.42,5.28,94.72,2.54,13644.8,...,0.0,0.0,-62,1,1,H,24,NaN,340143,85.8,7.3,1.3,2.2,0,0.9,2.5,NaN,2002,4053011.065,4315392.555,3976568.624,2.2322,1.8650,2.1225,14.40,7.23,14.71,0,0,0,2.879538,2.480450,2.907825,0,0,0,0,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
def lagged_column2(df,col,lag):
    x=np.where(df['min_year']!=df['Year'],df[col].shift(lag),np.nan)
    
    return x

In [23]:
list(new_est2)

['Unnamed: 0',
 'CBSA',
 'Mode',
 'Year',
 'MNAME',
 'PROBLEM_FLAG',
 'NOTE',
 'UPT',
 'VRM',
 'UPT_ADJ',
 'VRM_ADJ',
 'VRH_ADJ',
 'FARE_ADJ',
 'FARE_per_UPT',
 'FARE_ADJ_ORIGINAL',
 'AREALANDPT',
 'Tot_Pop',
 'Tot_Instate_Pop',
 'Tot_Outstate_Pop',
 'Tot_NonUSA_POP',
 'Total_Median_Income_Individual',
 'Native_Instate_Med_Inc_Indiv',
 'Native_Outstate_Med_Inc_Indiv',
 'Native_Outcountry_Med_Inc_Indiv',
 'Total_Pop_Poverty',
 'Pop_Below100_Poverty',
 'Pop_Below150_Poverty',
 'Pop_Above150_Poverty',
 'Age_under18',
 'Age_18to64',
 'Age_over64',
 'Total_HH',
 'HH_0Veh',
 'HH_1Veh',
 'HH_2Veh',
 'HH_3Veh',
 'HH_4+Veh',
 'PCT_HH_NO_VEH',
 'HH_MED_INC',
 'HH_MEAN_INC',
 'INC_U35',
 'INC_35_100',
 'INC_100P',
 'TOT_UNEMP_MSA',
 'TOT_EMP_MSA',
 'TOT_LABOR_MSA',
 'UNEMP_RATE_PCT',
 'EMP_RATE_PCT',
 'GasPrice',
 'Area_acre',
 'POP_CENSUSTRACT',
 'AVG_SPEED',
 '2018_Dollar_Multiplier',
 'TNC_ARRIVAL',
 'Link_x',
 'TNC_FLAG',
 'YEARS_SINCE_TNC',
 'FARE_ADJ_2018',
 'TOTAL_MED_INC_INDIV_2018',
 'NATIVE_INSTATE_MED_INC_2018',
 'NATIVE_OUTSTATE_MED_INC_2018',
 'HH_MED_INC_2018',
 'HH_MEAN_INC_2018',
 'GAS_PRICE_2018',
 'FARE_per_UPT_2018',
 'dockCt',
 'docklessCt',
 'scooterCt',
 'PBS_Start',
 'PBS_End',
 'PBS_Flag',
 'Link',
 'walkscore',
 'transit',
 'bike',
 'Bus_UPT_ADJ',
 'Bus_UPT_ADJ_diff',
 'Bus_UPT_ADJ_log',
 'PCT_Bus_UPT_ADJ_rel_diff',
 'Bus_UPT_ADJ_scale',
 'Bus_VRM_ADJ',
 'Bus_VRM_ADJ_diff',
 'Bus_VRM_ADJ_log',
 'PCT_Bus_VRM_ADJ_rel_diff',
 'Bus_VRM_ADJ_scale',
 'Bus_VRH_ADJ',
 'Bus_VRH_ADJ_diff',
 'Bus_VRH_ADJ_log',
 'PCT_Bus_VRH_ADJ_rel_diff',
 'Bus_VRH_ADJ_scale',
 'Bus_FARE_TOTAL',
 'Bus_FARE_TOTAL_diff',
 'Bus_FARE_TOTAL_log',
 'PCT_Bus_FARE_TOTAL_rel_diff',
 'Bus_FARE_TOTAL_scale',
 'Bus_FARE_per_UPT_2018',
 'Bus_FARE_per_UPT_2018_diff',
 'Bus_FARE_per_UPT_2018_log',
 'PCT_Bus_FARE_per_UPT_2018_rel_diff',
 'Bus_FARE_per_UPT_2018_scale',
 'Bus_AVG_SPEED',
 'Bus_AVG_SPEED_diff',
 'Bus_AVG_SPEED_log',
 'PCT_Bus_AVG_SPEED_rel_diff',
 'Bus_AVG_SPEED_scale',
 'Rail_UPT_ADJ',
 'Rail_UPT_ADJ_diff',
 'Rail_UPT_ADJ_log',
 'PCT_Rail_UPT_ADJ_rel_diff',
 'Rail_UPT_ADJ_scale',
 'Rail_VRM_ADJ',
 'Rail_VRM_ADJ_diff',
 'Rail_VRM_ADJ_log',
 'PCT_Rail_VRM_ADJ_rel_diff',
 'Rail_VRM_ADJ_scale',
 'Rail_VRH_ADJ',
 'Rail_VRH_ADJ_diff',
 'Rail_VRH_ADJ_log',
 'PCT_Rail_VRH_ADJ_rel_diff',
 'Rail_VRH_ADJ_scale',
 'Rail_FARE_TOTAL',
 'Rail_FARE_TOTAL_diff',
 'Rail_FARE_TOTAL_log',
 'PCT_Rail_FARE_TOTAL_rel_diff',
 'Rail_FARE_TOTAL_scale',
 'Rail_FARE_per_UPT_2018',
 'Rail_FARE_per_UPT_2018_diff',
 'Rail_FARE_per_UPT_2018_log',
 'PCT_Rail_FARE_per_UPT_2018_rel_diff',
 'Rail_FARE_per_UPT_2018_scale',
 'Rail_AVG_SPEED',
 'Rail_AVG_SPEED_diff',
 'Rail_AVG_SPEED_log',
 'PCT_Rail_AVG_SPEED_rel_diff',
 'Rail_AVG_SPEED_scale',
 'CLUSTER_GT_NEW_11',
 'CLUSTER_GT_ORIGINAL',
 'CLUSTER_GT_8_GROUPS',
 'CLUSTER_APTA',
 'CLUSTER_NOTE',
 'TOTAL_EMPLOYMENT',
 'JTW_DA_PCT',
 'JTW_CARPOOLED_PCT',
 'JTW_TRANSIT_PCT',
 'JTW_WALK_PCT',
 'JTW_BICYCLE_PCT',
 'JTW_OTHER_PCT',
 'JTW_HOME_PCT',
 'NOTE_JTW',
 'min_year',
 'VRM_ADJ_LAGGED_1',
 'VRM_ADJ_LAGGED_2',
 'VRM_ADJ_LAGGED_3',
 'FARE_per_UPT_LAGGED_1',
 'FARE_per_UPT_LAGGED_2',
 'FARE_per_UPT_LAGGED_3',
 'AVG_SPEED_LAGGED_1',
 'AVG_SPEED_LAGGED_2',
 'AVG_SPEED_LAGGED_3',
 'TNC_FLAG_LAGGED_1',
 'TNC_FLAG_LAGGED_2',
 'TNC_FLAG_LAGGED_3',
 'FARE_per_UPT_2018_LAGGED_1',
 'FARE_per_UPT_2018_LAGGED_2',
 'FARE_per_UPT_2018_LAGGED_3',
 'dockCt_LAGGED_1',
 'dockCt_LAGGED_2',
 'dockCt_LAGGED_3',
 'docklessCt_LAGGED_1',
 'docklessCt_LAGGED_2',
 'docklessCt_LAGGED_3',
 'scooterCt_LAGGED_1',
 'scooterCt_LAGGED_2',
 'scooterCt_LAGGED_3',
 'TNC_FLAG_LAGGED_4',
 'TNC_FLAG_LAGGED_5',
 'UPT_ADJ_COMPETING',
 'VRM_ADJ_COMPETING',
 'VRH_ADJ_COMPETING',
 'FARE_ADJ_COMPETING',
 'FARE_per_UPT_COMPETING',
 'AVG_SPEED_COMPETING']

In [30]:
lagged_columns=[
'UPT_ADJ_COMPETING',
 'VRM_ADJ_COMPETING',
 'VRH_ADJ_COMPETING',
 'FARE_ADJ_COMPETING',
 'FARE_per_UPT_COMPETING',
 'AVG_SPEED_COMPETING']

for col in new_est2.columns: 
    if col in lagged_columns:
        new_est2[col+'_LAGGED_1'] = lagged_column2(new_est2, col,1)
        new_est2[col+'_LAGGED_2'] = lagged_column2(new_est2, col,2)
        new_est2[col+'_LAGGED_3'] = lagged_column2(new_est2, col,3)

In [36]:
new_est2[new_est2['Mode']=='Rail']

,CBSA,Mode,Year,MNAME,PROBLEM_FLAG,NOTE,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_ADJ,FARE_per_UPT,FARE_ADJ_ORIGINAL,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,POP_CENSUSTRACT,...,VRM_ADJ_LAGGED_1,VRM_ADJ_LAGGED_2,VRM_ADJ_LAGGED_3,FARE_per_UPT_LAGGED_1,FARE_per_UPT_LAGGED_2,FARE_per_UPT_LAGGED_3,AVG_SPEED_LAGGED_1,AVG_SPEED_LAGGED_2,AVG_SPEED_LAGGED_3,TNC_FLAG_LAGGED_1,TNC_FLAG_LAGGED_2,TNC_FLAG_LAGGED_3,FARE_per_UPT_2018_LAGGED_1,FARE_per_UPT_2018_LAGGED_2,FARE_per_UPT_2018_LAGGED_3,dockCt_LAGGED_1,dockCt_LAGGED_2,dockCt_LAGGED_3,docklessCt_LAGGED_1,docklessCt_LAGGED_2,docklessCt_LAGGED_3,scooterCt_LAGGED_1,scooterCt_LAGGED_2,scooterCt_LAGGED_3,TNC_FLAG_LAGGED_4,TNC_FLAG_LAGGED_5,UPT_ADJ_COMPETING,VRM_ADJ_COMPETING,VRH_ADJ_COMPETING,FARE_ADJ_COMPETING,FARE_per_UPT_COMPETING,AVG_SPEED_COMPETING,UPT_ADJ_COMPETING_LAGGED_1,UPT_ADJ_COMPETING_LAGGED_2,UPT_ADJ_COMPETING_LAGGED_3,VRM_ADJ_COMPETING_LAGGED_1,VRM_ADJ_COMPETING_LAGGED_2,VRM_ADJ_COMPETING_LAGGED_3,VRH_ADJ_COMPETING_LAGGED_1,VRH_ADJ_COMPETING_LAGGED_2,VRH_ADJ_COMPETING_LAGGED_3,FARE_ADJ_COMPETING_LAGGED_1,FARE_ADJ_COMPETING_LAGGED_2,FARE_ADJ_COMPETING_LAGGED_3,FARE_per_UPT_COMPETING_LAGGED_1,FARE_per_UPT_COMPETING_LAGGED_2,FARE_per_UPT_COMPETING_LAGGED_3,AVG_SPEED_COMPETING_LAGGED_1,AVG_SPEED_COMPETING_LAGGED_2,AVG_SPEED_COMPETING_LAGGED_3
68,10740,Rail,2009,"Albuquerque, NM Metro Area",NaN,NaN,1351087.0,813885.00,1351087.0,813885.00,20107.000,1.868810e+07,13.8319,1.868810e+07,648969769,856216.00,432274.00,329891.0,11065.00,25253.0,23216.00,30017.00,27978,846650.00,15.90,10.40,73.70,24.8,63.10,12.10,334647.00,17776.0,120045.0,127430.00,47757.0,21639.0,5.31,46824.00,61059.0,36.70,46.60,16.70,31447.33,372776.25,404223.58,7.78,92.22,2.27,28089.6,250737.0,...,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.00,0.00,0.00,0,0,0,0.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,1.0,1.0,10639235.0,5144295.00,316912.000,8589760.0,0.8074,16.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,10740,Rail,2010,"Albuquerque, NM Metro Area",NaN,NaN,1165687.0,1415143.00,1165687.0,1415143.00,37249.000,1.992355e+07,17.0917,1.992355e+07,648969769,892014.00,459673.00,332367.0,9139.00,25891.0,23628.00,31267.00,26156,881703.00,NaN,0.00,0.00,24.4,63.20,12.40,344800.00,16484.0,120481.0,136269.00,48104.0,23462.0,4.78,47383.00,63619.0,36.80,45.30,17.90,34020.50,390669.08,424689.58,8.01,91.99,2.70,28089.6,247586.0,...,813885.00,5697345.00,5684500.00,13.8319,0.6307,0.6811,40.48,13.60,13.60,0,1,1,16.183323,0.630700,0.694722,0,0,15,0,0,0,0,0,0,1.0,1.0,11527241.0,5102876.00,377604.000,6920348.0,0.6003,13.51,10639235.0,771602.0,811421.0,5144295.00,1337514.00,1350224.00,316912.000,35650.000,35799.000,8589760.0,13551359.5,15071035.0,0.8074,17.5626,18.5736,16.23,37.52,37.72
70,10740,Rail,2011,"Albuquerque, NM Metro Area",NaN,NaN,1242174.0,1370680.00,1242174.0,1370680.00,36676.000,1.999384e+07,16.0958,1.999384e+07,648969769,899149.00,466738.00,336918.0,9294.00,24924.0,21970.00,30564.00,32165,887261.00,NaN,0.00,0.00,24.4,63.00,12.60,345157.00,23644.0,121901.0,126939.00,52444.0,20229.0,6.85,45027.00,61912.0,40.20,41.90,17.90,31629.17,389437.25,421066.42,7.51,92.49,3.42,28089.6,244435.0,...,1415143.00,813885.00,5697345.00,17.0917,13.8319,0.6307,37.99,40.48,13.60,0,0,1,19.655455,16.183323,0.630700,0,0,0,0,0,0,0,0,0,1.0,1.0,12375668.0,5329846.00,392829.000,8058762.0,0.6512,13.57,11527241.0,10639235.0,771602.0,5102876.00,5144295.00,1337514.00,377604.000,316912.000,35650.000,6920348.0,8589760.0,13551359.5,0.6003,0.8074,17.5626,13.51,16.23,37.52
71,10740,Rail,2012,"Albuquerque, NM Metro Area",NaN,NaN,1129303.0,1424748.00,1129303.0,1424748.00,36870.000,1.831540e+07,16.2183,1.831540e+07,648969769,902794.00,484743.00,320910.0,12335.00,25616.0,22332.00,31553.00,29079,887938.00,NaN,0.00,0.00,24.1,62.70,13.20,344869.00,21014.0,120959.0,130200.00,48806.0,23890.0,6.09,46725.00,62672.0,38.80,43.10,18.10,29752.50,387763.75,417516.25,7.13,92.87,3.49,28089.6,244628.0,...,1370680.00,1415143.00,813885.00,16.0958,17.0917,13.8319,37.37,37.99,40.48,0,0,0,18.027296,19.655455,16.183323,0,0,0,0,0,0,0,0,0,1.0,1.0,13029416.0,5428339.00,396364.000,8443120.0,0.6480,13.70,12375668.0,11527241.0,10639235.0,5329846.00,5102876.00,5144295.00,392829.000,377604.000,316912.000,8058762.0,6920348.0,8589760.0,0.6512,0.6003,0.8074,13.57,13.51,16.23
72,10740,Rail,2013,"Albuquerque, NM Metro Area",NaN,NaN,1082588.0,1388562.00,1082588.0,1388562.00,36503.000,2.102050e+07,19.4169,2.102050e+07,648969769,901932.00,472342.00,328386.0,11036.00,25717.0,22709.00,31723.00,31539,890054.00,19.40,10.70,69.80,23.7,62.50,13.80,336614.00,18513.0,118331.0,125926.00,51657.0,22187.0,5.50,48355.00,64625.0,37.70,43.90,18.40,28250.83,387442.33,415693.17,6.80,93.20,3.37,28089.6,245116.0,...,1424748.00,1370680.00,1415143.00,16.2183,16.0958,17.0917,38.64,37.37,37.99,0,0,0,17.677947,18.027296,19.655455,0,0,0,0,0,0,0,0,0,0.0,1.0,13037741.0,5732072.00,414531.000,8618545.0,0.6610,13.83,13029416.0,12375668.0,11527241.0,5428339.00,5329846.00,5102876.00,396364.000,392829.000,377604.000,8443120.0,8058762.0,6920348.0,0.6480,0.6512,0.6003,13.70,13.57,13.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4375,47900,Rail,2014,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",NaN,NaN,274505575.6,82388648.58,274505575.6,82388648.58,3311578.024,3.035029e+09,11.0563,3.035029e+09,3407385770,6032744.00,1893214.00,2649506.0,127261.00,41738.0,29863.00,55202.00,49043,5925998.00,8.70,5.80,85.50,23.3,65.20,11.50,2154147.00,209564.0,726223.0,774708.00,302559.0,141093.0,9.73,91193.00,117085.0,17.00,37.40,45.60,165049.75,3072740.58,3237790.33,5.10,94.90,3.41,202470.4,2511787.0,...,77363702.15,75874576.88,69929446.13,11.1438,10.2753,9.9948,24.67,24.69,24.79,1,1,1,12.035304,11.200077,11.194176,0,0,0,0,0,0,0,0,0,0.0,0.0,194294004.0,76580351.04,6718511.451,926460321.7,4.7683,11.40,195753145.1,193477738.8,189999951.5,76258418.97,74138686.15,73634166.15,6485262.797,6302321.637,6219349.039,906037552.9,863857302.0,837707762.2,4.6285,4.4649,4.4090,11.76,11.76,11.84
4376,47900,Rail,2015,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",NaN,NaN,263876299.6,83145853.15,263876299.6,83145853.15,3332900.435,3.202129e+09,12.1350,3.202129e+09,3407385770,6098283.00,1919234.00,2653289.0,128434.00,42252.0,30563.00,56157.00,50256,5993144.00,8.30,5.20,86.50,23.2,65.00,11.80,2172310.00,218471.0,723518.0,784926.00,297986.0,147409.0,10.06,93294.00,121072.0,16.50,36.60,46.90,143724.00,3106749.17,3250473.17,4.42,95.58,2.41,202470.4,2556635.0,...,82388648.58,77363702.15,75874576.88,11.0563,11.1438,10.2753,24.88,24.67,24.69,1,1,1,11.719678,12.035304,11.200077,0,0,0,0,0,0,0,0,0,1.0,0.0,187871117.9,76660019.43,6771825.850,933759501.6,4.9702,11.32,194294004.0,195753145.1,193477738.8,76580351.04,76258418.97,74138686.15,6718511.451,6485262.797,6302321.637,926460321.7,906037552.9,863857302.0,4.7683,4.6285,4.4649,11.40,11.76,11.76
4377,47900,Rail,2016,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",NaN,NaN,237335745.7,79175822.57,237335745.7,79175822.57,3222564.472,2.941549e+09,12.3940,2.941549e+09,3407385770,6133552.00,1961451.00,2629215.0,135099.00,43327.0,31201.00,57317.00,52095,6025231.00,8.40,5.30,86.30,23.1,64.80,12.10,2191806.00,222367.0,719214.0,784674.00,308887.0,156664.0,10.15,95843.00,123171.0,16.90,35.20,47.90,128961.17,3169331.33,3298292.50,3.91,96.09,2.21,202470.4,2582486.0,...,83145853.15,82388648.58,77363702.15,12.1350,11.0563,11.1438,24.95,24.88,24.67,1,1,1,12.863100,11.719678,12.035304,354,0,0,0,0,0,0,0,0,1.0,1.0,178336810.7,78369197.22,6903122.627,909786457.9,5.1015,11.35,187871117.9,194294004.0,195753145.1,76660019.43,76580351.04,76258418.97,6771825.850,6718511.451,6485262.797,933759501.6,926460321.7,906037552.9,4.9702,4.7683,4.6285,11.32,11.40,11.76
4378,47900,Rail,2017,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",NaN,NaN,235272012.2,82945431.68,235272012.2,82945431.68,3487185.734,2.688671e+09,11.4279,2.688671e+09,3407385770,6216710.00,1969261.00,2676043.0,135859.00,46136.0,32060.00,58952.00,50599,6112403.00,7.90,5.10,87.00,23.0,64.40,12.60,2203717.00,210097.0,725490.0,804757.00,309188.0,154185.0,9.53,99669.00,128402.0,15.40,34.80,49.80,124490.92,3236289.33,3360780.25,3.70,96.30,2.46,202470.4,2617859.0,...,79175822.57,83145853.15,82388648.58,12.3940,12.1350,11.0563,24.57,24.95,24.88,1,1,1,13.013700,12.863100,11.719678,488,354,0,0,0,0,0,0,0,1.0,1.0,172566172.0,77126570.51,6901180.302,838052738.6,4.8564,11.18,178336810.7,187871117.9,194294004.0,78369197.22,76660019.43,76580351.04,6903122.627,6771825.850,6718511.451,909786457.9,933759501.6,926460321.7,5.1015,4.9702,4.7683,11.35,11.32,11.40
4379,47900,Rail,2018,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",NaN,NaN,233283293.0,85666389.02,233283293.0,85666389.02,3696864.586,2.431942e+09,10.4248,2.431942e+09,3407385770,6287895.75,1985672.75,2705145.5,138095.25,48511.5,32863.75,60468.25,49936.75,6185803.75,7.55,4.98,87.48,22.9,64.05,13.05,2217524.25,201868.5,729121.0,819756.25,312139.0,154639.5,9.10,103175.75,132850.0,14.38,34.15,51.48,115904.00,3274930.36,3390834.36,3.42,96.58,2.71,NaN,2650851.5,...,82945431.68,79175822.57,83145853.15,11.4279,12.3940,12.1350,23.79,24.57,24.95,1,1,1,11.656458,13.013700,12.863100,531,488,354,9,0,0,0,0,0,1.0,1.0,168604786.3,77301961.80,6937981.798,790199357.1,4.6867,11.14,172566172.0,178336810.7,187871117.9,77126570.51,78369197.22,76660019.43,6901180.302,6903122.627,6771825.850,838052738.6,909786457.9,933759501.6,4.8564,5.1015,4.9702,11.18,11.35,11.32

In [33]:
new_est2.drop(columns=['Unnamed: 0'],inplace=True)

In [35]:
new_est2.to_csv('../Factors and Ridership Data/Estimation_File/estimation_file2.csv')