In [1]:
import pandas as pd
import numpy as np

In [3]:
tsd_list=pd.read_csv('../Factors and Ridership Data/Final Datasets/tsd_final_updated.csv')
tsd_list.head()

,Unnamed: 0,CBSA Title,CBSA Code,Area_acre,Year,POP_CENSUSTRACT,CBSA
0,0,"Abilene, TX",10180.0,1216.0,2005,6947.0,"Abilene, TX Metro Area"
1,1,"Akron, OH",10420.0,13644.8,2005,118025.0,"Akron, OH Metro Area"
2,2,"Albany, GA",10500.0,691.2,2005,2307.0,"Albany, GA Metro Area"
3,3,"Albany-Lebanon, OR",10540.0,2259.2,2005,13058.0,"Albany-Lebanon, OR Metro Area"
4,4,"Albany-Schenectady-Troy, NY",10580.0,17900.8,2005,193466.0,"Albany-Schenectady-Troy, NY Metro Area"

In [4]:
df=pd.read_csv('tsd_missing.csv')
df.head()

    CBSA Mode  Year               MNAME_x  POP_CENSUSTRACT
0  10420  Bus  2002  Akron, OH Metro Area         119786.0
1  10420  Bus  2003  Akron, OH Metro Area         119199.0
2  10420  Bus  2004  Akron, OH Metro Area         118612.0
3  10420  Bus  2005  Akron, OH Metro Area         118025.0
4  10420  Bus  2006  Akron, OH Metro Area         117438.0

In [6]:
df.CBSA.describe()

count     4565.000000
mean     30211.546550
std      11469.503246
min      10420.000000
25%      19740.000000
50%      30780.000000
75%      40420.000000
max      49740.000000
Name: CBSA, dtype: float64

In [5]:
new=pd.merge(df,tsd_list,left_on=['CBSA','Year'],right_on=['CBSA Code','Year'],how='left',indicator=True)
new.head()

,CBSA_x,Mode,Year,MNAME_x,POP_CENSUSTRACT_x,Unnamed: 0,CBSA Title,CBSA Code,Area_acre,POP_CENSUSTRACT_y,CBSA_y,_merge
0,10420,Bus,2002,"Akron, OH Metro Area",119786.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,10420,Bus,2003,"Akron, OH Metro Area",119199.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,10420,Bus,2004,"Akron, OH Metro Area",118612.0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,10420,Bus,2005,"Akron, OH Metro Area",118025.0,1.0,"Akron, OH",10420.0,13644.8,118025.0,"Akron, OH Metro Area",both
4,10420,Bus,2006,"Akron, OH Metro Area",117438.0,337.0,"Akron, OH",10420.0,13644.8,117438.0,"Akron, OH Metro Area",both

In [8]:
new[new['CBSA_x']==31080]

,CBSA_x,Mode,Year,MNAME_x,POP_CENSUSTRACT_x,Unnamed: 0,CBSA Title,CBSA Code,Area_acre,POP_CENSUSTRACT_y,CBSA_y,_merge
2318,31080,Bus,2002,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2319,31080,Bus,2003,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2320,31080,Bus,2004,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2321,31080,Bus,2005,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,182.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10825958.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2322,31080,Bus,2006,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,518.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10790637.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2323,31080,Bus,2007,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,854.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10755316.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2324,31080,Bus,2008,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,1190.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10719995.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2325,31080,Bus,2009,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,1526.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10684674.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2326,31080,Bus,2010,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,1862.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10649353.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2327,31080,Bus,2011,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,2198.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10614032.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2328,31080,Bus,2012,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,2534.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10684048.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2329,31080,Bus,2013,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,2870.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10752006.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2330,31080,Bus,2014,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,3206.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10849167.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2331,31080,Bus,2015,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,3542.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10921327.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2332,31080,Bus,2016,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,3878.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10944789.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2333,31080,Bus,2017,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,4214.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,11003240.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2334,31080,Bus,2018,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,4550.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,11061691.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2335,31080,Rail,2002,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2336,31080,Rail,2003,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2337,31080,Rail,2004,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2338,31080,Rail,2005,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,182.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10825958.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2339,31080,Rail,2006,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,518.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10790637.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2340,31080,Rail,2007,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,854.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10755316.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2341,31080,Rail,2008,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,1190.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10719995.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2342,31080,Rail,2009,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,1526.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10684674.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2343,31080,Rail,2010,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,1862.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10649353.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2344,31080,Rail,2011,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,2198.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10614032.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2345,31080,Rail,2012,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,2534.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10684048.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2346,31080,Rail,2013,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,2870.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10752006.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2347,31080,Rail,2014,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,3206.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10849167.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2348,31080,Rail,2015,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,3542.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10921327.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2349,31080,Rail,2016,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,3878.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,10944789.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2350,31080,Rail,2017,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,4214.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,11003240.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both
2351,31080,Rail,2018,"Los Angeles-Long Beach-Santa Ana, CA Metro Area",NaN,4550.0,"Los Angeles-Long Beach-Anaheim, CA",31080.0,711955.2,11061691.0,"Los Angeles-Long Beach-Anaheim, CA Metro Area",both