In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import linearmodels as lm
import matplotlib
import math
import statsmodels.formula.api as smf

from linearmodels.panel import PanelOLS
from linearmodels.panel import RandomEffects
from linearmodels.panel import FirstDifferenceOLS
from linearmodels.panel import compare
from matplotlib import pyplot as plt

from pandas.api.types import is_numeric_dtype

pd.set_option('display.max_columns', 500)

%matplotlib inline

/Users/rianajawad/anaconda3/lib/python3.7/site-packages/linearmodels/panel/data.py:10: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import (Categorical, DataFrame, Index, MultiIndex, Panel, Series,

In [2]:
df=pd.read_csv('../../Factors and Ridership Data/Shared_dataset/merged_df_3.csv',
                    encoding='utf-8')
df.head()

,Unnamed: 0,CBSA,NEW_CBSA,MNAME,Mode,Year,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_TOTAL,FARE_per_UPT,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,JTW_DA,JTW_CARPOOL,JTW_TRANSIT,MEAN_TT,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,POP_CENSUSTRACT,AVG_SPEED,2018_Dollar_Multiplier,TNC_ARRIVAL,Link_x,TNC_FLAG,YEARS_SINCE_TNC,PROBLEM_FLAG,NOTE,dockCt,docklessCt,scooterCt,PBS_Start,PBS_End,PBS_Flag,Link_y,walkscore,transit,bike
0,0,10180,NaN,"Abilene, TX Metro Area",Bus,2002,493073.0,389678.0,493073.0,389678.0,29016.0,162609.0,0.329787,141756054,117258.2188,87723.96875,23752.17188,2987.484375,19756.67188,22848.10938,17091.51563,-1768.703125,147631.94,22.30,12.89,64.82,31.23,54.90,13.87,61601.69,1195.73,27303.56,21926.16,8121.36,3054.88,1.94,25775.875,30134.875,61.74,34.07,4.19,47503.52,6031.48,325.61,15.75,3945.33,73760.33,77705.67,5.08,94.92,1.32,NaN,6848,13.43,1.40,2016,Judgement Call based on Population,0,0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1,1,10180,NaN,"Abilene, TX Metro Area",Bus,2003,475747.0,383239.0,475747.0,383239.0,28597.0,173563.0,0.364822,141756054,127098.1250,93677.12500,26964.31250,2834.062500,19941.31250,21972.56250,18472.93750,5303.8125,147198.25,20.72,12.86,66.43,29.78,56.41,13.81,61229.25,1515.06,25910.75,22846.38,8038.56,2918.50,2.47,29077.500,35373.500,57.54,36.92,5.54,49409.94,6680.06,304.56,16.09,4222.75,75377.08,79599.83,5.30,94.70,1.50,NaN,6881,13.40,1.37,2016,Judgement Call based on Population,0,0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,2,10180,NaN,"Abilene, TX Metro Area",Bus,2004,469981.0,388907.0,469981.0,388907.0,29126.0,185046.0,0.393731,141756054,137113.5000,99787.50000,30227.75000,2648.750000,20132.75000,21085.75000,19808.25000,12620.75,146801.00,19.13,12.88,68.00,28.30,57.95,13.75,60833.00,1823.75,24514.00,23787.50,7942.75,2765.00,3.00,32452.000,40728.000,53.25,39.83,6.93,51343.25,7384.75,282.75,16.45,3712.17,75862.08,79574.25,4.67,95.33,1.79,NaN,6914,13.35,1.33,2016,Judgement Call based on Population,0,0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,3,10180,NaN,"Abilene, TX Metro Area",Bus,2005,507165.0,444176.0,507165.0,444176.0,31147.0,213965.0,0.421884,141756054,146427.0000,105269.00000,33286.00000,2591.000000,20297.00000,20244.00000,21328.00000,18960,146258.00,17.60,12.70,69.70,26.90,59.40,13.70,60532.00,2175.00,23133.00,24645.00,7899.00,2680.00,3.59,35535.000,45619.000,49.30,42.50,8.20,53169,7865,264,16.7,3375.75,76704.50,80080.25,4.22,95.78,2.23,1216.0,6947,14.26,1.29,2016,Judgement Call based on Population,0,0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,4,10180,NaN,"Abilene, TX Metro Area",Bus,2006,493638.0,441300.0,493638.0,441300.0,30750.0,201795.0,0.408791,141756054,158548.0000,113266.00000,37165.00000,2023.000000,20570.00000,19222.00000,22110.00000,29210,146298.00,15.80,13.30,70.90,25.20,61.20,13.60,59850.00,2356.00,21689.00,25837.00,7647.00,2321.00,3.94,39784.000,52364.000,44.00,46.10,9.90,55425,9243,233,17.4,3242.08,78203.25,81445.33,3.98,96.02,2.52,1216.0,6980,14.35,1.25,2016,Judgement Call based on Population,0,0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [10]:
df[df['POP_CENSUSTRACT']=='#REF!']

,CBSA,NEW_CBSA,MNAME,Mode,Year,UPT,VRM,UPT_ADJ,VRM_ADJ,VRH_ADJ,FARE_TOTAL,FARE_per_UPT,AREALANDPT,Tot_Pop,Tot_Instate_Pop,Tot_Outstate_Pop,Tot_NonUSA_POP,Total_Median_Income_Individual,Native_Instate_Med_Inc_Indiv,Native_Outstate_Med_Inc_Indiv,Native_Outcountry_Med_Inc_Indiv,Total_Pop_Poverty,Pop_Below100_Poverty,Pop_Below150_Poverty,Pop_Above150_Poverty,Age_under18,Age_18to64,Age_over64,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,PCT_HH_NO_VEH,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,JTW_DA,JTW_CARPOOL,JTW_TRANSIT,MEAN_TT,TOT_UNEMP_MSA,TOT_EMP_MSA,TOT_LABOR_MSA,UNEMP_RATE_PCT,EMP_RATE_PCT,GasPrice,Area_acre,POP_CENSUSTRACT,AVG_SPEED,2018_Dollar_Multiplier,TNC_ARRIVAL,Link_x,TNC_FLAG,YEARS_SINCE_TNC,PROBLEM_FLAG,NOTE,dockCt,docklessCt,scooterCt,PBS_Start,PBS_End,PBS_Flag,Link_y,walkscore,transit,bike
2980,29140,NaN,"Lafayette, IN Metro Area",Bus,2018,4713280.0,1804300.0,4713280.0,1804300.0,141832.0,3108355.75,0.659489,166040040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,3562.64,108911.36,112474.0,3.17,96.83,2.72,NaN,#REF!,12.72,1.0,2014,https://www.theledger.com/news/20141204/smartp...,1,4,1.0,MSA definition changed. New one not found.,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [3]:
df=df.drop(columns=['Unnamed: 0'])

In [4]:
bus_ridership=df[df['Mode']=='Bus']
rail_ridership=df[df['Mode']=='Rail']

In [5]:
estimation_df_bus=bus_ridership.groupby(['CBSA','Year']).mean()

In [6]:
list(estimation_df_bus)

['NEW_CBSA',
 'UPT',
 'VRM',
 'UPT_ADJ',
 'VRM_ADJ',
 'VRH_ADJ',
 'FARE_TOTAL',
 'FARE_per_UPT',
 'AREALANDPT',
 'Tot_Pop',
 'Tot_Instate_Pop',
 'Tot_Outstate_Pop',
 'Tot_NonUSA_POP',
 'Total_Median_Income_Individual',
 'Native_Instate_Med_Inc_Indiv',
 'Native_Outstate_Med_Inc_Indiv',
 'Total_Pop_Poverty',
 'Pop_Below100_Poverty',
 'Pop_Below150_Poverty',
 'Pop_Above150_Poverty',
 'Age_under18',
 'Age_18to64',
 'Age_over64',
 'Total_HH',
 'HH_0Veh',
 'HH_1Veh',
 'HH_2Veh',
 'HH_3Veh',
 'HH_4+Veh',
 'PCT_HH_NO_VEH',
 'HH_MED_INC',
 'HH_MEAN_INC',
 'INC_U35',
 'INC_35_100',
 'INC_100P',
 'TOT_UNEMP_MSA',
 'TOT_EMP_MSA',
 'TOT_LABOR_MSA',
 'UNEMP_RATE_PCT',
 'EMP_RATE_PCT',
 'GasPrice',
 'Area_acre',
 'AVG_SPEED',
 '2018_Dollar_Multiplier',
 'TNC_ARRIVAL',
 'TNC_FLAG',
 'YEARS_SINCE_TNC',
 'PROBLEM_FLAG',
 'dockCt',
 'docklessCt',
 'scooterCt',
 'PBS_Start',
 'PBS_End',
 'PBS_Flag',
 'walkscore',
 'transit',
 'bike']

In [13]:
mod=PanelOLS.from_formula('UPT \
                    ~ VRM \
                    + Tot_Pop \
                    + GasPrice \
                    + Total_HH \
                    + HH_0Veh \
                    + AVG_SPEED \
                    + HH_1Veh \
                    + HH_MED_INC \
                    + INC_U35 \
                    + INC_35_100 \
                    + TOT_EMP_MSA \
                    + UNEMP_RATE_PCT \
                    + YEARS_SINCE_TNC \
                    + Age_over64',data=estimation_df_bus)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    UPT   R-squared:                        0.9858
Estimator:                   PanelOLS   R-squared (Between):              0.9902
No. Observations:                5279   R-squared (Within):               0.0854
Date:                Fri, Oct 25 2019   R-squared (Overall):              0.9858
Time:                        10:03:42   Log-likelihood                -9.252e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                   2.607e+04
Entities:                         313   P-value                           0.0000
Avg Obs:                       16.866   Distribution:                 F(14,5265)
Min Obs:                      10.0000
Max Obs:                       17.000   F-statistic (robust):          2.607e+04
                                        P-value                           0.0000
Time periods:                      17   Distribution:                 F(14,5265)
Avg Obs:                       310.53
Min Obs:                       306.00
Max Obs:                       313.00

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
VRM                 3.1216     0.0341     91.496     0.0000      3.0547      3.1885
Tot_Pop             11.981     1.4270     8.3959     0.0000      9.1834      14.778
GasPrice         8.124e+04   2.34e+05     0.3472     0.7285  -3.775e+05   5.399e+05
Total_HH           -104.88     6.5625    -15.982     0.0000     -117.75     -92.017
HH_0Veh             261.59     3.8075     68.703     0.0000      254.12      269.05
AVG_SPEED       -4.491e+04   1.18e+04    -3.8068     0.0001  -6.803e+04  -2.178e+04
HH_1Veh            -12.730     10.123    -1.2575     0.2086     -32.575      7.1163
HH_MED_INC         -87.063     20.514    -4.2441     0.0000     -127.28     -46.847
INC_U35             8342.2  1.749e+04     0.4769     0.6335  -2.595e+04   4.263e+04
INC_35_100       1.356e+04  2.646e+04     0.5126     0.6082   -3.83e+04   6.543e+04
TOT_EMP_MSA         36.882     3.7951     9.7182     0.0000      29.442      44.321
UNEMP_RATE_PCT  -9.366e+04  5.874e+04    -1.5945     0.1109  -2.088e+05   2.149e+04
YEARS_SINCE_TNC -1.286e+06  1.691e+05    -7.6060     0.0000  -1.617e+06  -9.545e+05
Age_over64       2.736e+05  4.357e+04     6.2801     0.0000   1.882e+05    3.59e+05
===================================================================================

In [14]:
estimation_df_bus['UPT_ADJ_MIL']=estimation_df_bus['UPT_ADJ']/1000000
estimation_df_bus['VRM_ADJ_MIL']=estimation_df_bus['VRM_ADJ']/1000000
estimation_df_bus['Tot_Pop_MIL']=estimation_df_bus['Tot_Pop']/1000000

In [15]:
mod=PanelOLS.from_formula('UPT_ADJ_MIL \
                    ~ VRM_ADJ_MIL \
                    + Tot_Pop_MIL \
                    + GasPrice \
                    + Total_HH \
                    + HH_0Veh \
                    + AVG_SPEED \
                    + HH_1Veh \
                    + HH_MED_INC \
                    + INC_U35 \
                    + INC_35_100 \
                    + TOT_EMP_MSA \
                    + UNEMP_RATE_PCT \
                    + YEARS_SINCE_TNC \
                    + Age_over64',data=estimation_df_bus)
res=mod.fit()
print(res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:            UPT_ADJ_MIL   R-squared:                        0.9858
Estimator:                   PanelOLS   R-squared (Between):              0.9902
No. Observations:                5279   R-squared (Within):               0.0854
Date:                Fri, Oct 25 2019   R-squared (Overall):              0.9858
Time:                        10:07:02   Log-likelihood                -1.959e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                   2.607e+04
Entities:                         313   P-value                           0.0000
Avg Obs:                       16.866   Distribution:                 F(14,5265)
Min Obs:                      10.0000
Max Obs:                       17.000   F-statistic (robust):          2.607e+04
                                        P-value                           0.0000
Time periods:                      17   Distribution:                 F(14,5265)
Avg Obs:                       310.53
Min Obs:                       306.00
Max Obs:                       313.00

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
VRM_ADJ_MIL         3.1216     0.0341     91.496     0.0000      3.0547      3.1885
Tot_Pop_MIL         11.981     1.4270     8.3959     0.0000      9.1834      14.778
GasPrice            0.0812     0.2340     0.3472     0.7285     -0.3775      0.5399
Total_HH           -0.0001  6.562e-06    -15.982     0.0000     -0.0001  -9.202e-05
HH_0Veh             0.0003  3.808e-06     68.703     0.0000      0.0003      0.0003
AVG_SPEED          -0.0449     0.0118    -3.8068     0.0001     -0.0680     -0.0218
HH_1Veh         -1.273e-05  1.012e-05    -1.2575     0.2086  -3.258e-05   7.116e-06
HH_MED_INC      -8.706e-05  2.051e-05    -4.2441     0.0000     -0.0001  -4.685e-05
INC_U35             0.0083     0.0175     0.4769     0.6335     -0.0260      0.0426
INC_35_100          0.0136     0.0265     0.5126     0.6082     -0.0383      0.0654
TOT_EMP_MSA      3.688e-05  3.795e-06     9.7182     0.0000   2.944e-05   4.432e-05
UNEMP_RATE_PCT     -0.0937     0.0587    -1.5945     0.1109     -0.2088      0.0215
YEARS_SINCE_TNC    -1.2859     0.1691    -7.6060     0.0000     -1.6173     -0.9545
Age_over64          0.2736     0.0436     6.2801     0.0000      0.1882      0.3590
===================================================================================