In [1]:
import pandas as pd
import numpy as np

In [4]:
acs_2005=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_05_EST_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2005

,Id,Id2,Geography,Estimate; Total:,Margin of Error; Total:,Estimate; No vehicle available,Margin of Error; No vehicle available,Estimate; 1 vehicle available,Margin of Error; 1 vehicle available,Estimate; 2 vehicles available,...,Estimate; 4-or-more-person household: - No vehicle available,Margin of Error; 4-or-more-person household: - No vehicle available,Estimate; 4-or-more-person household: - 1 vehicle available,Margin of Error; 4-or-more-person household: - 1 vehicle available,Estimate; 4-or-more-person household: - 2 vehicles available,Margin of Error; 4-or-more-person household: - 2 vehicles available,Estimate; 4-or-more-person household: - 3 vehicles available,Margin of Error; 4-or-more-person household: - 3 vehicles available,Estimate; 4-or-more-person household: - 4 or more vehicles available,Margin of Error; 4-or-more-person household: - 4 or more vehicles available
0,3100000US10180,10180,"Abilene, TX Metro Area",60532,1337,2175,650,23133,1921,24645,...,148,159,2909,822,5735,1058,2350,591,1215,458
1,3100000US10420,10420,"Akron, OH Metro Area",276416,3593,20661,2339,85198,4445,112380,...,1877,807,3981,1050,25934,2189,14912,1845,10305,1794
2,3100000US10500,10500,"Albany, GA Metro Area",59384,1817,7093,1390,18516,2152,20546,...,1096,510,2688,838,4936,1073,4080,976,1536,489
3,3100000US10580,10580,"Albany-Schenectady-Troy, NY Metro Area",337662,3587,30104,2308,122342,5202,130417,...,2172,641,8210,1476,33341,2684,15823,2003,7062,1307
4,3100000US10740,10740,"Albuquerque, NM Metro Area",319677,3262,18413,2378,110293,4688,125079,...,1309,733,9656,1828,28904,2439,19035,1904,9279,1572
5,3100000US10780,10780,"Alexandria, LA Metro Area",55401,1441,4539,1012,18939,1842,22357,...,539,301,2098,693,5262,893,2685,625,1563,556
6,3100000US10900,10900,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",302968,2697,23930,2291,91510,3481,122452,...,2227,775,6686,1181,33887,2417,15575,1879,12511,1831
7,3100000US11020,11020,"Altoona, PA Metro Area",52145,886,5684,1160,18877,1636,18730,...,647,437,1894,661,4315,749,2484,653,1171,366
8,3100000US11100,11100,"Amarillo, TX Metro Area",88509,1496,4338,953,32326,2285,34565,...,149,168,4290,1061,8190,1147,3815,748,3610,896
9,3100000US11180,11180,"Ames, IA Metro Area",31064,1109,1178,406,10564,1156,11591,...,0,268,674,342,2096,522,1467,444,1276,540
10,3100000US11260,11260,"Anchorage, AK Metro Area",124902,1457,7835,1335,39839,2262,53795,...,797,402,4446,1053,15559,1564,6222,1205,3246,693
11,3100000US11300,11300,"Anderson, IN Metro Area",51244,1386,2719,638,16311,1499,21286,...,0,268,1137,560,4082,806,1862,615,1053,321
12,3100000US11340,11340,"Anderson, SC Metro Area",68919,1895,4167,1169,20937,2160,28242,...,452,291,2322,923,7130,1502,2876,766,2531,690
13,3100000US11460,11460,"Ann Arbor, MI Metro Area",131268,2123,9669,1505,44966,2722,53893,...,174,161,2855,707,13381,1446,5898,1075,4274,1024
14,3100000US11500,11500,"Anniston-Oxford, AL Metro Area",46986,1496,3076,1027,12807,1460,20093,...,42,74,1495,546,4619,1235,1883,746,1348,554
15,3100000US11540,11540,"Appleton, WI Metro Area",83180,1157,2934,790,22102,1736,39725,...,46,76,962,480,11276,1338,6196,1059,2147,521
16,3100000US11700,11700,"Asheville, NC Metro Area",167464,2882,7908,1413,56758,3756,66433,...,458,331,3349,1131,12588,1650,6226,1176,4419,1116
17,3100000US12020,12020,"Athens-Clarke County, GA Metro Area",68468,1868,4631,1037,20926,1830,25025,...,511,325,1562,634,6079,1212,3708,1114,3189,856
18,3100000US12060,12060,"Atlanta-Sandy Springs-Marietta, GA Metro Area",1781766,10930,105885,5548,564992,14156,735712,...,18668,3170,64647,5287,213823,8070,105782,6044,53489,3820
19,3100000US12100,12100,"Atlantic City, NJ Metro Area",101584,2700,13954,1955,35426,2889,36179,...,1321,478,3300,886,11635,1701,5605,1266,2773,1068
20,3100000US12220,12220,"Auburn-Opelika, AL Metro Area",50793,1214,3214,652,16804,1566,18509,...,302,215,797,405,3218,801,2784,889,2076,627
21,3100000US12260,12260,"Augusta-Richmond County, GA-SC Metro Area",199470,2759,14207,2134,61149,3497,75242,...,3281,1265,8660,1649,20252,2494,10901,1675,6609,1444
22,3100000US12420,12420,"Austin-Round Rock, TX Metro Area",540685,3893,30036,3055,197272,6381,226617,...,3131,875,20235,2882,62085,4136,24396,2165,14299,2373
23,3100000US12540,12540,"Bakersfield, CA Metro Area",231566,3346,17502,2283,71680,4498,88131,...,2764,870,16049,2806,34316,3006,17101,2799,9359,1382
24,3100000US12580,12580,"Baltimore-Towson, MD Metro Area",1002709,5360,116542,5977,330915,7662,362000,...,13819,2037,33071,4192,95650,4878,50742,3693,31783,2659
25,3100000US12620,12620,"Bangor, ME Metro Area",60822,1196,3726,884,19735,1808,24894,...,213,157,1236,421,4643,801,2859,704,1261,469
26,3100000US12700,12700,"Barnstable Town, MA Metro Area",100254,3152,3464,926,34415,3033,43142,...,0,268,899,515,10862,1959,6129,1618,2928,975
27,3100000US12940,12940,"Baton Rouge, LA Metro Area",273980,3780,19540,2637,100347,4839,107109,...,3725,1305,13972,2742,29063,3104,14461,2156,8141,1458
28,3100000US12980,12980,"Battle Creek, MI Metro Area",54821,1220,3733,865,18958,1783,20027,...,395,316,1562,530,5962,979,2830,1086,1514,524
29,3100000US13020,13020,"Bay City, MI Metro Area",45043,1175,2427,735,16338,1454,17308,...,72,115,673,440,4747,817,2106,640,1180,439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,3100000US46220,46220,"Tuscaloosa, AL Metro Area",79395,2382,7362,1370,27648,2213,29375,...,732,518,2986,839,5277,1224,3665,951,1522,528
329,3100000US46340,46340,"Tyler, TX Metro Area",68162,1518,3999,1020,22475,2118,29067,...,580,472,2426,898,8123,1251,4406,1054,1488,612
330,3100000US46540,46540,"Utica-Rome, NY Metro Area",117643,2247,12110,1908,44813,3124,42608,...,1105,531,4667,1310,10505,1525,5066,1036,2184,576
331,3100000US46660,46660,"Valdosta, GA Metro Area",47763,1289,2897,1041,14144,1789,20351,...,305,253,1384,675,5900,1080,2503,837,1421,496
332,3100000US46700,46700,"Vallejo-Fairfield, CA Metro Area",134624,2179,8522,1730,33092,2791,53071,...,760,430,3704,962,15923,2197,12285,2019,7530,1292
333,3100000US46940,46940,"Vero Beach, FL Metro Area",57315,1724,2235,744,24928,2103,22229,...,239,299,1319,685,4711,1346,2098,771,1032,580
334,3100000US47020,47020,"Victoria, TX Metro Area",43031,1414,2915,873,14855,1679,18471,...,305,235,2211,745,6594,1224,2145,668,787,322
335,3100000US47220,47220,"Vineland-Millville-Bridgeton, NJ Metro Area",49914,1213,5865,1231,16739,1731,18355,...,590,338,2151,630,5785,1036,2441,734,2165,697
336,3100000US47260,47260,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",617762,4448,38333,3191,193409,7135,238463,...,4457,1030,19262,2185,59275,2828,37169,2666,22856,2280
337,3100000US47300,47300,"Visalia-Porterville, CA Metro Area",119621,1485,9808,1718,39757,2726,46559,...,2691,862,13445,2018,20251,1692,7293,1087,3802,816
338,3100000US47380,47380,"Waco, TX Metro Area",80546,1611,6471,1700,27531,2622,30355,...,904,557,3428,841,7757,1237,4465,1155,3129,727
339,3100000US47580,47580,"Warner Robins, GA Metro Area",47700,1342,3419,997,15878,1896,16887,...,480,444,1075,545,4980,1270,3422,1006,1566,699
340,3100000US47900,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",1944465,6862,196099,6900,623843,11594,719955,...,24567,2696,56372,4310,215435,6649,111755,5120,73164,4603
341,3100000US47940,47940,"Waterloo-Cedar Falls, IA Metro Area",65373,1016,3825,767,19516,1708,27393,...,129,154,1266,677,4828,741,2317,563,2488,464
342,3100000US48140,48140,"Wausau, WI Metro Area",52478,901,2328,562,14097,1233,23592,...,85,116,721,477,5613,954,2761,594,2269,492
343,3100000US48260,48260,"Weirton-Steubenville, WV-OH Metro Area",53906,1248,4364,850,17182,1607,21329,...,160,133,1079,467,3935,807,2028,589,1571,449
344,3100000US48300,48300,"Wenatchee, WA Metro Area",39057,1223,1912,683,10938,1490,16610,...,365,383,1347,673,3805,905,2124,579,1185,428
345,3100000US48540,48540,"Wheeling, WV-OH Metro Area",62947,1433,5080,810,20454,1726,23983,...,234,228,1374,628,4429,818,3003,843,2526,781
346,3100000US48620,48620,"Wichita, KS Metro Area",226366,3035,13501,1860,68447,3607,91537,...,831,479,7006,1224,24778,1988,13884,1876,9903,1376
347,3100000US48660,48660,"Wichita Falls, TX Metro Area",55559,1929,3015,796,18919,1892,23651,...,175,236,1681,820,5550,1275,3026,918,1137,402
348,3100000US48700,48700,"Williamsport, PA Metro Area",48270,903,3733,754,15447,1323,19040,...,192,154,1050,488,4120,766,2864,664,1550,441
349,3100000US48900,48900,"Wilmington, NC Metro Area",138238,2595,8647,1499,47365,3083,57018,...,301,252,2909,1114,11720,1438,4361,1046,2336,815
350,3100000US49020,49020,"Winchester, VA-WV Metro Area",43653,1447,2301,801,10777,1418,17886,...,178,185,662,392,5251,902,2384,707,1974,491
351,3100000US49180,49180,"Winston-Salem, NC Metro Area",180887,2451,9636,1717,55256,3611,70900,...,928,519,6371,1432,16995,2086,8578,1459,5669,1142
352,3100000US49340,49340,"Worcester, MA Metro Area",284040,3222,21771,2662,94272,3606,117331,...,1399,581,8332,1588,36655,2719,15593,2002,8780,1440
353,3100000US49420,49420,"Yakima, WA Metro Area",76288,1245,5000,1102,20658,1927,27474,...,295,245,2242,720,9889,1379,6169,1234,4339,960
354,3100000US49620,49620,"York-Hanover, PA Metro Area",159432,2242,8436,1235,45628,2744,65975,...,1171,553,3667,1287,16611,2060,8846,1439,7101,1209
355,3100000US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",236779,2831,15824,1881,83953,3587,91387,...,2252,836,6168,1376,21064,1855,10930,1682,7367,1202
356,3100000US49700,49700,"Yuba City, CA Metro Area",52227,1231,3357,1003,14393,1533,20791,...,65,104,1960,795,6006,1262,3416,832,2815,867
357,3100000US49740,49740,"Yuma, AZ Metro Area",66877,1783,4837,1157,27992,2304,21841,...,708,572,2867,1035,7641,1225,4298,942,2511,906

In [11]:
acs_05=acs_2005.filter(['Id','Id2','Geography',
                        'Estimate; Total:',
                        'Estimate; No vehicle available',
                        'Estimate; 1 vehicle available',
                        'Estimate; 2 vehicles available',
                       'Estimate; 3 vehicles available',
                       'Estimate; 4 or more vehicles available'],
                      axis=1)

In [12]:
list(acs_05)

['Id',
 'Id2',
 'Geography',
 'Estimate; Total:',
 'Estimate; No vehicle available',
 'Estimate; 1 vehicle available',
 'Estimate; 2 vehicles available',
 'Estimate; 3 vehicles available',
 'Estimate; 4 or more vehicles available']

In [13]:
acs_05=acs_05.rename(index=str, columns={'Estimate; Total:':'Total_HH',
                                         'Estimate; No vehicle available':'HH_0Veh',
                                         'Estimate; 1 vehicle available':'HH_1Veh',
                                         'Estimate; 2 vehicles available':'HH_2Veh',
                                         'Estimate; 3 vehicles available':'HH_3Veh',
                                         'Estimate; 4 or more vehicles available':'HH_4+Veh'})

In [15]:
def HH_veh(df):
    new_df=df.filter(['Id','Id2','Geography',
                        'Estimate; Total:',
                        'Estimate; No vehicle available',
                        'Estimate; 1 vehicle available',
                        'Estimate; 2 vehicles available',
                       'Estimate; 3 vehicles available',
                       'Estimate; 4 or more vehicles available'],
                      axis=1)
    new_df2=new_df.rename(index=str, columns={'Estimate; Total:':'Total_HH',
                                         'Estimate; No vehicle available':'HH_0Veh',
                                         'Estimate; 1 vehicle available':'HH_1Veh',
                                         'Estimate; 2 vehicles available':'HH_2Veh',
                                         'Estimate; 3 vehicles available':'HH_3Veh',
                                         'Estimate; 4 or more vehicles available':'HH_4+Veh'})
    return new_df2

In [16]:
acs_2006=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_06_EST_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2007=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_07_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2008=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_08_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2009=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_09_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2010=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_10_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2011=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_11_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2012=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_12_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2013=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_13_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2014=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_14_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2015=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_15_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2016=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_16_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2017=pd.read_csv('../Factors and Ridership Data/HH Vehicle Data/ACS_17_1YR_B08201_with_ann.csv',
                    encoding='utf-8',skiprows=1)

In [19]:
acs_06=HH_veh(acs_2006)
acs_07=HH_veh(acs_2007)
acs_08=HH_veh(acs_2008)
acs_09=HH_veh(acs_2009)

In [20]:
acs_05['Year']=2005
acs_06['Year']=2006
acs_07['Year']=2007
acs_08['Year']=2008
acs_09['Year']=2009

In [108]:
merge_1=pd.concat([acs_05,acs_06],ignore_index=True,sort=False)

In [109]:
merge_2=pd.concat([merge_1,acs_07],ignore_index=True, sort=False)

In [110]:
merge_3=pd.concat([merge_2,acs_08],ignore_index=True, sort=False)

In [111]:
merge_4=pd.concat([merge_3,acs_09],ignore_index=True, sort=False)

In [112]:
merge_5=pd.concat([merge_4,acs_10],ignore_index=True, sort=False)

In [113]:
merge_6=pd.concat([merge_5,acs_11],ignore_index=True, sort=False)

In [114]:
merge_7=pd.concat([merge_6,acs_12],ignore_index=True, sort=False)

In [115]:
merge_8=pd.concat([merge_7,acs_13],ignore_index=True, sort=False)

In [116]:
merge_9=pd.concat([merge_8,acs_14],ignore_index=True, sort=False)

In [117]:
merge_10=pd.concat([merge_9,acs_15],ignore_index=True, sort=False)

In [118]:
merge_11=pd.concat([merge_10,acs_16],ignore_index=True, sort=False)

In [125]:
merge_final_VEH=pd.concat([merge_11,acs_17],ignore_index=True, sort=False)
merge_final_VEH

,Id,Id2,Geography,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,Year
0,3100000US10180,10180,"Abilene, TX Metro Area",60532,2175,23133,24645,7899,2680,2005
1,3100000US10420,10420,"Akron, OH Metro Area",276416,20661,85198,112380,40847,17330,2005
2,3100000US10500,10500,"Albany, GA Metro Area",59384,7093,18516,20546,9969,3260,2005
3,3100000US10580,10580,"Albany-Schenectady-Troy, NY Metro Area",337662,30104,122342,130417,41631,13168,2005
4,3100000US10740,10740,"Albuquerque, NM Metro Area",319677,18413,110293,125079,48207,17685,2005
5,3100000US10780,10780,"Alexandria, LA Metro Area",55401,4539,18939,22357,6914,2652,2005
6,3100000US10900,10900,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",302968,23930,91510,122452,43760,21316,2005
7,3100000US11020,11020,"Altoona, PA Metro Area",52145,5684,18877,18730,6421,2433,2005
8,3100000US11100,11100,"Amarillo, TX Metro Area",88509,4338,32326,34565,11919,5361,2005
9,3100000US11180,11180,"Ames, IA Metro Area",31064,1178,10564,11591,5314,2417,2005
10,3100000US11260,11260,"Anchorage, AK Metro Area",124902,7835,39839,53795,16322,7111,2005
11,3100000US11300,11300,"Anderson, IN Metro Area",51244,2719,16311,21286,8401,2527,2005
12,3100000US11340,11340,"Anderson, SC Metro Area",68919,4167,20937,28242,11110,4463,2005
13,3100000US11460,11460,"Ann Arbor, MI Metro Area",131268,9669,44966,53893,14966,7774,2005
14,3100000US11500,11500,"Anniston-Oxford, AL Metro Area",46986,3076,12807,20093,7812,3198,2005
15,3100000US11540,11540,"Appleton, WI Metro Area",83180,2934,22102,39725,14990,3429,2005
16,3100000US11700,11700,"Asheville, NC Metro Area",167464,7908,56758,66433,25699,10666,2005
17,3100000US12020,12020,"Athens-Clarke County, GA Metro Area",68468,4631,20926,25025,12282,5604,2005
18,3100000US12060,12060,"Atlanta-Sandy Springs-Marietta, GA Metro Area",1781766,105885,564992,735712,272662,102515,2005
19,3100000US12100,12100,"Atlantic City, NJ Metro Area",101584,13954,35426,36179,12209,3816,2005
20,3100000US12220,12220,"Auburn-Opelika, AL Metro Area",50793,3214,16804,18509,8805,3461,2005
21,3100000US12260,12260,"Augusta-Richmond County, GA-SC Metro Area",199470,14207,61149,75242,34507,14365,2005
22,3100000US12420,12420,"Austin-Round Rock, TX Metro Area",540685,30036,197272,226617,65171,21589,2005
23,3100000US12540,12540,"Bakersfield, CA Metro Area",231566,17502,71680,88131,38874,15379,2005
24,3100000US12580,12580,"Baltimore-Towson, MD Metro Area",1002709,116542,330915,362000,137232,56020,2005
25,3100000US12620,12620,"Bangor, ME Metro Area",60822,3726,19735,24894,9278,3189,2005
26,3100000US12700,12700,"Barnstable Town, MA Metro Area",100254,3464,34415,43142,14663,4570,2005
27,3100000US12940,12940,"Baton Rouge, LA Metro Area",273980,19540,100347,107109,35009,11975,2005
28,3100000US12980,12980,"Battle Creek, MI Metro Area",54821,3733,18958,20027,8702,3401,2005
29,3100000US13020,13020,"Bay City, MI Metro Area",45043,2427,16338,17308,6835,2135,2005
...,...,...,...,...,...,...,...,...,...,...
4780,310M300US46520,46520,"Urban Honolulu, HI Metro Area",312625,28812,109891,107898,38690,27334,2017
4781,310M300US46540,46540,"Utica-Rome, NY Metro Area",113323,11551,42975,42247,11510,5040,2017
4782,310M300US46660,46660,"Valdosta, GA Metro Area",53619,4062,16998,21190,7514,3855,2017
4783,310M300US46700,46700,"Vallejo-Fairfield, CA Metro Area",151127,8441,40933,52444,28066,21243,2017
4784,310M300US47020,47020,"Victoria, TX Metro Area",35635,1543,12945,14094,5270,1783,2017
4785,310M300US47220,47220,"Vineland-Bridgeton, NJ Metro Area",50696,5409,15999,17870,7291,4127,2017
4786,310M300US47260,47260,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",641881,42728,196378,257197,98181,47397,2017
4787,310M300US47300,47300,"Visalia-Porterville, CA Metro Area",137576,7039,43854,49439,25684,11560,2017
4788,310M300US47380,47380,"Waco, TX Metro Area",97310,7949,31787,36084,13899,7591,2017
4789,310M300US47460,47460,"Walla Walla, WA Metro Area",24256,1676,7178,9013,4233,2156,2017
4790,310M300US47580,47580,"Warner Robins, GA Metro Area",70479,5180,23429,25505,10940,5425,2017
4791,310M300US47900,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",2203717,210097,725490,804757,309188,154185,2017
4792,310M300US47940,47940,"Waterloo-Cedar Falls, IA Metro Area",67711,4109,20993,26723,10219,5667,2017
4793,310M300US48060,48060,"Watertown-Fort Drum, NY Metro Area",41548,4523,14678,15870,4720,1757,2017
4794,310M300US48140,48140,"Wausau, WI Metro Area",55084,2669,13813,24657,9599,4346,2017
4795,310M300US48260,48260,"Weirton-Steubenville, WV-OH Metro Area",48242,3512,18843,16859,5538,3490,2017
4796,310M300US48300,48300,"Wenatchee, WA Metro Area",42468,1801,11129,18125,7539,3874,2017
4797,310M300US48540,48540,"Wheeling, WV-OH Metro Area",51143,3910,17906,18495,7106,3726,2017
4798,310M300US48620,48620,"Wichita, KS Metro Area",246524,15165,74155,93202,41323,22679,2017
4799,310M300US48660,48660,"Wichita Falls, TX Metro Area",55426,3709,21226,20747,6915,2829,2017
4800,310M300US48700,48700,"Williamsport, PA Metro Area",46122,2772,14087,19655,6470,3138,2017
4801,310M300US48900,48900,"Wilmington, NC Metro Area",117982,7109,39493,45685,18620,7075,2017
4802,310M300US49020,49020,"Winchester, VA-WV Metro Area",51174,2180,13288,19826,10559,5321,2017
4803,310M300US49180,49180,"Winston-Salem, NC Metro Area",263215,15880,84272,94720,46704,21639,2017
4804,310M300US49340,49340,"Worcester, MA-CT Metro Area",352356,35387,115535,133979,46453,21002,2017
4805,310M300US49420,49420,"Yakima, WA Metro Area",82107,4101,22008,30460,16296,9242,2017
4806,310M300US49620,49620,"York-Hanover, PA Metro Area",171781,10602,49292,66949,31215,13723,2017
4807,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",231423,19650,80585,84501,31681,15006,2017
4808,310M300US49700,49700,"Yuba City, CA Metro Area",58173,4464,16032,21443,10366,5868,2017
4809,310M300US49740,49740,"Yuma, AZ Metro Area",74620,3785,26320,27297,12090,5128,2017

In [126]:
merge_final_VEH=merge_final_VEH.sort_values(by=['Geography','Year'])

In [40]:
list(acs_2010)

['Id',
 'Id2',
 'Geography',
 'Estimate; Total:',
 'Margin of Error; Total:',
 'Estimate; Total: - No vehicle available',
 'Margin of Error; Total: - No vehicle available',
 'Estimate; Total: - 1 vehicle available',
 'Margin of Error; Total: - 1 vehicle available',
 'Estimate; Total: - 2 vehicles available',
 'Margin of Error; Total: - 2 vehicles available',
 'Estimate; Total: - 3 vehicles available',
 'Margin of Error; Total: - 3 vehicles available',
 'Estimate; Total: - 4 or more vehicles available',
 'Margin of Error; Total: - 4 or more vehicles available',
 'Estimate; Total: - 1-person household:',
 'Margin of Error; Total: - 1-person household:',
 'Estimate; Total: - 1-person household: - No vehicle available',
 'Margin of Error; Total: - 1-person household: - No vehicle available',
 'Estimate; Total: - 1-person household: - 1 vehicle available',
 'Margin of Error; Total: - 1-person household: - 1 vehicle available',
 'Estimate; Total: - 1-person household: - 2 vehicles available',
 'Margin of Error; Total: - 1-person household: - 2 vehicles available',
 'Estimate; Total: - 1-person household: - 3 vehicles available',
 'Margin of Error; Total: - 1-person household: - 3 vehicles available',
 'Estimate; Total: - 1-person household: - 4 or more vehicles available',
 'Margin of Error; Total: - 1-person household: - 4 or more vehicles available',
 'Estimate; Total: - 2-person household:',
 'Margin of Error; Total: - 2-person household:',
 'Estimate; Total: - 2-person household: - No vehicle available',
 'Margin of Error; Total: - 2-person household: - No vehicle available',
 'Estimate; Total: - 2-person household: - 1 vehicle available',
 'Margin of Error; Total: - 2-person household: - 1 vehicle available',
 'Estimate; Total: - 2-person household: - 2 vehicles available',
 'Margin of Error; Total: - 2-person household: - 2 vehicles available',
 'Estimate; Total: - 2-person household: - 3 vehicles available',
 'Margin of Error; Total: - 2-person household: - 3 vehicles available',
 'Estimate; Total: - 2-person household: - 4 or more vehicles available',
 'Margin of Error; Total: - 2-person household: - 4 or more vehicles available',
 'Estimate; Total: - 3-person household:',
 'Margin of Error; Total: - 3-person household:',
 'Estimate; Total: - 3-person household: - No vehicle available',
 'Margin of Error; Total: - 3-person household: - No vehicle available',
 'Estimate; Total: - 3-person household: - 1 vehicle available',
 'Margin of Error; Total: - 3-person household: - 1 vehicle available',
 'Estimate; Total: - 3-person household: - 2 vehicles available',
 'Margin of Error; Total: - 3-person household: - 2 vehicles available',
 'Estimate; Total: - 3-person household: - 3 vehicles available',
 'Margin of Error; Total: - 3-person household: - 3 vehicles available',
 'Estimate; Total: - 3-person household: - 4 or more vehicles available',
 'Margin of Error; Total: - 3-person household: - 4 or more vehicles available',
 'Estimate; Total: - 4-or-more-person household:',
 'Margin of Error; Total: - 4-or-more-person household:',
 'Estimate; Total: - 4-or-more-person household: - No vehicle available',
 'Margin of Error; Total: - 4-or-more-person household: - No vehicle available',
 'Estimate; Total: - 4-or-more-person household: - 1 vehicle available',
 'Margin of Error; Total: - 4-or-more-person household: - 1 vehicle available',
 'Estimate; Total: - 4-or-more-person household: - 2 vehicles available',
 'Margin of Error; Total: - 4-or-more-person household: - 2 vehicles available',
 'Estimate; Total: - 4-or-more-person household: - 3 vehicles available',
 'Margin of Error; Total: - 4-or-more-person household: - 3 vehicles available',
 'Estimate; Total: - 4-or-more-person household: - 4 or more vehicles available',
 'Margin of Error; Total: - 4-or-more-person household: - 4 or more vehicles available']

In [42]:
def HH_veh_type2(df):
    new_df=df.filter(['Id','Id2','Geography',
                        'Estimate; Total:',
                        'Estimate; Total: - No vehicle available',
                        'Estimate; Total: - 1 vehicle available',
                        'Estimate; Total: - 2 vehicles available',
                       'Estimate; Total: - 3 vehicles available',
                       'Estimate; Total: - 4 or more vehicles available'],
                      axis=1)
    new_df2=new_df.rename(index=str, columns={'Estimate; Total:':'Total_HH',
                                         'Estimate; Total: - No vehicle available':'HH_0Veh',
                                         'Estimate; Total: - 1 vehicle available':'HH_1Veh',
                                         'Estimate; Total: - 2 vehicles available':'HH_2Veh',
                                         'Estimate; Total: - 3 vehicles available':'HH_3Veh',
                                         'Estimate; Total: - 4 or more vehicles available':'HH_4+Veh'})
    return new_df2

In [43]:
acs_10=HH_veh_type2(acs_2010)
acs_11=HH_veh_type2(acs_2011)
acs_12=HH_veh_type2(acs_2012)
acs_13=HH_veh_type2(acs_2013)
acs_14=HH_veh_type2(acs_2014)
acs_15=HH_veh_type2(acs_2015)
acs_16=HH_veh_type2(acs_2016)
acs_17=HH_veh_type2(acs_2017)

In [44]:
list(acs_11)

['Id',
 'Id2',
 'Geography',
 'Total_HH',
 'HH_0Veh',
 'HH_1Veh',
 'HH_2Veh',
 'HH_3Veh',
 'HH_4+Veh']

In [54]:
acs_10['Year']=2010
acs_11['Year']=2011
acs_12['Year']=2012
acs_13['Year']=2013
acs_14['Year']=2014
acs_15['Year']=2015
acs_16['Year']=2016
acs_17['Year']=2017

In [66]:
merge_final.to_csv('../Factors and Ridership Data/Final Datasets/Veh_HH_yearly.csv')

In [67]:
merge_final

,Id,Id2,Geography,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,Year
0,3100000US10180,10180,"Abilene, TX Metro Area",60532,2175,23133,24645,7899,2680,2005
358,3100000US10180,10180,"Abilene, TX Metro Area",59850,2356,21689,25837,7647,2321,2006
717,3100000US10180,10180,"Abilene, TX Metro Area",60692,3218,20497,25691,8228,3058,2007
1078,3100000US10180,10180,"Abilene, TX Metro Area",59960,2164,22931,24732,7910,2223,2008
1439,3100000US10180,10180,"Abilene, TX Metro Area",58052,3724,20561,21354,8712,3701,2009
1805,310M100US10180,10180,"Abilene, TX Metro Area",59857,4672,18972,24464,8253,3496,2010
2171,310M100US10180,10180,"Abilene, TX Metro Area",58974,4119,21753,22514,8101,2487,2011
2537,310M100US10180,10180,"Abilene, TX Metro Area",60066,3268,21030,24744,7973,3051,2012
2903,310M200US10180,10180,"Abilene, TX Metro Area",60588,3361,22377,22363,9673,2814,2013
3284,310M200US10180,10180,"Abilene, TX Metro Area",59932,2056,22178,24905,8001,2792,2014
3665,310M200US10180,10180,"Abilene, TX Metro Area",59372,3004,20918,24663,7364,3423,2015
4046,310M300US10180,10180,"Abilene, TX Metro Area",59263,4162,20643,24437,7454,2567,2016
4428,310M300US10180,10180,"Abilene, TX Metro Area",61603,2935,20387,26759,7306,4216,2017
1,3100000US10420,10420,"Akron, OH Metro Area",276416,20661,85198,112380,40847,17330,2005
359,3100000US10420,10420,"Akron, OH Metro Area",280837,19248,97567,109326,38795,15901,2006
718,3100000US10420,10420,"Akron, OH Metro Area",281669,21066,94071,113232,36917,16383,2007
1079,3100000US10420,10420,"Akron, OH Metro Area",281731,19035,100229,108332,38548,15587,2008
1440,3100000US10420,10420,"Akron, OH Metro Area",281769,23447,97811,108215,36339,15957,2009
1806,310M100US10420,10420,"Akron, OH Metro Area",281523,22621,92537,114311,35021,17033,2010
2172,310M100US10420,10420,"Akron, OH Metro Area",274696,22332,98938,101762,35249,16415,2011
2538,310M100US10420,10420,"Akron, OH Metro Area",280887,24001,98798,110693,32826,14569,2012
2904,310M200US10420,10420,"Akron, OH Metro Area",281324,22696,97785,108261,37798,14784,2013
3285,310M200US10420,10420,"Akron, OH Metro Area",283364,23065,96377,110920,37946,15056,2014
3666,310M200US10420,10420,"Akron, OH Metro Area",282456,23662,95766,109671,35513,17844,2015
4047,310M300US10420,10420,"Akron, OH Metro Area",284670,23386,99761,106473,36824,18226,2016
4429,310M300US10420,10420,"Akron, OH Metro Area",289282,22538,96678,111274,39726,19066,2017
2,3100000US10500,10500,"Albany, GA Metro Area",59384,7093,18516,20546,9969,3260,2005
360,3100000US10500,10500,"Albany, GA Metro Area",61158,6536,20069,21296,8594,4663,2006
719,3100000US10500,10500,"Albany, GA Metro Area",60777,6970,21026,19730,8575,4476,2007
1080,3100000US10500,10500,"Albany, GA Metro Area",60893,6073,23282,18448,8971,4119,2008
...,...,...,...,...,...,...,...,...,...,...
3662,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228797,20889,82387,82541,30549,12431,2014
4043,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228692,19021,84761,80942,29705,14263,2015
4425,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228427,18240,77746,90016,29474,12951,2016
4807,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",231423,19650,80585,84501,31681,15006,2017
356,3100000US49700,49700,"Yuba City, CA Metro Area",52227,3357,14393,20791,9055,4631,2005
715,3100000US49700,49700,"Yuba City, CA Metro Area",54586,3263,14675,23173,8943,4532,2006
1076,3100000US49700,49700,"Yuba City, CA Metro Area",55450,3069,15247,20818,10470,5846,2007
1437,3100000US49700,49700,"Yuba City, CA Metro Area",56215,2834,16089,22777,10431,4084,2008
1803,3100000US49700,49700,"Yuba City, CA Metro Area",55805,3650,16914,22542,8250,4449,2009
2169,310M100US49700,49700,"Yuba City, CA Metro Area",55241,3617,15422,21761,9984,4457,2010
2535,310M100US49700,49700,"Yuba City, CA Metro Area",55418,3570,16337,23920,7997,3594,2011
2901,310M100US49700,49700,"Yuba City, CA Metro Area",56101,3513,17458,20694,9763,4673,2012
3282,310M200US49700,49700,"Yuba City, CA Metro Area",56806,4441,17103,21752,9031,4479,2013
3663,310M200US49700,49700,"Yuba City, CA Metro Area",57366,3685,16936,22494,9868,4383,2014
4044,310M200US49700,49700,"Yuba City, CA Metro Area",58262,4644,16747,20779,10317,5775,2015
4426,310M300US49700,49700,"Yuba City, CA Metro Area",59044,4283,16322,23647,9416,5376,2016
4808,310M300US49700,49700,"Yuba City, CA Metro Area",58173,4464,16032,21443,10366,5868,2017
357,3100000US49740,49740,"Yuma, AZ Metro Area",66877,4837,27992,21841,8160,4047,2005
716,3100000US49740,49740,"Yuma, AZ Metro Area",69922,3305,27133,25359,9838,4287,2006
1077,3100000US49740,49740,"Yuma, AZ Metro Area",70173,4518,27454,26309,7894,3998,2007
1438,3100000US49740,49740,"Yuma, AZ Metro Area",69370,4352,30508,23886,7480,3144,2008
1804,3100000US49740,49740,"Yuma, AZ Metro Area",71680,4098,28691,24628,9675,4588,2009
2170,310M100US49740,49740,"Yuma, AZ Metro Area",67750,3930,24325,27102,8398,3995,2010
2536,310M100US49740,49740,"Yuma, AZ Metro Area",71490,4551,25458,25084,11838,4559,2011
2902,310M100US49740,49740,"Yuma, AZ Metro Area",70895,3341,26914,27702,8550,4388,2012
3283,310M200US49740,49740,"Yuma, AZ Metro Area",69744,3823,26238,25709,9109,4865,2013
3664,310M200US49740,49740,"Yuma, AZ Metro Area",70593,4768,25179,28219,8073,4354,2014
4045,310M200US49740,49740,"Yuma, AZ Metro Area",71751,4876,29399,25679,8055,3742,2015
4427,310M300US49740,49740,"Yuma, AZ Metro Area",73072,4385,27443,25501,10557,5186,2016
4809,310M300US49740,49740,"Yuma, AZ Metro Area",74620,3785,26320,27297,12090,5128,2017

In [69]:
acs_2005_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_05_EST_S1901/ACS_05_EST_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2005_inc

,Id,Id2,Geography,Households; Estimate; Total,Households; Margin of Error; Total,Families; Estimate; Total,Families; Margin of Error; Total,Married-couple families; Estimate; Total,Married-couple families; Margin of Error; Total,Nonfamily households; Estimate; Total,...,Nonfamily households; Estimate; PERCENT IMPUTED - Family income in the past 12 months,Nonfamily households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months,Households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months,Families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months,Married-couple families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Married-couple families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months,Nonfamily households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Nonfamily households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months
0,3100000US10180,10180,"Abilene, TX Metro Area",60532,1337,41536,1897,30862,2020,18996,...,(X),(X),(X),(X),(X),(X),(X),(X),19.1,(X)
1,3100000US10420,10420,"Akron, OH Metro Area",276416,3593,180638,4689,133008,4269,95778,...,(X),(X),(X),(X),(X),(X),(X),(X),22.7,(X)
2,3100000US10500,10500,"Albany, GA Metro Area",59384,1817,42381,2296,25901,2393,17003,...,(X),(X),(X),(X),(X),(X),(X),(X),27.6,(X)
3,3100000US10580,10580,"Albany-Schenectady-Troy, NY Metro Area",337662,3587,211715,4679,157648,4595,125947,...,(X),(X),(X),(X),(X),(X),(X),(X),17.3,(X)
4,3100000US10740,10740,"Albuquerque, NM Metro Area",319677,3262,204373,4928,147467,5055,115304,...,(X),(X),(X),(X),(X),(X),(X),(X),17.3,(X)
5,3100000US10780,10780,"Alexandria, LA Metro Area",55401,1441,38402,1708,26572,1578,16999,...,(X),(X),(X),(X),(X),(X),(X),(X),21.7,(X)
6,3100000US10900,10900,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",302968,2697,207013,4272,161512,4480,95955,...,(X),(X),(X),(X),(X),(X),(X),(X),18.2,(X)
7,3100000US11020,11020,"Altoona, PA Metro Area",52145,886,33280,1532,25810,1477,18865,...,(X),(X),(X),(X),(X),(X),(X),(X),23.2,(X)
8,3100000US11100,11100,"Amarillo, TX Metro Area",88509,1496,60230,2534,43871,2265,28279,...,(X),(X),(X),(X),(X),(X),(X),(X),19.3,(X)
9,3100000US11180,11180,"Ames, IA Metro Area",31064,1109,17501,1203,N,N,13563,...,(X),(X),(X),(X),(X),(X),(X),(X),21.2,(X)
10,3100000US11260,11260,"Anchorage, AK Metro Area",124902,1457,84822,2785,62469,2972,40080,...,(X),(X),(X),(X),(X),(X),(X),(X),19.7,(X)
11,3100000US11300,11300,"Anderson, IN Metro Area",51244,1386,32589,1926,N,N,18655,...,(X),(X),(X),(X),(X),(X),(X),(X),30.1,(X)
12,3100000US11340,11340,"Anderson, SC Metro Area",68919,1895,50251,2301,37055,2475,18668,...,(X),(X),(X),(X),(X),(X),(X),(X),27.4,(X)
13,3100000US11460,11460,"Ann Arbor, MI Metro Area",131268,2123,77546,2711,60650,2895,53722,...,(X),(X),(X),(X),(X),(X),(X),(X),20.2,(X)
14,3100000US11500,11500,"Anniston-Oxford, AL Metro Area",46986,1496,30874,2142,21543,1906,16112,...,(X),(X),(X),(X),(X),(X),(X),(X),21.5,(X)
15,3100000US11540,11540,"Appleton, WI Metro Area",83180,1157,57222,1917,48480,2099,25958,...,(X),(X),(X),(X),(X),(X),(X),(X),14.9,(X)
16,3100000US11700,11700,"Asheville, NC Metro Area",167464,2882,108889,3691,86191,3728,58575,...,(X),(X),(X),(X),(X),(X),(X),(X),22.6,(X)
17,3100000US12020,12020,"Athens-Clarke County, GA Metro Area",68468,1868,39308,2123,27846,2042,29160,...,(X),(X),(X),(X),(X),(X),(X),(X),20.3,(X)
18,3100000US12060,12060,"Atlanta-Sandy Springs-Marietta, GA Metro Area",1781766,10930,1216245,11616,886483,11930,565521,...,(X),(X),(X),(X),(X),(X),(X),(X),24.7,(X)
19,3100000US12100,12100,"Atlantic City, NJ Metro Area",101584,2700,66704,2665,47452,2551,34880,...,(X),(X),(X),(X),(X),(X),(X),(X),28.8,(X)
20,3100000US12220,12220,"Auburn-Opelika, AL Metro Area",50793,1214,29168,1490,21723,1364,21625,...,(X),(X),(X),(X),(X),(X),(X),(X),17.9,(X)
21,3100000US12260,12260,"Augusta-Richmond County, GA-SC Metro Area",199470,2759,143265,3445,99122,3894,56205,...,(X),(X),(X),(X),(X),(X),(X),(X),22.6,(X)
22,3100000US12420,12420,"Austin-Round Rock, TX Metro Area",540685,3893,333506,5766,253161,6618,207179,...,(X),(X),(X),(X),(X),(X),(X),(X),20.1,(X)
23,3100000US12540,12540,"Bakersfield, CA Metro Area",231566,3346,167575,4298,117882,4288,63991,...,(X),(X),(X),(X),(X),(X),(X),(X),23.6,(X)
24,3100000US12580,12580,"Baltimore-Towson, MD Metro Area",1002709,5360,654819,8760,469075,8530,347890,...,(X),(X),(X),(X),(X),(X),(X),(X),19.6,(X)
25,3100000US12620,12620,"Bangor, ME Metro Area",60822,1196,38454,1945,31241,2090,22368,...,(X),(X),(X),(X),(X),(X),(X),(X),17.3,(X)
26,3100000US12700,12700,"Barnstable Town, MA Metro Area",100254,3152,67591,2746,52273,2984,32663,...,(X),(X),(X),(X),(X),(X),(X),(X),28.4,(X)
27,3100000US12940,12940,"Baton Rouge, LA Metro Area",273980,3780,185040,4549,126273,4899,88940,...,(X),(X),(X),(X),(X),(X),(X),(X),27.1,(X)
28,3100000US12980,12980,"Battle Creek, MI Metro Area",54821,1220,35915,1752,25884,1596,18906,...,(X),(X),(X),(X),(X),(X),(X),(X),19.8,(X)
29,3100000US13020,13020,"Bay City, MI Metro Area",45043,1175,29540,1556,N,N,15503,...,(X),(X),(X),(X),(X),(X),(X),(X),20.7,(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,3100000US46220,46220,"Tuscaloosa, AL Metro Area",79395,2382,48148,2511,32774,2253,31247,...,(X),(X),(X),(X),(X),(X),(X),(X),27.3,(X)
329,3100000US46340,46340,"Tyler, TX Metro Area",68162,1518,48152,1993,35693,2155,20010,...,(X),(X),(X),(X),(X),(X),(X),(X),25.9,(X)
330,3100000US46540,46540,"Utica-Rome, NY Metro Area",117643,2247,75321,3102,53145,2690,42322,...,(X),(X),(X),(X),(X),(X),(X),(X),21.8,(X)
331,3100000US46660,46660,"Valdosta, GA Metro Area",47763,1289,34206,1803,25401,2032,13557,...,(X),(X),(X),(X),(X),(X),(X),(X),29.2,(X)
332,3100000US46700,46700,"Vallejo-Fairfield, CA Metro Area",134624,2179,99293,3118,71267,2981,35331,...,(X),(X),(X),(X),(X),(X),(X),(X),22.7,(X)
333,3100000US46940,46940,"Vero Beach, FL Metro Area",57315,1724,39586,2206,29606,1806,17729,...,(X),(X),(X),(X),(X),(X),(X),(X),25.4,(X)
334,3100000US47020,47020,"Victoria, TX Metro Area",43031,1414,31300,1496,23147,1548,11731,...,(X),(X),(X),(X),(X),(X),(X),(X),21.7,(X)
335,3100000US47220,47220,"Vineland-Millville-Bridgeton, NJ Metro Area",49914,1213,33864,1889,22828,1866,16050,...,(X),(X),(X),(X),(X),(X),(X),(X),25.2,(X)
336,3100000US47260,47260,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",617762,4448,423185,6758,305980,6407,194577,...,(X),(X),(X),(X),(X),(X),(X),(X),23.2,(X)
337,3100000US47300,47300,"Visalia-Porterville, CA Metro Area",119621,1485,95483,2096,68134,2427,24138,...,(X),(X),(X),(X),(X),(X),(X),(X),30.3,(X)
338,3100000US47380,47380,"Waco, TX Metro Area",80546,1611,50985,2229,37327,2408,29561,...,(X),(X),(X),(X),(X),(X),(X),(X),17.7,(X)
339,3100000US47580,47580,"Warner Robins, GA Metro Area",47700,1342,33260,2044,23742,2104,14440,...,(X),(X),(X),(X),(X),(X),(X),(X),25.3,(X)
340,3100000US47900,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",1944465,6862,1267121,11215,949705,10452,677344,...,(X),(X),(X),(X),(X),(X),(X),(X),20.0,(X)
341,3100000US47940,47940,"Waterloo-Cedar Falls, IA Metro Area",65373,1016,42157,1751,33217,1740,23216,...,(X),(X),(X),(X),(X),(X),(X),(X),17.0,(X)
342,3100000US48140,48140,"Wausau, WI Metro Area",52478,901,36978,1269,31009,1248,15500,...,(X),(X),(X),(X),(X),(X),(X),(X),22.3,(X)
343,3100000US48260,48260,"Weirton-Steubenville, WV-OH Metro Area",53906,1248,36564,1628,27874,1961,17342,...,(X),(X),(X),(X),(X),(X),(X),(X),28.0,(X)
344,3100000US48300,48300,"Wenatchee, WA Metro Area",39057,1223,28053,1516,N,N,11004,...,(X),(X),(X),(X),(X),(X),(X),(X),24.1,(X)
345,3100000US48540,48540,"Wheeling, WV-OH Metro Area",62947,1433,42340,2144,33372,2058,20607,...,(X),(X),(X),(X),(X),(X),(X),(X),21.7,(X)
346,3100000US48620,48620,"Wichita, KS Metro Area",226366,3035,152692,4154,116806,3808,73674,...,(X),(X),(X),(X),(X),(X),(X),(X),15.9,(X)
347,3100000US48660,48660,"Wichita Falls, TX Metro Area",55559,1929,38037,1851,30127,2120,17522,...,(X),(X),(X),(X),(X),(X),(X),(X),17.8,(X)
348,3100000US48700,48700,"Williamsport, PA Metro Area",48270,903,32502,1504,25438,1517,15768,...,(X),(X),(X),(X),(X),(X),(X),(X),15.6,(X)
349,3100000US48900,48900,"Wilmington, NC Metro Area",138238,2595,85610,3170,66437,3066,52628,...,(X),(X),(X),(X),(X),(X),(X),(X),28.4,(X)
350,3100000US49020,49020,"Winchester, VA-WV Metro Area",43653,1447,30167,1552,N,N,13486,...,(X),(X),(X),(X),(X),(X),(X),(X),20.9,(X)
351,3100000US49180,49180,"Winston-Salem, NC Metro Area",180887,2451,124372,3985,92676,4083,56515,...,(X),(X),(X),(X),(X),(X),(X),(X),25.8,(X)
352,3100000US49340,49340,"Worcester, MA Metro Area",284040,3222,189938,4473,145768,4471,94102,...,(X),(X),(X),(X),(X),(X),(X),(X),28.0,(X)
353,3100000US49420,49420,"Yakima, WA Metro Area",76288,1245,55718,1878,40732,2125,20570,...,(X),(X),(X),(X),(X),(X),(X),(X),15.2,(X)
354,3100000US49620,49620,"York-Hanover, PA Metro Area",159432,2242,110154,3520,87588,4237,49278,...,(X),(X),(X),(X),(X),(X),(X),(X),19.3,(X)
355,3100000US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",236779,2831,159482,4176,118549,3887,77297,...,(X),(X),(X),(X),(X),(X),(X),(X),20.6,(X)
356,3100000US49700,49700,"Yuba City, CA Metro Area",52227,1231,38042,1858,28405,1945,14185,...,(X),(X),(X),(X),(X),(X),(X),(X),12.5,(X)
357,3100000US49740,49740,"Yuma, AZ Metro Area",66877,1783,47805,2135,36042,2630,19072,...,(X),(X),(X),(X),(X),(X),(X),(X),16.1,(X)

In [71]:
pd.options.display.max_columns=100

In [72]:
acs_2005_inc

,Id,Id2,Geography,Households; Estimate; Total,Households; Margin of Error; Total,Families; Estimate; Total,Families; Margin of Error; Total,Married-couple families; Estimate; Total,Married-couple families; Margin of Error; Total,Nonfamily households; Estimate; Total,Nonfamily households; Margin of Error; Total,"Households; Estimate; Total - Less than $10,000","Households; Margin of Error; Total - Less than $10,000","Families; Estimate; Total - Less than $10,000","Families; Margin of Error; Total - Less than $10,000","Married-couple families; Estimate; Total - Less than $10,000","Married-couple families; Margin of Error; Total - Less than $10,000","Nonfamily households; Estimate; Total - Less than $10,000","Nonfamily households; Margin of Error; Total - Less than $10,000","Households; Estimate; Total - $10,000 to $14,999","Households; Margin of Error; Total - $10,000 to $14,999","Families; Estimate; Total - $10,000 to $14,999","Families; Margin of Error; Total - $10,000 to $14,999","Married-couple families; Estimate; Total - $10,000 to $14,999","Married-couple families; Margin of Error; Total - $10,000 to $14,999","Nonfamily households; Estimate; Total - $10,000 to $14,999","Nonfamily households; Margin of Error; Total - $10,000 to $14,999","Households; Estimate; Total - $15,000 to $24,999","Households; Margin of Error; Total - $15,000 to $24,999","Families; Estimate; Total - $15,000 to $24,999","Families; Margin of Error; Total - $15,000 to $24,999","Married-couple families; Estimate; Total - $15,000 to $24,999","Married-couple families; Margin of Error; Total - $15,000 to $24,999","Nonfamily households; Estimate; Total - $15,000 to $24,999","Nonfamily households; Margin of Error; Total - $15,000 to $24,999","Households; Estimate; Total - $25,000 to $34,999","Households; Margin of Error; Total - $25,000 to $34,999","Families; Estimate; Total - $25,000 to $34,999","Families; Margin of Error; Total - $25,000 to $34,999","Married-couple families; Estimate; Total - $25,000 to $34,999","Married-couple families; Margin of Error; Total - $25,000 to $34,999","Nonfamily households; Estimate; Total - $25,000 to $34,999","Nonfamily households; Margin of Error; Total - $25,000 to $34,999","Households; Estimate; Total - $35,000 to $49,999","Households; Margin of Error; Total - $35,000 to $49,999","Families; Estimate; Total - $35,000 to $49,999","Families; Margin of Error; Total - $35,000 to $49,999","Married-couple families; Estimate; Total - $35,000 to $49,999","Married-couple families; Margin of Error; Total - $35,000 to $49,999","Nonfamily households; Estimate; Total - $35,000 to $49,999",...,"Nonfamily households; Estimate; Total - $150,000 to $199,999","Nonfamily households; Margin of Error; Total - $150,000 to $199,999","Households; Estimate; Total - $200,000 or more","Households; Margin of Error; Total - $200,000 or more","Families; Estimate; Total - $200,000 or more","Families; Margin of Error; Total - $200,000 or more","Married-couple families; Estimate; Total - $200,000 or more","Married-couple families; Margin of Error; Total - $200,000 or more","Nonfamily households; Estimate; Total - $200,000 or more","Nonfamily households; Margin of Error; Total - $200,000 or more",Households; Estimate; Median income (dollars),Households; Margin of Error; Median income (dollars),Families; Estimate; Median income (dollars),Families; Margin of Error; Median income (dollars),Married-couple families; Estimate; Median income (dollars),Married-couple families; Margin of Error; Median income (dollars),Nonfamily households; Estimate; Median income (dollars),Nonfamily households; Margin of Error; Median income (dollars),Households; Estimate; Mean income (dollars),Households; Margin of Error; Mean income (dollars),Families; Estimate; Mean income (dollars),Families; Margin of Error; Mean income (dollars),Married-couple families; Estimate; Mean income (dollars),Married-couple families; Margin of Error; Mean income (dollars),Nonfamily households; Estimate; Mean income (dollars),Nonfamily households; Margin of Error; Mean income (dollars),Households; Estimate; PERCENT IMPUTED - Household income in the past 12 months,Households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months,Families; Estimate; PERCENT IMPUTED - Household income in the past 12 months,Families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months,Married-couple families; Estimate; PERCENT IMPUTED - Household income in the past 12 months,Married-couple families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months,Nonfamily households; Estimate; PERCENT IMPUTED - Household income in the past 12 months,Nonfamily households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months,Households; Estimate; PERCENT IMPUTED - Family income in the past 12 months,Households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months,Families; Estimate; PERCENT IMPUTED - Family income in the past 12 months,Families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months,Married-couple families; Estimate; PERCENT IMPUTED - Family income in the past 12 months,Married-couple families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months,Nonfamily households; Estimate; PERCENT IMPUTED - Family income in the past 12 months,Nonfamily households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months,Households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months,Families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months,Married-couple families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Married-couple families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months,Nonfamily households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months,Nonfamily households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months
0,3100000US10180,10180,"Abilene, TX Metro Area",60532,1337,41536,1897,30862,2020,18996,1588,8.8,1.8,4.8,1.7,2.8,1.6,18.3,4.6,9.5,1.9,7.5,2.3,2.4,1.3,15.2,3.8,15.0,2.1,12.0,2.2,10.4,2.4,20.4,4.3,16.0,2.1,15.3,2.2,14.5,2.6,18.5,5.1,18.1,2.6,19.2,2.9,19.5,2.9,14.6,...,0.0,0.9,1.1,0.5,1.6,0.7,2.0,0.9,0.1,0.1,35535,1961,42398,2031,50237,2234,23106,3363,45619,1726,53381,2404,61167,3035,27683,2269,25.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),27.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),19.1,(X)
1,3100000US10420,10420,"Akron, OH Metro Area",276416,3593,180638,4689,133008,4269,95778,4150,8.2,0.9,5.1,1.0,1.1,0.4,15.3,2.1,6.4,0.8,3.5,0.8,1.4,0.5,11.3,1.8,11.8,1.0,7.9,1.1,4.8,0.9,20.0,2.1,12.3,1.1,11.0,1.1,8.7,1.1,15.0,2.0,16.0,1.2,15.4,1.3,14.5,1.4,17.2,...,0.9,0.5,2.1,0.4,2.9,0.5,3.7,0.7,0.6,0.3,44719,1414,57155,1944,67574,1585,26497,1286,58676,1293,69826,1828,81650,2146,36059,2012,22.9,(X),(X),(X),(X),(X),(X),(X),(X),(X),22.3,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),22.7,(X)
2,3100000US10500,10500,"Albany, GA Metro Area",59384,1817,42381,2296,25901,2393,17003,1840,12.5,2.1,9.6,2.4,0.7,0.6,22.2,5.1,9.0,2.1,4.4,1.7,1.2,0.9,20.5,5.5,10.6,2.2,9.8,2.8,6.3,2.8,12.7,4.3,10.8,2.3,11.9,2.7,10.2,2.8,8.7,3.5,16.5,2.8,16.3,3.7,15.9,4.1,17.2,...,0.0,1.0,2.3,0.9,3.1,1.2,5.1,2.0,0.0,1.0,41213,2018,47225,5428,61327,3503,18810,3999,53167,3520,61281,4820,80562,7663,28985,2954,27.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),27.3,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),27.6,(X)
3,3100000US10580,10580,"Albany-Schenectady-Troy, NY Metro Area",337662,3587,211715,4679,157648,4595,125947,4488,7.1,0.7,4.4,0.8,1.0,0.4,12.9,1.4,5.2,0.7,2.8,0.6,1.7,0.5,9.8,1.5,11.1,1.0,7.9,1.3,5.5,1.1,17.0,1.6,10.9,0.9,8.8,1.0,6.9,1.2,14.9,1.9,14.7,1.0,13.6,1.2,11.6,1.2,16.4,...,0.8,0.3,2.2,0.4,3.2,0.6,4.1,0.7,0.5,0.3,50828,1085,62442,2216,74918,1791,31754,1318,63227,1636,75147,2452,86948,2672,40798,1735,20.1,(X),(X),(X),(X),(X),(X),(X),(X),(X),21.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),17.3,(X)
4,3100000US10740,10740,"Albuquerque, NM Metro Area",319677,3262,204373,4928,147467,5055,115304,4968,8.8,0.9,5.8,0.8,2.0,0.6,16.2,1.8,6.6,0.8,3.8,0.7,2.3,0.7,11.7,1.4,13.6,1.2,10.3,1.1,6.7,1.2,19.9,2.8,11.3,1.0,10.0,1.3,8.8,1.5,14.6,1.8,16.0,1.0,17.3,1.5,15.8,1.6,14.8,...,0.7,0.4,2.2,0.4,2.4,0.4,3.2,0.5,1.1,0.5,43070,1432,53209,1653,63925,1876,26383,1601,56791,1428,65291,1790,76241,2268,37836,2386,21.3,(X),(X),(X),(X),(X),(X),(X),(X),(X),22.8,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),17.3,(X)
5,3100000US10780,10780,"Alexandria, LA Metro Area",55401,1441,38402,1708,26572,1578,16999,1773,13.6,2.6,8.5,2.1,3.5,1.3,26.7,7.0,10.1,2.3,7.8,2.2,3.9,1.5,16.6,4.9,12.1,2.2,9.5,2.3,6.9,2.1,17.0,4.6,14.6,2.5,15.6,3.1,12.1,3.4,12.4,3.8,14.9,2.1,15.6,2.6,17.4,3.2,12.6,...,0.8,1.0,2.3,0.9,2.7,0.9,3.9,1.3,1.5,1.9,34587,2877,42484,3282,54430,3614,18818,5554,50908,4113,58772,5275,72235,7289,30966,5563,23.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),24.1,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),21.7,(X)
6,3100000US10900,10900,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",302968,2697,207013,4272,161512,4480,95955,4009,5.0,0.5,3.0,0.6,1.4,0.5,10.6,1.5,5.6,0.7,2.3,0.6,1.0,0.4,13.2,1.6,11.4,1.0,8.1,0.9,5.2,0.8,19.6,2.5,11.5,1.0,10.0,1.0,8.0,1.0,15.0,2.1,14.6,1.0,13.9,1.1,12.8,1.2,15.5,...,0.8,0.4,2.7,0.4,3.5,0.6,4.4,0.7,0.7,0.4,51676,999,62379,1651,70675,1593,29511,1650,65102,1389,75859,2019,85184,2289,39204,2186,20.0,(X),(X),(X),(X),(X),(X),(X),(X),(X),20.3,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),18.2,(X)
7,3100000US11020,11020,"Altoona, PA Metro Area",52145,886,33280,1532,25810,1477,18865,1585,11.4,2.3,5.3,2.1,0.7,0.5,22.7,4.5,8.3,1.7,5.9,1.9,3.4,1.6,14.8,3.6,16.7,2.3,11.5,2.3,9.1,2.1,27.1,4.3,15.1,2.2,14.5,2.6,15.2,2.9,16.1,3.8,15.8,2.1,17.4,3.0,17.0,3.2,11.7,...,0.2,0.4,0.9,0.6,1.4,0.9,1.9,1.1,0.0,0.9,33730,2467,45987,2359,53338,2652,19988,1932,44103,2295,54752,2881,61992,3629,23321,1663,23.1,(X),(X),(X),(X),(X),(X),(X),(X),(X),22.9,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),23.2,(X)
8,3100000US11100,11100,"Amarillo, TX Metro Area",88509,1496,60230,2534,43871,2265,28279,2470,10.2,1.5,6.0,1.8,1.9,1.1,19.9,3.7,7.3,1.6,5.2,1.6,2.1,1.2,13.4,3.4,15.6,1.8,13.7,1.9,9.1,1.9,19.8,4.0,15.1,1.8,14.4,2.2,13.3,2.5,15.6,3.3,14.1,1.7,13.2,1.6,14.0,1.8,15.2,...,0.5,0.6,1.9,0.6,2.1,0.7,2.9,1.0,1.5,1.2,36603,2585,46258,4322,59071,2454,22905,2970,53327,2541,61960,3747,73931,4997,33805,3801,18.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),17.6,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),19.3,(X)
9,3100000US11180,11180,"Ames, IA Metro Area",31064,1109,17501,1203,N,N,13563,1172,11.6,2.6,3.5,1.9,N,N,22.2,4.8,5.8,1.8,3.7,2.1,N,N,9.0,3.1,16.2,2.6,8.6,3.0,N,N,26.2,5.3,9.6,2.4,9.2,3.0,N,N,9.9,3.4,15.9,2.5,15.1,3.6,N,N,16.6,...,0.9,0.9,1.9,1.4,2.0,1.3,N,N,1.7,2.5,40471,3161,62395,6089,70638,6551,21597,2390,56116,4998,74632,7096,N,N,31892,5412,16.9,(X),(X),(X),(X),(X),(X),(X),(X),(X),12.8,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),21.2,(X)
10,3100000US11260,11260,"Anchorage, AK Metro Area",124902,1457,84822,2785,62469,2972,40080,2712,5.9,1.1,3.9,1.1,1.6,0.7,11.3,2.7,4.2,0.8,2.7,0.9,1.4,0.7,8.5,2.2,8.6,1.1,6.7,1.6,3.2,1.2,14.0,2.7,7.8,1.3,6.8,1.4,4.0,1.1,11.7,2.6,14.0,1.4,13.2,1.8,12.5,2.2,15.0,...,1.8,0.9,3.1,0.6,3.7,0.9,4.8,1.2,1.3,0.8,60180,2253,70808,2631,83341,3682,40177,3671,76142,3634,85682,5255,99134,6656,50887,4421,21.8,(X),(X),(X),(X),(X),(X),(X),(X),(X),21.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),19.7,(X)
11,3100000US11300,11300,"Anderson, IN Metro Area",51244,1386,32589,1926,N,N,18655,1681,9.3,1.8,4.9,2.0,N,N,18.9,4.0,6.4,1.8,3.0,1.7,N,N,12.2,4.9,15.6,2.1,10.6,2.8,N,N,24.0,4.1,11.9,2.3,10.7,2.4,N,N,15.5,4.4,17.5,3.0,18.2,3.1,N,N,16.3,...,1.5,2.0,1.2,0.7,1.9,1.1,N,N,0.0,0.9,40050,2679,52080,2633,60390,2716,22501,2726,49414,3194,60088,4163,N,N,28599,3091,25.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),21.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),30.1,(X)
12,3100000US11340,11340,"Anderson, SC Metro Area",68919,1895,50251,2301,37055,2475,18668,2062,11.6,2.5,8.5,2.3,1.2,0.7,22.1,6.0,7.5,1.6,4.4,1.7,2.8,1.8,15.9,3.7,16.8,2.7,14.1,2.8,12.1,3.1,26.4,6.4,10.9,2.1,10.4,2.4,10.7,2.8,10.9,3.6,15.3,2.6,16.5,3.3,16.6,3.7,10.1,...,0.4,0.6,1.5,0.9,1.7,1.1,2.3,1.6,0.9,1.4,37955,2914,45256,3112,54725,3666,20468,1892,50117,2953,57413,4027,67842,5316,28363,4764,26.3,(X),(X),(X),(X),(X),(X),(X),(X),(X),25.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),27.4,(X)
13,3100000US11460,11460,"Ann Arbor, MI Metro Area",131268,2123,77546,2711,60650,2895,53722,2735,9.3,1.3,5.0,1.2,1.5,0.7,16.1,2.9,5.3,0.9,2.1,0.7,1.5,0.7,9.8,2.2,10.8,1.4,6.7,1.7,5.3,1.9,16.8,2.7,8.9,1.0,6.5,1.3,4.6,1.1,13.0,2.4,12.8,1.4,11.1,1.9,9.3,1.7,15.4,...,1.4,0.6,4.7,0.8,6.6,1.1,8.0,1.5,1.5,0.7,53495,3517,73551,4109,85517,3559,30996,2117,71798,2584,91933,3743,104180,4280,41412,2690,19.0,(X),(X),(X),(X),(X),(X),(X),(X),(X),17.8,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),20.2,(X)
14,3100000US11500,11500,"Anniston-Oxford, AL Metro Area",46986,1496,30874,2142,21543,1906,16112,1941,13.0,2.3,6.2,1.9,2.2,1.1,26.0,5.5,9.6,2.8,5.9,2.3,3.6,1.9,16.7,6.2,12.2,2.8,11.5,2.8,8.0,2.2,16.9,6.4,13.8,3.0,12.1,3.1,11.8,3.4,17.7,6.8,18.0,3.1,22.1,4.5,24.8,6.1,10.8,...,0.0,1.0,2.4,1.1,3.1,1.5,2.6,1.2,1.0,1.6,36243,3001,44912,4045,49777,3580,18928,3669,47707,3254,56557,3720,62745,4790,27958,5167,24.9,(X),(X),(X),(X),(X),(X),(X),(X),(X),26.6,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),21.5,(X)
15,3100000US11540,11540,"Appleton, WI Metro Area",83180,1157,57222,1917,48480,2099,25958,1806,4.2,0.9,2.1,0.9,0.9,0.5,9.9,2.3,3.8,1.0,2.0,1.0,0.8,0.6,8.7,2.3,10.9,1.6,7.2,1.4,5.4,1.5,20.8,4.2,10.6,1.6,8.8,1.7,7.0,1.5,15.1,3.4,15.0,2.1,12.9,2.1,10.9,2.0,18.5,...,0.8,1.2,1.5,0.5,2.0,0.7,2.3,0.8,0.1,0.2,54476,1963,64289,2749,69402,2268,31540,2438,62495,2116,71555,2687,77403,2723,40110,3185,17.6,(X),(X),(X),(X),(X),(X),(X),(X),(X),18.5,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),14.9,(X)
16,3100000US11700,11700,"Asheville, NC Metro Area",167464,2882,108889,3691,86191,3728,58575,3180,7.7,1.0,4.3,0.9,2.0,0.8,15.0,2.1,7.7,1.1,3.9,1.0,2.1,0.8,14.8,2.1,16.5,1.3,12.8,1.6,10.4,1.6,24.1,2.4,13.7,1.4,13.8,1.5,13.3,1.6,13.9,2.4,15.8,1.4,16.4,1.7,16.0,1.9,13.5,...,1.1,0.8,2.1,0.5,2.8,0.7,3.4,0.8,0.6,0.4,38275,2022,48621,2566,55361,1982,22842,1507,53455,3125,63519,4455,70781,5442,33228,2009,24.2,(X),(X),(X),(X),(X),(X),(X),(X),(X),24.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),22.6,(X)
17,3100000US12020,12020,"Athens-Clarke County, GA Metro Area",68468,1868,39308,2123,27846,2042,29160,2111,15.1,2.3,7.5,2.4,3.9,2.3,27.3,3.8,9.3,2.0,7.2,2.5,3.4,1.8,13.3,3.6,15.4,2.1,12.4,2.5,8.0,2.4,19.7,3.8,10.2,1.9,7.5,2.0,6.0,2.3,11.4,2.9,16.0,2.0,19.5,3.2,19.0,3.7,12.1,...,0.2,0.3,1.6,0.6,2.6,1.0,3.4,1.4,0.2,0.4,34950,4848,47739,2254,58623,3337,20182,2677,46211,2478,59284,3649,70942,4424,27387,2739,21.5,(X),(X),(X),(X),(X),(X),(X),(X),(X),21.0,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),20.3,(X)
18,3100000US12060,12060,"Atlanta-Sandy Springs-Marietta, GA Metro Area",1781766,10930,1216245,11616,886483,11930,565521,11025,6.6,0.3,4.7,0.3,1.6,0.2,11.7,0.7,4.4,0.3,3.2,0.3,1.3,0.2,7.5,0.6,9.3,0.3,7.6,0.4,5.0,0.4,13.6,0.8,10.8,0.5,9.6,0.5,7.2,0.4,14.6,1.0,15.1,0.5,13.6,0.6,12.2,0.7,18.1,...,1.6,0.3,4.2,0.2,5.4,0.3,7.1,0.4,1.5,0.2,54066,894,63484,1064,75943,920,36574,702,71246,899,80969,1219,95160,1333,47542,894,27.0,(X),(X),(X),(X),(X),(X),(X),(X),(X),27.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),24.7,(X)
19,3100000US12100,12100,"Atlantic City, NJ Metro Area",101584,2700,66704,2665,47452,2551,34880,2752,9.1,1.6,4.0,1.4,1.4,1.1,19.2,4.2,3.8,1.0,2.0,0.8,1.0,0.5,8.0,2.6,10.9,2.0,9.3,2.5,5.8,2.0,14.9,3.1,9.8,1.4,7.5,1.7,5.3,1.4,15.4,3.3,16.1,2.0,15.8,2.1,15.1,2.4,16.3,...,0.8,0.6,3.2,1.0,4.4,1.4,5.9,2.0,1.0,0.8,50377,2284,61240,2728,71892,4555,29822,2944,64278,2715,75764,3665,88495,4801,39348,3729,25.5,(X),(X),(X),(X),(X),(X),(X),(X),(X),23.1,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),28.8,(X)
20,3100000US12220,12220,"Auburn-Opelika, AL Metro Area",50793,1214,29168,1490,21723,1364,21625,1693,17.4,2.4,7.1,2.2,1.5,0.9,32.1,4.7,6.9,1.5,4.2,1.7,1.8,1.0,10.9,3.0,15.4,2.6,11.0,2.8,7.1,2.8,21.5,4.8,10.1,2.2,9.2,2.3,6.4,1.9,10.8,3.5,15.1,2.3,17.5,2.8,19.1,3.3,12.2,...,0.1,0.1,1.2,0.5,1.9,0.9,2.5,1.2,0.3,0.3,35203,2487,51280,4783,65643,3476,18060,1738,46718,3095,62244,4937,74745,6210,24972,2249,20.2,(X),(X),(X),(X),(X),(X),(X),(X),(X),21.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),17.9,(X)
21,3100000US12260,12260,"Augusta-Richmond County, GA-SC Metro Area",199470,2759,143265,3445,99122,3894,56205,3369,11.1,1.2,8.6,1.3,2.5,0.8,20.4,2.5,6.8,0.9,5.0,0.9,2.2,0.8,11.0,2.0,11.5,1.3,9.7,1.5,5.8,1.4,16.0,2.4,12.5,1.2,9.9,1.1,8.9,1.3,18.2,2.6,15.8,1.4,16.7,1.6,17.6,1.9,14.0,...,0.9,0.5,2.0,0.5,2.4,0.7,3.2,1.0,0.9,0.7,42276,1511,50137,2174,62341,2942,25772,1028,55404,2268,62545,2933,76137,3696,34677,2448,24.6,(X),(X),(X),(X),(X),(X),(X),(X),(X),24.8,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),22.6,(X)
22,3100000US12420,12420,"Austin-Round Rock, TX Metro Area",540685,3893,333506,5766,253161,6618,207179,5133,7.7,0.7,5.0,0.8,1.6,0.5,13.3,1.4,4.7,0.5,2.9,0.5,1.2,0.3,8.0,1.1,10.2,0.7,7.6,0.8,5.4,0.7,15.2,1.5,11.3,0.7,9.1,0.9,7.3,0.9,15.8,1.3,15.6,0.9,13.2,1.0,11.4,1.1,18.7,...,0.7,0.3,3.7,0.3,4.9,0.5,6.2,0.7,1.5,0.4,50484,1193,65739,1590,77228,1991,33381,1483,68191,1383,81672,2021,94781,2462,44258,1767,22.2,(X),(X),(X),(X),(X),(X),(X),(X),(X),22.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),20.1,(X)
23,3100000US12540,12540,"Bakersfield, CA Metro Area",231566,3346,167575,4298,117882,4288,63991,4171,8.5,1.0,7.0,1.2,2.2,0.7,16.9,2.5,8.0,0.9,6.7,1.0,3.5,0.9,13.3,2.5,15.2,1.3,13.8,1.5,10.5,1.9,19.8,2.8,12.7,1.2,11.5,1.3,11.6,1.5,13.9,3.0,15.9,1.3,15.4,1.7,15.9,1.9,15.4,...,0.3,0.3,1.8,0.6,2.2,0.8,3.1,1.2,0.4,0.3,40224,1244,45111,1935,57913,2963,25016,2780,54418,1817,60108,2225,71672,3007,35265,2530,25.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),25.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),23.6,(X)
24,3100000US12580,12580,"Baltimore-Towson, MD Metro Area",1002709,5360,654819,8760,469075,8530,347890,8151,6.8,0.4,3.9,0.4,1.2,0.3,13.1,0.9,5.0,0.4,2.7,0.4,1.0,0.2,10.0,0.9,9.3,0.5,6.6,0.5,4.0,0.4,15.3,1.2,9.2,0.4,7.7,0.5,5.3,0.5,12.7,1.0,13.4,0.6,12.1,0.7,9.5,0.7,15.8,...,1.2,0.3,4.2,0.3,5.7,0.4,7.5,0.6,1.3,0.3,57447,1023,71738,951,86355,1425,33857,1692,74007,1117,87403,1435,103098,1824,45496,1246,23.7,(X),(X),(X),(X),(X),(X),(X),(X),(X),25.0,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),19.6,(X)
25,3100000US12620,12620,"Bangor, ME Metro Area",60822,1196,38454,1945,31241,2090,22368,2068,8.8,1.7,3.2,1.1,1.5,0.8,19.2,3.6,8.1,1.5,4.7,1.4,3.2,1.3,14.2,3.2,14.6,2.0,9.6,1.8,8.0,1.7,24.0,4.1,11.7,1.9,10.6,2.2,8.2,2.0,15.3,3.3,18.1,2.2,20.5,2.7,20.0,2.6,12.0,...,0.7,0.7,1.6,0.7,2.6,1.1,3.2,1.4,0.0,0.7,40761,1688,51108,2549,56721,2240,21097,2559,50907,2717,62816,3699,69637,4305,28960,2245,17.3,(X),(X),(X),(X),(X),(X),(X),(X),(X),16.4,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),17.3,(X)
26,3100000US12700,12700,"Barnstable Town, MA Metro Area",100254,3152,67591,2746,52273,2984,32663,2784,4.6,1.3,2.2,1.2,1.0,0.7,10.3,2.9,5.3,1.4,3.0,1.5,1.2,0.7,9.5,2.6,9.0,1.3,5.4,1.5,4.1,1.2,17.0,3.2,11.2,1.2,7.8,1.5,6.1,1.4,18.1,3.1,14.5,1.7,13.2,2.1,11.1,2.1,17.8,...,1.9,1.2,3.9,0.9,5.2,1.3,6.1,1.6,0.9,0.6,54439,1921,68290,4946,74307,5226,32454,2517,69887,3716,81942,5044,91222,6168,43072,3058,25.9,(X),(X),(X),(X),(X),(X),(X),(X),(X),24.2,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),(X),28.4,(X)

In [70]:
list(acs_2005_inc)

['Id',
 'Id2',
 'Geography',
 'Households; Estimate; Total',
 'Households; Margin of Error; Total',
 'Families; Estimate; Total',
 'Families; Margin of Error; Total',
 'Married-couple families; Estimate; Total',
 'Married-couple families; Margin of Error; Total',
 'Nonfamily households; Estimate; Total',
 'Nonfamily households; Margin of Error; Total',
 'Households; Estimate; Total - Less than $10,000',
 'Households; Margin of Error; Total - Less than $10,000',
 'Families; Estimate; Total - Less than $10,000',
 'Families; Margin of Error; Total - Less than $10,000',
 'Married-couple families; Estimate; Total - Less than $10,000',
 'Married-couple families; Margin of Error; Total - Less than $10,000',
 'Nonfamily households; Estimate; Total - Less than $10,000',
 'Nonfamily households; Margin of Error; Total - Less than $10,000',
 'Households; Estimate; Total - $10,000 to $14,999',
 'Households; Margin of Error; Total - $10,000 to $14,999',
 'Families; Estimate; Total - $10,000 to $14,999',
 'Families; Margin of Error; Total - $10,000 to $14,999',
 'Married-couple families; Estimate; Total - $10,000 to $14,999',
 'Married-couple families; Margin of Error; Total - $10,000 to $14,999',
 'Nonfamily households; Estimate; Total - $10,000 to $14,999',
 'Nonfamily households; Margin of Error; Total - $10,000 to $14,999',
 'Households; Estimate; Total - $15,000 to $24,999',
 'Households; Margin of Error; Total - $15,000 to $24,999',
 'Families; Estimate; Total - $15,000 to $24,999',
 'Families; Margin of Error; Total - $15,000 to $24,999',
 'Married-couple families; Estimate; Total - $15,000 to $24,999',
 'Married-couple families; Margin of Error; Total - $15,000 to $24,999',
 'Nonfamily households; Estimate; Total - $15,000 to $24,999',
 'Nonfamily households; Margin of Error; Total - $15,000 to $24,999',
 'Households; Estimate; Total - $25,000 to $34,999',
 'Households; Margin of Error; Total - $25,000 to $34,999',
 'Families; Estimate; Total - $25,000 to $34,999',
 'Families; Margin of Error; Total - $25,000 to $34,999',
 'Married-couple families; Estimate; Total - $25,000 to $34,999',
 'Married-couple families; Margin of Error; Total - $25,000 to $34,999',
 'Nonfamily households; Estimate; Total - $25,000 to $34,999',
 'Nonfamily households; Margin of Error; Total - $25,000 to $34,999',
 'Households; Estimate; Total - $35,000 to $49,999',
 'Households; Margin of Error; Total - $35,000 to $49,999',
 'Families; Estimate; Total - $35,000 to $49,999',
 'Families; Margin of Error; Total - $35,000 to $49,999',
 'Married-couple families; Estimate; Total - $35,000 to $49,999',
 'Married-couple families; Margin of Error; Total - $35,000 to $49,999',
 'Nonfamily households; Estimate; Total - $35,000 to $49,999',
 'Nonfamily households; Margin of Error; Total - $35,000 to $49,999',
 'Households; Estimate; Total - $50,000 to $74,999',
 'Households; Margin of Error; Total - $50,000 to $74,999',
 'Families; Estimate; Total - $50,000 to $74,999',
 'Families; Margin of Error; Total - $50,000 to $74,999',
 'Married-couple families; Estimate; Total - $50,000 to $74,999',
 'Married-couple families; Margin of Error; Total - $50,000 to $74,999',
 'Nonfamily households; Estimate; Total - $50,000 to $74,999',
 'Nonfamily households; Margin of Error; Total - $50,000 to $74,999',
 'Households; Estimate; Total - $75,000 to $99,999',
 'Households; Margin of Error; Total - $75,000 to $99,999',
 'Families; Estimate; Total - $75,000 to $99,999',
 'Families; Margin of Error; Total - $75,000 to $99,999',
 'Married-couple families; Estimate; Total - $75,000 to $99,999',
 'Married-couple families; Margin of Error; Total - $75,000 to $99,999',
 'Nonfamily households; Estimate; Total - $75,000 to $99,999',
 'Nonfamily households; Margin of Error; Total - $75,000 to $99,999',
 'Households; Estimate; Total - $100,000 to $149,999',
 'Households; Margin of Error; Total - $100,000 to $149,999',
 'Families; Estimate; Total - $100,000 to $149,999',
 'Families; Margin of Error; Total - $100,000 to $149,999',
 'Married-couple families; Estimate; Total - $100,000 to $149,999',
 'Married-couple families; Margin of Error; Total - $100,000 to $149,999',
 'Nonfamily households; Estimate; Total - $100,000 to $149,999',
 'Nonfamily households; Margin of Error; Total - $100,000 to $149,999',
 'Households; Estimate; Total - $150,000 to $199,999',
 'Households; Margin of Error; Total - $150,000 to $199,999',
 'Families; Estimate; Total - $150,000 to $199,999',
 'Families; Margin of Error; Total - $150,000 to $199,999',
 'Married-couple families; Estimate; Total - $150,000 to $199,999',
 'Married-couple families; Margin of Error; Total - $150,000 to $199,999',
 'Nonfamily households; Estimate; Total - $150,000 to $199,999',
 'Nonfamily households; Margin of Error; Total - $150,000 to $199,999',
 'Households; Estimate; Total - $200,000 or more',
 'Households; Margin of Error; Total - $200,000 or more',
 'Families; Estimate; Total - $200,000 or more',
 'Families; Margin of Error; Total - $200,000 or more',
 'Married-couple families; Estimate; Total - $200,000 or more',
 'Married-couple families; Margin of Error; Total - $200,000 or more',
 'Nonfamily households; Estimate; Total - $200,000 or more',
 'Nonfamily households; Margin of Error; Total - $200,000 or more',
 'Households; Estimate; Median income (dollars)',
 'Households; Margin of Error; Median income (dollars)',
 'Families; Estimate; Median income (dollars)',
 'Families; Margin of Error; Median income (dollars)',
 'Married-couple families; Estimate; Median income (dollars)',
 'Married-couple families; Margin of Error; Median income (dollars)',
 'Nonfamily households; Estimate; Median income (dollars)',
 'Nonfamily households; Margin of Error; Median income (dollars)',
 'Households; Estimate; Mean income (dollars)',
 'Households; Margin of Error; Mean income (dollars)',
 'Families; Estimate; Mean income (dollars)',
 'Families; Margin of Error; Mean income (dollars)',
 'Married-couple families; Estimate; Mean income (dollars)',
 'Married-couple families; Margin of Error; Mean income (dollars)',
 'Nonfamily households; Estimate; Mean income (dollars)',
 'Nonfamily households; Margin of Error; Mean income (dollars)',
 'Households; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Households; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months']

In [80]:
def HH_Inc(df):
    new_df=df.filter(['Id','Id2','Geography',
                      'Households; Estimate; Total - Less than $10,000',
                      'Households; Estimate; Total - $10,000 to $14,999',
                     'Households; Estimate; Total - $15,000 to $24,999',
                     'Households; Estimate; Total - $25,000 to $34,999',
                     'Households; Estimate; Total - $35,000 to $49,999',
                     'Households; Estimate; Total - $50,000 to $74,999',
                     'Households; Estimate; Total - $75,000 to $99,999',
                     'Households; Estimate; Median income (dollars)',
                     'Households; Estimate; Mean income (dollars)',
                     ],
                      axis=1)
    
    new_df['INC_U35']=new_df['Households; Estimate; Total - Less than $10,000']+new_df['Households; Estimate; Total - $10,000 to $14,999']+new_df['Households; Estimate; Total - $15,000 to $24,999']+new_df['Households; Estimate; Total - $25,000 to $34,999']
    new_df['INC_35_100']=new_df['Households; Estimate; Total - $35,000 to $49,999']+new_df['Households; Estimate; Total - $50,000 to $74,999']+new_df['Households; Estimate; Total - $75,000 to $99,999']
    new_df['INC_100P']=100-new_df['INC_U35']-new_df['INC_35_100']
    
    new_df2=new_df.rename(index=str, columns={'Households; Estimate; Median income (dollars)':'HH_MED_INC',
                                              'Households; Estimate; Mean income (dollars)':'HH_MEAN_INC'})
    
    new_df2=new_df2.drop(columns=['Households; Estimate; Total - Less than $10,000',
                                  'Households; Estimate; Total - $10,000 to $14,999',
                                  'Households; Estimate; Total - $15,000 to $24,999',
                                  'Households; Estimate; Total - $25,000 to $34,999',
                                  'Households; Estimate; Total - $35,000 to $49,999',
                                  'Households; Estimate; Total - $50,000 to $74,999',
                                  'Households; Estimate; Total - $75,000 to $99,999'])
    return new_df2

In [81]:
HH_Inc(acs_2005_inc)

,Id,Id2,Geography,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P
0,3100000US10180,10180,"Abilene, TX Metro Area",35535,45619,49.3,42.5,8.2
1,3100000US10420,10420,"Akron, OH Metro Area",44719,58676,38.7,46.8,14.5
2,3100000US10500,10500,"Albany, GA Metro Area",41213,53167,42.9,46.4,10.7
3,3100000US10580,10580,"Albany-Schenectady-Troy, NY Metro Area",50828,63227,34.3,48.9,16.8
4,3100000US10740,10740,"Albuquerque, NM Metro Area",43070,56791,40.3,46.0,13.7
5,3100000US10780,10780,"Alexandria, LA Metro Area",34587,50908,50.4,38.4,11.2
6,3100000US10900,10900,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",51676,65102,33.5,49.7,16.8
7,3100000US11020,11020,"Altoona, PA Metro Area",33730,44103,51.5,42.3,6.2
8,3100000US11100,11100,"Amarillo, TX Metro Area",36603,53327,48.2,39.1,12.7
9,3100000US11180,11180,"Ames, IA Metro Area",40471,56116,43.2,42.5,14.3
10,3100000US11260,11260,"Anchorage, AK Metro Area",60180,76142,26.5,49.3,24.2
11,3100000US11300,11300,"Anderson, IN Metro Area",40050,49414,43.2,48.4,8.4
12,3100000US11340,11340,"Anderson, SC Metro Area",37955,50117,46.8,43.2,10.0
13,3100000US11460,11460,"Ann Arbor, MI Metro Area",53495,71798,34.3,42.7,23.0
14,3100000US11500,11500,"Anniston-Oxford, AL Metro Area",36243,47707,48.6,41.4,10.0
15,3100000US11540,11540,"Appleton, WI Metro Area",54476,62495,29.5,56.4,14.1
16,3100000US11700,11700,"Asheville, NC Metro Area",38275,53455,45.6,44.2,10.2
17,3100000US12020,12020,"Athens-Clarke County, GA Metro Area",34950,46211,50.0,40.6,9.4
18,3100000US12060,12060,"Atlanta-Sandy Springs-Marietta, GA Metro Area",54066,71246,31.1,48.6,20.3
19,3100000US12100,12100,"Atlantic City, NJ Metro Area",50377,64278,33.6,48.6,17.8
20,3100000US12220,12220,"Auburn-Opelika, AL Metro Area",35203,46718,49.8,41.1,9.1
21,3100000US12260,12260,"Augusta-Richmond County, GA-SC Metro Area",42276,55404,41.9,44.5,13.6
22,3100000US12420,12420,"Austin-Round Rock, TX Metro Area",50484,68191,33.9,46.3,19.8
23,3100000US12540,12540,"Bakersfield, CA Metro Area",40224,54418,44.4,42.2,13.4
24,3100000US12580,12580,"Baltimore-Towson, MD Metro Area",57447,74007,30.3,45.7,24.0
25,3100000US12620,12620,"Bangor, ME Metro Area",40761,50907,43.2,46.9,9.9
26,3100000US12700,12700,"Barnstable Town, MA Metro Area",54439,69887,30.1,49.9,20.0
27,3100000US12940,12940,"Baton Rouge, LA Metro Area",40904,54958,43.7,42.9,13.4
28,3100000US12980,12980,"Battle Creek, MI Metro Area",40223,50656,44.2,45.1,10.7
29,3100000US13020,13020,"Bay City, MI Metro Area",41384,51078,42.4,47.1,10.5
...,...,...,...,...,...,...,...,...
328,3100000US46220,46220,"Tuscaloosa, AL Metro Area",31708,43692,54.4,37.7,7.9
329,3100000US46340,46340,"Tyler, TX Metro Area",37964,55080,46.2,42.5,11.3
330,3100000US46540,46540,"Utica-Rome, NY Metro Area",38423,49554,45.1,45.6,9.3
331,3100000US46660,46660,"Valdosta, GA Metro Area",38429,49699,46.1,44.3,9.6
332,3100000US46700,46700,"Vallejo-Fairfield, CA Metro Area",62213,73275,26.6,49.7,23.7
333,3100000US46940,46940,"Vero Beach, FL Metro Area",45040,68450,38.9,46.9,14.2
334,3100000US47020,47020,"Victoria, TX Metro Area",36547,49732,47.5,43.1,9.4
335,3100000US47220,47220,"Vineland-Millville-Bridgeton, NJ Metro Area",46064,57576,39.7,45.9,14.4
336,3100000US47260,47260,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",51077,63492,32.5,51.1,16.4
337,3100000US47300,47300,"Visalia-Porterville, CA Metro Area",38722,51908,45.6,43.0,11.4
338,3100000US47380,47380,"Waco, TX Metro Area",36135,48365,48.2,42.6,9.2
339,3100000US47580,47580,"Warner Robins, GA Metro Area",48962,56991,35.4,50.2,14.4
340,3100000US47900,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",74708,95207,20.2,44.7,35.1
341,3100000US47940,47940,"Waterloo-Cedar Falls, IA Metro Area",41194,49579,43.3,47.9,8.8
342,3100000US48140,48140,"Wausau, WI Metro Area",49906,60031,32.9,55.3,11.8
343,3100000US48260,48260,"Weirton-Steubenville, WV-OH Metro Area",36102,45761,48.4,44.4,7.2
344,3100000US48300,48300,"Wenatchee, WA Metro Area",40302,53310,43.7,47.3,9.0
345,3100000US48540,48540,"Wheeling, WV-OH Metro Area",34032,45718,51.4,41.5,7.1
346,3100000US48620,48620,"Wichita, KS Metro Area",43259,55498,39.4,48.0,12.6
347,3100000US48660,48660,"Wichita Falls, TX Metro Area",40397,50454,42.1,49.5,8.4
348,3100000US48700,48700,"Williamsport, PA Metro Area",38562,48403,45.6,46.6,7.8
349,3100000US48900,48900,"Wilmington, NC Metro Area",41000,55388,41.6,45.6,12.8
350,3100000US49020,49020,"Winchester, VA-WV Metro Area",49736,62354,36.0,48.4,15.6
351,3100000US49180,49180,"Winston-Salem, NC Metro Area",42444,57232,40.7,47.5,11.8
352,3100000US49340,49340,"Worcester, MA Metro Area",55513,68478,31.7,46.3,22.0
353,3100000US49420,49420,"Yakima, WA Metro Area",34412,47459,50.8,42.1,7.1
354,3100000US49620,49620,"York-Hanover, PA Metro Area",48911,57665,34.7,52.7,12.6
355,3100000US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",38497,49624,45.5,44.9,9.6
356,3100000US49700,49700,"Yuba City, CA Metro Area",43885,57402,39.5,45.6,14.9
357,3100000US49740,49740,"Yuma, AZ Metro Area",35956,46071,48.4,44.0,7.6

In [75]:
acs_2006_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_06_EST_S1901/ACS_06_EST_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2007_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_07_1YR_S1901/ACS_07_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2008_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_08_1YR_S1901/ACS_08_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2009_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_09_1YR_S1901/ACS_09_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2010_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_10_1YR_S1901/ACS_10_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2011_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_11_1YR_S1901/ACS_11_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2012_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_12_1YR_S1901/ACS_12_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2013_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_13_1YR_S1901/ACS_13_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2014_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_14_1YR_S1901/ACS_14_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2015_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_15_1YR_S1901/ACS_15_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2016_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_16_1YR_S1901/ACS_16_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)
acs_2017_inc=pd.read_csv('../Factors and Ridership Data/Mean Income/ACS_Data/ACS_17_1YR_S1901/ACS_17_1YR_S1901_with_ann.csv',
                    encoding='utf-8',skiprows=1)

In [78]:
list(acs_2006_inc)

['Id',
 'Id2',
 'Geography',
 'Households; Estimate; Total',
 'Households; Margin of Error; Total',
 'Families; Estimate; Total',
 'Families; Margin of Error; Total',
 'Married-couple families; Estimate; Total',
 'Married-couple families; Margin of Error; Total',
 'Nonfamily households; Estimate; Total',
 'Nonfamily households; Margin of Error; Total',
 'Households; Estimate; Total - Less than $10,000',
 'Households; Margin of Error; Total - Less than $10,000',
 'Families; Estimate; Total - Less than $10,000',
 'Families; Margin of Error; Total - Less than $10,000',
 'Married-couple families; Estimate; Total - Less than $10,000',
 'Married-couple families; Margin of Error; Total - Less than $10,000',
 'Nonfamily households; Estimate; Total - Less than $10,000',
 'Nonfamily households; Margin of Error; Total - Less than $10,000',
 'Households; Estimate; Total - $10,000 to $14,999',
 'Households; Margin of Error; Total - $10,000 to $14,999',
 'Families; Estimate; Total - $10,000 to $14,999',
 'Families; Margin of Error; Total - $10,000 to $14,999',
 'Married-couple families; Estimate; Total - $10,000 to $14,999',
 'Married-couple families; Margin of Error; Total - $10,000 to $14,999',
 'Nonfamily households; Estimate; Total - $10,000 to $14,999',
 'Nonfamily households; Margin of Error; Total - $10,000 to $14,999',
 'Households; Estimate; Total - $15,000 to $24,999',
 'Households; Margin of Error; Total - $15,000 to $24,999',
 'Families; Estimate; Total - $15,000 to $24,999',
 'Families; Margin of Error; Total - $15,000 to $24,999',
 'Married-couple families; Estimate; Total - $15,000 to $24,999',
 'Married-couple families; Margin of Error; Total - $15,000 to $24,999',
 'Nonfamily households; Estimate; Total - $15,000 to $24,999',
 'Nonfamily households; Margin of Error; Total - $15,000 to $24,999',
 'Households; Estimate; Total - $25,000 to $34,999',
 'Households; Margin of Error; Total - $25,000 to $34,999',
 'Families; Estimate; Total - $25,000 to $34,999',
 'Families; Margin of Error; Total - $25,000 to $34,999',
 'Married-couple families; Estimate; Total - $25,000 to $34,999',
 'Married-couple families; Margin of Error; Total - $25,000 to $34,999',
 'Nonfamily households; Estimate; Total - $25,000 to $34,999',
 'Nonfamily households; Margin of Error; Total - $25,000 to $34,999',
 'Households; Estimate; Total - $35,000 to $49,999',
 'Households; Margin of Error; Total - $35,000 to $49,999',
 'Families; Estimate; Total - $35,000 to $49,999',
 'Families; Margin of Error; Total - $35,000 to $49,999',
 'Married-couple families; Estimate; Total - $35,000 to $49,999',
 'Married-couple families; Margin of Error; Total - $35,000 to $49,999',
 'Nonfamily households; Estimate; Total - $35,000 to $49,999',
 'Nonfamily households; Margin of Error; Total - $35,000 to $49,999',
 'Households; Estimate; Total - $50,000 to $74,999',
 'Households; Margin of Error; Total - $50,000 to $74,999',
 'Families; Estimate; Total - $50,000 to $74,999',
 'Families; Margin of Error; Total - $50,000 to $74,999',
 'Married-couple families; Estimate; Total - $50,000 to $74,999',
 'Married-couple families; Margin of Error; Total - $50,000 to $74,999',
 'Nonfamily households; Estimate; Total - $50,000 to $74,999',
 'Nonfamily households; Margin of Error; Total - $50,000 to $74,999',
 'Households; Estimate; Total - $75,000 to $99,999',
 'Households; Margin of Error; Total - $75,000 to $99,999',
 'Families; Estimate; Total - $75,000 to $99,999',
 'Families; Margin of Error; Total - $75,000 to $99,999',
 'Married-couple families; Estimate; Total - $75,000 to $99,999',
 'Married-couple families; Margin of Error; Total - $75,000 to $99,999',
 'Nonfamily households; Estimate; Total - $75,000 to $99,999',
 'Nonfamily households; Margin of Error; Total - $75,000 to $99,999',
 'Households; Estimate; Total - $100,000 to $149,999',
 'Households; Margin of Error; Total - $100,000 to $149,999',
 'Families; Estimate; Total - $100,000 to $149,999',
 'Families; Margin of Error; Total - $100,000 to $149,999',
 'Married-couple families; Estimate; Total - $100,000 to $149,999',
 'Married-couple families; Margin of Error; Total - $100,000 to $149,999',
 'Nonfamily households; Estimate; Total - $100,000 to $149,999',
 'Nonfamily households; Margin of Error; Total - $100,000 to $149,999',
 'Households; Estimate; Total - $150,000 to $199,999',
 'Households; Margin of Error; Total - $150,000 to $199,999',
 'Families; Estimate; Total - $150,000 to $199,999',
 'Families; Margin of Error; Total - $150,000 to $199,999',
 'Married-couple families; Estimate; Total - $150,000 to $199,999',
 'Married-couple families; Margin of Error; Total - $150,000 to $199,999',
 'Nonfamily households; Estimate; Total - $150,000 to $199,999',
 'Nonfamily households; Margin of Error; Total - $150,000 to $199,999',
 'Households; Estimate; Total - $200,000 or more',
 'Households; Margin of Error; Total - $200,000 or more',
 'Families; Estimate; Total - $200,000 or more',
 'Families; Margin of Error; Total - $200,000 or more',
 'Married-couple families; Estimate; Total - $200,000 or more',
 'Married-couple families; Margin of Error; Total - $200,000 or more',
 'Nonfamily households; Estimate; Total - $200,000 or more',
 'Nonfamily households; Margin of Error; Total - $200,000 or more',
 'Households; Estimate; Median income (dollars)',
 'Households; Margin of Error; Median income (dollars)',
 'Families; Estimate; Median income (dollars)',
 'Families; Margin of Error; Median income (dollars)',
 'Married-couple families; Estimate; Median income (dollars)',
 'Married-couple families; Margin of Error; Median income (dollars)',
 'Nonfamily households; Estimate; Median income (dollars)',
 'Nonfamily households; Margin of Error; Median income (dollars)',
 'Households; Estimate; Mean income (dollars)',
 'Households; Margin of Error; Mean income (dollars)',
 'Families; Estimate; Mean income (dollars)',
 'Families; Margin of Error; Mean income (dollars)',
 'Married-couple families; Estimate; Mean income (dollars)',
 'Married-couple families; Margin of Error; Mean income (dollars)',
 'Nonfamily households; Estimate; Mean income (dollars)',
 'Nonfamily households; Margin of Error; Mean income (dollars)',
 'Households; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Households; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months']

In [79]:
list(acs_2010_inc)

['Id',
 'Id2',
 'Geography',
 'Households; Estimate; Total',
 'Households; Margin of Error; Total',
 'Families; Estimate; Total',
 'Families; Margin of Error; Total',
 'Married-couple families; Estimate; Total',
 'Married-couple families; Margin of Error; Total',
 'Nonfamily households; Estimate; Total',
 'Nonfamily households; Margin of Error; Total',
 'Households; Estimate; Less than $10,000',
 'Households; Margin of Error; Less than $10,000',
 'Families; Estimate; Less than $10,000',
 'Families; Margin of Error; Less than $10,000',
 'Married-couple families; Estimate; Less than $10,000',
 'Married-couple families; Margin of Error; Less than $10,000',
 'Nonfamily households; Estimate; Less than $10,000',
 'Nonfamily households; Margin of Error; Less than $10,000',
 'Households; Estimate; $10,000 to $14,999',
 'Households; Margin of Error; $10,000 to $14,999',
 'Families; Estimate; $10,000 to $14,999',
 'Families; Margin of Error; $10,000 to $14,999',
 'Married-couple families; Estimate; $10,000 to $14,999',
 'Married-couple families; Margin of Error; $10,000 to $14,999',
 'Nonfamily households; Estimate; $10,000 to $14,999',
 'Nonfamily households; Margin of Error; $10,000 to $14,999',
 'Households; Estimate; $15,000 to $24,999',
 'Households; Margin of Error; $15,000 to $24,999',
 'Families; Estimate; $15,000 to $24,999',
 'Families; Margin of Error; $15,000 to $24,999',
 'Married-couple families; Estimate; $15,000 to $24,999',
 'Married-couple families; Margin of Error; $15,000 to $24,999',
 'Nonfamily households; Estimate; $15,000 to $24,999',
 'Nonfamily households; Margin of Error; $15,000 to $24,999',
 'Households; Estimate; $25,000 to $34,999',
 'Households; Margin of Error; $25,000 to $34,999',
 'Families; Estimate; $25,000 to $34,999',
 'Families; Margin of Error; $25,000 to $34,999',
 'Married-couple families; Estimate; $25,000 to $34,999',
 'Married-couple families; Margin of Error; $25,000 to $34,999',
 'Nonfamily households; Estimate; $25,000 to $34,999',
 'Nonfamily households; Margin of Error; $25,000 to $34,999',
 'Households; Estimate; $35,000 to $49,999',
 'Households; Margin of Error; $35,000 to $49,999',
 'Families; Estimate; $35,000 to $49,999',
 'Families; Margin of Error; $35,000 to $49,999',
 'Married-couple families; Estimate; $35,000 to $49,999',
 'Married-couple families; Margin of Error; $35,000 to $49,999',
 'Nonfamily households; Estimate; $35,000 to $49,999',
 'Nonfamily households; Margin of Error; $35,000 to $49,999',
 'Households; Estimate; $50,000 to $74,999',
 'Households; Margin of Error; $50,000 to $74,999',
 'Families; Estimate; $50,000 to $74,999',
 'Families; Margin of Error; $50,000 to $74,999',
 'Married-couple families; Estimate; $50,000 to $74,999',
 'Married-couple families; Margin of Error; $50,000 to $74,999',
 'Nonfamily households; Estimate; $50,000 to $74,999',
 'Nonfamily households; Margin of Error; $50,000 to $74,999',
 'Households; Estimate; $75,000 to $99,999',
 'Households; Margin of Error; $75,000 to $99,999',
 'Families; Estimate; $75,000 to $99,999',
 'Families; Margin of Error; $75,000 to $99,999',
 'Married-couple families; Estimate; $75,000 to $99,999',
 'Married-couple families; Margin of Error; $75,000 to $99,999',
 'Nonfamily households; Estimate; $75,000 to $99,999',
 'Nonfamily households; Margin of Error; $75,000 to $99,999',
 'Households; Estimate; $100,000 to $149,999',
 'Households; Margin of Error; $100,000 to $149,999',
 'Families; Estimate; $100,000 to $149,999',
 'Families; Margin of Error; $100,000 to $149,999',
 'Married-couple families; Estimate; $100,000 to $149,999',
 'Married-couple families; Margin of Error; $100,000 to $149,999',
 'Nonfamily households; Estimate; $100,000 to $149,999',
 'Nonfamily households; Margin of Error; $100,000 to $149,999',
 'Households; Estimate; $150,000 to $199,999',
 'Households; Margin of Error; $150,000 to $199,999',
 'Families; Estimate; $150,000 to $199,999',
 'Families; Margin of Error; $150,000 to $199,999',
 'Married-couple families; Estimate; $150,000 to $199,999',
 'Married-couple families; Margin of Error; $150,000 to $199,999',
 'Nonfamily households; Estimate; $150,000 to $199,999',
 'Nonfamily households; Margin of Error; $150,000 to $199,999',
 'Households; Estimate; $200,000 or more',
 'Households; Margin of Error; $200,000 or more',
 'Families; Estimate; $200,000 or more',
 'Families; Margin of Error; $200,000 or more',
 'Married-couple families; Estimate; $200,000 or more',
 'Married-couple families; Margin of Error; $200,000 or more',
 'Nonfamily households; Estimate; $200,000 or more',
 'Nonfamily households; Margin of Error; $200,000 or more',
 'Households; Estimate; Median income (dollars)',
 'Households; Margin of Error; Median income (dollars)',
 'Families; Estimate; Median income (dollars)',
 'Families; Margin of Error; Median income (dollars)',
 'Married-couple families; Estimate; Median income (dollars)',
 'Married-couple families; Margin of Error; Median income (dollars)',
 'Nonfamily households; Estimate; Median income (dollars)',
 'Nonfamily households; Margin of Error; Median income (dollars)',
 'Households; Estimate; Mean income (dollars)',
 'Households; Margin of Error; Mean income (dollars)',
 'Families; Estimate; Mean income (dollars)',
 'Families; Margin of Error; Mean income (dollars)',
 'Married-couple families; Estimate; Mean income (dollars)',
 'Married-couple families; Margin of Error; Mean income (dollars)',
 'Nonfamily households; Estimate; Mean income (dollars)',
 'Nonfamily households; Margin of Error; Mean income (dollars)',
 'Households; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Household income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Household income in the past 12 months',
 'Households; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Family income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Family income in the past 12 months',
 'Households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Married-couple families; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Married-couple families; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Nonfamily households; Estimate; PERCENT IMPUTED - Nonfamily income in the past 12 months',
 'Nonfamily households; Margin of Error; PERCENT IMPUTED - Nonfamily income in the past 12 months']

In [86]:
def HH_Inc_type2(df):
    new_df=df.filter(['Id','Id2','Geography',
                      'Households; Estimate; Less than $10,000',
                      'Households; Estimate; $10,000 to $14,999',
                     'Households; Estimate; $15,000 to $24,999',
                     'Households; Estimate; $25,000 to $34,999',
                     'Households; Estimate; $35,000 to $49,999',
                     'Households; Estimate; $50,000 to $74,999',
                     'Households; Estimate; $75,000 to $99,999',
                     'Households; Estimate; Median income (dollars)',
                     'Households; Estimate; Mean income (dollars)',
                     ],
                      axis=1)
    
    new_df['INC_U35']=new_df['Households; Estimate; Less than $10,000']+new_df['Households; Estimate; $10,000 to $14,999']+new_df['Households; Estimate; $15,000 to $24,999']+new_df['Households; Estimate; $25,000 to $34,999']
    new_df['INC_35_100']=new_df['Households; Estimate; $35,000 to $49,999']+new_df['Households; Estimate; $50,000 to $74,999']+new_df['Households; Estimate; $75,000 to $99,999']
    new_df['INC_100P']=100-new_df['INC_U35']-new_df['INC_35_100']
    
    new_df2=new_df.rename(index=str, columns={'Households; Estimate; Median income (dollars)':'HH_MED_INC',
                                              'Households; Estimate; Mean income (dollars)':'HH_MEAN_INC'})
    
    new_df2=new_df2.drop(columns=['Households; Estimate; Less than $10,000',
                                  'Households; Estimate; $10,000 to $14,999',
                                  'Households; Estimate; $15,000 to $24,999',
                                  'Households; Estimate; $25,000 to $34,999',
                                  'Households; Estimate; $35,000 to $49,999',
                                  'Households; Estimate; $50,000 to $74,999',
                                  'Households; Estimate; $75,000 to $99,999'])
    return new_df2

In [91]:
acs_05_inc=HH_Inc(acs_2005_inc)
acs_06_inc=HH_Inc(acs_2006_inc)
acs_07_inc=HH_Inc(acs_2007_inc)
acs_08_inc=HH_Inc(acs_2008_inc)
acs_09_inc=HH_Inc(acs_2009_inc)
acs_10_inc=HH_Inc_type2(acs_2010_inc)
acs_11_inc=HH_Inc_type2(acs_2011_inc)
acs_12_inc=HH_Inc_type2(acs_2012_inc)
acs_13_inc=HH_Inc_type2(acs_2013_inc)
acs_14_inc=HH_Inc_type2(acs_2014_inc)
acs_15_inc=HH_Inc_type2(acs_2015_inc)
acs_16_inc=HH_Inc_type2(acs_2016_inc)
acs_17_inc=HH_Inc_type2(acs_2017_inc)

In [92]:
acs_06_inc['Year']=2006
acs_05_inc['Year']=2005
acs_07_inc['Year']=2007
acs_08_inc['Year']=2008
acs_09_inc['Year']=2009
acs_10_inc['Year']=2010
acs_11_inc['Year']=2011
acs_12_inc['Year']=2012
acs_13_inc['Year']=2013
acs_14_inc['Year']=2014
acs_15_inc['Year']=2015
acs_16_inc['Year']=2016
acs_17_inc['Year']=2017

In [93]:
merge_1=pd.concat([acs_05_inc,acs_06_inc],ignore_index=True,sort=False)

In [94]:
merge_2=pd.concat([merge_1,acs_07_inc],ignore_index=True,sort=False)

In [95]:
merge_3=pd.concat([merge_2,acs_08_inc],ignore_index=True,sort=False)

In [96]:
merge_4=pd.concat([merge_3,acs_09_inc],ignore_index=True,sort=False)

In [97]:
merge_5=pd.concat([merge_4,acs_10_inc],ignore_index=True,sort=False)

In [98]:
merge_6=pd.concat([merge_5,acs_11_inc],ignore_index=True,sort=False)

In [99]:
merge_7=pd.concat([merge_6,acs_12_inc],ignore_index=True,sort=False)

In [100]:
merge_8=pd.concat([merge_7,acs_13_inc],ignore_index=True,sort=False)

In [101]:
merge_9=pd.concat([merge_8,acs_14_inc],ignore_index=True,sort=False)

In [102]:
merge_10=pd.concat([merge_9,acs_15_inc],ignore_index=True,sort=False)

In [103]:
merge_11=pd.concat([merge_10,acs_16_inc],ignore_index=True,sort=False)

In [104]:
merge_final=pd.concat([merge_11,acs_17_inc],ignore_index=True,sort=False)

In [107]:
merge_final_inc=merge_final.sort_values(['Geography','Year'])
merge_final_inc

,Id,Id2,Geography,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P,Year
0,3100000US10180,10180,"Abilene, TX Metro Area",35535,45619,49.3,42.5,8.2,2005
358,3100000US10180,10180,"Abilene, TX Metro Area",39784,52364,44.0,46.1,9.9,2006
717,3100000US10180,10180,"Abilene, TX Metro Area",39369,51693,44.1,46.0,9.9,2007
1078,3100000US10180,10180,"Abilene, TX Metro Area",41961,58191,39.6,48.3,12.1,2008
1439,3100000US10180,10180,"Abilene, TX Metro Area",42931,54998,41.4,46.8,11.8,2009
1805,310M100US10180,10180,"Abilene, TX Metro Area",40630,55007,41.6,45.2,13.2,2010
2171,310M100US10180,10180,"Abilene, TX Metro Area",40659,52221,44.1,44.9,11.0,2011
2537,310M100US10180,10180,"Abilene, TX Metro Area",43407,60465,41.0,45.2,13.8,2012
2903,310M200US10180,10180,"Abilene, TX Metro Area",44149,57937,40.1,45.9,14.0,2013
3284,310M200US10180,10180,"Abilene, TX Metro Area",44303,61532,38.8,46.2,15.0,2014
3665,310M200US10180,10180,"Abilene, TX Metro Area",47420,65183,37.1,45.3,17.6,2015
4046,310M300US10180,10180,"Abilene, TX Metro Area",48016,62145,35.9,47.8,16.3,2016
4428,310M300US10180,10180,"Abilene, TX Metro Area",51130,68263,34.9,42.6,22.5,2017
1,3100000US10420,10420,"Akron, OH Metro Area",44719,58676,38.7,46.8,14.5,2005
359,3100000US10420,10420,"Akron, OH Metro Area",44507,58859,38.8,47.2,14.0,2006
718,3100000US10420,10420,"Akron, OH Metro Area",47898,63454,37.2,46.1,16.7,2007
1079,3100000US10420,10420,"Akron, OH Metro Area",50036,65801,36.4,45.1,18.5,2008
1440,3100000US10420,10420,"Akron, OH Metro Area",47482,60668,36.8,48.1,15.1,2009
1806,310M100US10420,10420,"Akron, OH Metro Area",46521,60782,38.0,45.6,16.4,2010
2172,310M100US10420,10420,"Akron, OH Metro Area",47032,62438,38.4,45.1,16.5,2011
2538,310M100US10420,10420,"Akron, OH Metro Area",49731,65187,35.5,46.2,18.3,2012
2904,310M200US10420,10420,"Akron, OH Metro Area",49984,67507,35.2,45.7,19.1,2013
3285,310M200US10420,10420,"Akron, OH Metro Area",50538,67821,35.1,44.9,20.0,2014
3666,310M200US10420,10420,"Akron, OH Metro Area",51580,70288,34.5,43.2,22.3,2015
4047,310M300US10420,10420,"Akron, OH Metro Area",51598,70083,34.6,45.3,20.1,2016
4429,310M300US10420,10420,"Akron, OH Metro Area",56106,75838,31.0,46.1,22.9,2017
2,3100000US10500,10500,"Albany, GA Metro Area",41213,53167,42.9,46.4,10.7,2005
360,3100000US10500,10500,"Albany, GA Metro Area",35515,49529,49.3,38.7,12.0,2006
719,3100000US10500,10500,"Albany, GA Metro Area",36402,51200,48.5,41.4,10.1,2007
1080,3100000US10500,10500,"Albany, GA Metro Area",38989,55456,46.6,40.5,12.9,2008
...,...,...,...,...,...,...,...,...,...
3662,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",42228,55386,40.8,46.1,13.1,2014
4043,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",43127,58927,40.5,45.2,14.3,2015
4425,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",44981,60428,39.3,45.5,15.2,2016
4807,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",45382,61534,38.8,45.2,16.0,2017
356,3100000US49700,49700,"Yuba City, CA Metro Area",43885,57402,39.5,45.6,14.9,2005
715,3100000US49700,49700,"Yuba City, CA Metro Area",45287,58743,39.0,46.3,14.7,2006
1076,3100000US49700,49700,"Yuba City, CA Metro Area",47777,61585,36.5,45.9,17.6,2007
1437,3100000US49700,49700,"Yuba City, CA Metro Area",50746,62749,37.9,45.9,16.2,2008
1803,3100000US49700,49700,"Yuba City, CA Metro Area",47327,59121,38.6,47.4,14.0,2009
2169,310M100US49700,49700,"Yuba City, CA Metro Area",46314,58860,37.4,47.6,15.0,2010
2535,310M100US49700,49700,"Yuba City, CA Metro Area",46509,59409,34.5,51.1,14.4,2011
2901,310M100US49700,49700,"Yuba City, CA Metro Area",45646,61441,37.3,46.5,16.2,2012
3282,310M200US49700,49700,"Yuba City, CA Metro Area",46773,60686,38.9,45.4,15.7,2013
3663,310M200US49700,49700,"Yuba City, CA Metro Area",48115,63704,35.7,46.3,18.0,2014
4044,310M200US49700,49700,"Yuba City, CA Metro Area",51185,66463,36.1,43.1,20.8,2015
4426,310M300US49700,49700,"Yuba City, CA Metro Area",50775,68476,35.3,44.2,20.5,2016
4808,310M300US49700,49700,"Yuba City, CA Metro Area",58727,71091,28.9,48.1,23.0,2017
357,3100000US49740,49740,"Yuma, AZ Metro Area",35956,46071,48.4,44.0,7.6,2005
716,3100000US49740,49740,"Yuma, AZ Metro Area",37457,48815,46.8,44.3,8.9,2006
1077,3100000US49740,49740,"Yuma, AZ Metro Area",40733,51917,42.2,47.2,10.6,2007
1438,3100000US49740,49740,"Yuma, AZ Metro Area",38930,48924,44.8,44.9,10.3,2008
1804,3100000US49740,49740,"Yuma, AZ Metro Area",38681,49011,45.6,44.9,9.5,2009
2170,310M100US49740,49740,"Yuma, AZ Metro Area",42240,51511,41.7,47.2,11.1,2010
2536,310M100US49740,49740,"Yuma, AZ Metro Area",38390,51435,45.3,42.7,12.0,2011
2902,310M100US49740,49740,"Yuma, AZ Metro Area",39485,49642,43.7,47.0,9.3,2012
3283,310M200US49740,49740,"Yuma, AZ Metro Area",41666,55512,41.7,46.3,12.0,2013
3664,310M200US49740,49740,"Yuma, AZ Metro Area",40008,54402,44.2,44.1,11.7,2014
4045,310M200US49740,49740,"Yuma, AZ Metro Area",40539,52633,44.3,43.6,12.1,2015
4427,310M300US49740,49740,"Yuma, AZ Metro Area",43518,56872,39.4,48.7,11.9,2016
4809,310M300US49740,49740,"Yuma, AZ Metro Area",46798,60110,38.6,45.6,15.8,2017

In [127]:
merge_final_VEH

,Id,Id2,Geography,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,Year
0,3100000US10180,10180,"Abilene, TX Metro Area",60532,2175,23133,24645,7899,2680,2005
358,3100000US10180,10180,"Abilene, TX Metro Area",59850,2356,21689,25837,7647,2321,2006
717,3100000US10180,10180,"Abilene, TX Metro Area",60692,3218,20497,25691,8228,3058,2007
1078,3100000US10180,10180,"Abilene, TX Metro Area",59960,2164,22931,24732,7910,2223,2008
1439,3100000US10180,10180,"Abilene, TX Metro Area",58052,3724,20561,21354,8712,3701,2009
1805,310M100US10180,10180,"Abilene, TX Metro Area",59857,4672,18972,24464,8253,3496,2010
2171,310M100US10180,10180,"Abilene, TX Metro Area",58974,4119,21753,22514,8101,2487,2011
2537,310M100US10180,10180,"Abilene, TX Metro Area",60066,3268,21030,24744,7973,3051,2012
2903,310M200US10180,10180,"Abilene, TX Metro Area",60588,3361,22377,22363,9673,2814,2013
3284,310M200US10180,10180,"Abilene, TX Metro Area",59932,2056,22178,24905,8001,2792,2014
3665,310M200US10180,10180,"Abilene, TX Metro Area",59372,3004,20918,24663,7364,3423,2015
4046,310M300US10180,10180,"Abilene, TX Metro Area",59263,4162,20643,24437,7454,2567,2016
4428,310M300US10180,10180,"Abilene, TX Metro Area",61603,2935,20387,26759,7306,4216,2017
1,3100000US10420,10420,"Akron, OH Metro Area",276416,20661,85198,112380,40847,17330,2005
359,3100000US10420,10420,"Akron, OH Metro Area",280837,19248,97567,109326,38795,15901,2006
718,3100000US10420,10420,"Akron, OH Metro Area",281669,21066,94071,113232,36917,16383,2007
1079,3100000US10420,10420,"Akron, OH Metro Area",281731,19035,100229,108332,38548,15587,2008
1440,3100000US10420,10420,"Akron, OH Metro Area",281769,23447,97811,108215,36339,15957,2009
1806,310M100US10420,10420,"Akron, OH Metro Area",281523,22621,92537,114311,35021,17033,2010
2172,310M100US10420,10420,"Akron, OH Metro Area",274696,22332,98938,101762,35249,16415,2011
2538,310M100US10420,10420,"Akron, OH Metro Area",280887,24001,98798,110693,32826,14569,2012
2904,310M200US10420,10420,"Akron, OH Metro Area",281324,22696,97785,108261,37798,14784,2013
3285,310M200US10420,10420,"Akron, OH Metro Area",283364,23065,96377,110920,37946,15056,2014
3666,310M200US10420,10420,"Akron, OH Metro Area",282456,23662,95766,109671,35513,17844,2015
4047,310M300US10420,10420,"Akron, OH Metro Area",284670,23386,99761,106473,36824,18226,2016
4429,310M300US10420,10420,"Akron, OH Metro Area",289282,22538,96678,111274,39726,19066,2017
2,3100000US10500,10500,"Albany, GA Metro Area",59384,7093,18516,20546,9969,3260,2005
360,3100000US10500,10500,"Albany, GA Metro Area",61158,6536,20069,21296,8594,4663,2006
719,3100000US10500,10500,"Albany, GA Metro Area",60777,6970,21026,19730,8575,4476,2007
1080,3100000US10500,10500,"Albany, GA Metro Area",60893,6073,23282,18448,8971,4119,2008
...,...,...,...,...,...,...,...,...,...,...
3662,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228797,20889,82387,82541,30549,12431,2014
4043,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228692,19021,84761,80942,29705,14263,2015
4425,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228427,18240,77746,90016,29474,12951,2016
4807,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",231423,19650,80585,84501,31681,15006,2017
356,3100000US49700,49700,"Yuba City, CA Metro Area",52227,3357,14393,20791,9055,4631,2005
715,3100000US49700,49700,"Yuba City, CA Metro Area",54586,3263,14675,23173,8943,4532,2006
1076,3100000US49700,49700,"Yuba City, CA Metro Area",55450,3069,15247,20818,10470,5846,2007
1437,3100000US49700,49700,"Yuba City, CA Metro Area",56215,2834,16089,22777,10431,4084,2008
1803,3100000US49700,49700,"Yuba City, CA Metro Area",55805,3650,16914,22542,8250,4449,2009
2169,310M100US49700,49700,"Yuba City, CA Metro Area",55241,3617,15422,21761,9984,4457,2010
2535,310M100US49700,49700,"Yuba City, CA Metro Area",55418,3570,16337,23920,7997,3594,2011
2901,310M100US49700,49700,"Yuba City, CA Metro Area",56101,3513,17458,20694,9763,4673,2012
3282,310M200US49700,49700,"Yuba City, CA Metro Area",56806,4441,17103,21752,9031,4479,2013
3663,310M200US49700,49700,"Yuba City, CA Metro Area",57366,3685,16936,22494,9868,4383,2014
4044,310M200US49700,49700,"Yuba City, CA Metro Area",58262,4644,16747,20779,10317,5775,2015
4426,310M300US49700,49700,"Yuba City, CA Metro Area",59044,4283,16322,23647,9416,5376,2016
4808,310M300US49700,49700,"Yuba City, CA Metro Area",58173,4464,16032,21443,10366,5868,2017
357,3100000US49740,49740,"Yuma, AZ Metro Area",66877,4837,27992,21841,8160,4047,2005
716,3100000US49740,49740,"Yuma, AZ Metro Area",69922,3305,27133,25359,9838,4287,2006
1077,3100000US49740,49740,"Yuma, AZ Metro Area",70173,4518,27454,26309,7894,3998,2007
1438,3100000US49740,49740,"Yuma, AZ Metro Area",69370,4352,30508,23886,7480,3144,2008
1804,3100000US49740,49740,"Yuma, AZ Metro Area",71680,4098,28691,24628,9675,4588,2009
2170,310M100US49740,49740,"Yuma, AZ Metro Area",67750,3930,24325,27102,8398,3995,2010
2536,310M100US49740,49740,"Yuma, AZ Metro Area",71490,4551,25458,25084,11838,4559,2011
2902,310M100US49740,49740,"Yuma, AZ Metro Area",70895,3341,26914,27702,8550,4388,2012
3283,310M200US49740,49740,"Yuma, AZ Metro Area",69744,3823,26238,25709,9109,4865,2013
3664,310M200US49740,49740,"Yuma, AZ Metro Area",70593,4768,25179,28219,8073,4354,2014
4045,310M200US49740,49740,"Yuma, AZ Metro Area",71751,4876,29399,25679,8055,3742,2015
4427,310M300US49740,49740,"Yuma, AZ Metro Area",73072,4385,27443,25501,10557,5186,2016
4809,310M300US49740,49740,"Yuma, AZ Metro Area",74620,3785,26320,27297,12090,5128,2017

In [129]:
HH_DATA=pd.merge(merge_final_VEH,merge_final_inc,on=['Id','Id2','Geography','Year'])

In [130]:
HH_DATA.to_csv('../Factors and Ridership Data/Final Datasets/HH_DATA_yearly.csv')

In [131]:
HH_DATA

,Id,Id2,Geography,Total_HH,HH_0Veh,HH_1Veh,HH_2Veh,HH_3Veh,HH_4+Veh,Year,HH_MED_INC,HH_MEAN_INC,INC_U35,INC_35_100,INC_100P
0,3100000US10180,10180,"Abilene, TX Metro Area",60532,2175,23133,24645,7899,2680,2005,35535,45619,49.3,42.5,8.2
1,3100000US10180,10180,"Abilene, TX Metro Area",59850,2356,21689,25837,7647,2321,2006,39784,52364,44.0,46.1,9.9
2,3100000US10180,10180,"Abilene, TX Metro Area",60692,3218,20497,25691,8228,3058,2007,39369,51693,44.1,46.0,9.9
3,3100000US10180,10180,"Abilene, TX Metro Area",59960,2164,22931,24732,7910,2223,2008,41961,58191,39.6,48.3,12.1
4,3100000US10180,10180,"Abilene, TX Metro Area",58052,3724,20561,21354,8712,3701,2009,42931,54998,41.4,46.8,11.8
5,310M100US10180,10180,"Abilene, TX Metro Area",59857,4672,18972,24464,8253,3496,2010,40630,55007,41.6,45.2,13.2
6,310M100US10180,10180,"Abilene, TX Metro Area",58974,4119,21753,22514,8101,2487,2011,40659,52221,44.1,44.9,11.0
7,310M100US10180,10180,"Abilene, TX Metro Area",60066,3268,21030,24744,7973,3051,2012,43407,60465,41.0,45.2,13.8
8,310M200US10180,10180,"Abilene, TX Metro Area",60588,3361,22377,22363,9673,2814,2013,44149,57937,40.1,45.9,14.0
9,310M200US10180,10180,"Abilene, TX Metro Area",59932,2056,22178,24905,8001,2792,2014,44303,61532,38.8,46.2,15.0
10,310M200US10180,10180,"Abilene, TX Metro Area",59372,3004,20918,24663,7364,3423,2015,47420,65183,37.1,45.3,17.6
11,310M300US10180,10180,"Abilene, TX Metro Area",59263,4162,20643,24437,7454,2567,2016,48016,62145,35.9,47.8,16.3
12,310M300US10180,10180,"Abilene, TX Metro Area",61603,2935,20387,26759,7306,4216,2017,51130,68263,34.9,42.6,22.5
13,3100000US10420,10420,"Akron, OH Metro Area",276416,20661,85198,112380,40847,17330,2005,44719,58676,38.7,46.8,14.5
14,3100000US10420,10420,"Akron, OH Metro Area",280837,19248,97567,109326,38795,15901,2006,44507,58859,38.8,47.2,14.0
15,3100000US10420,10420,"Akron, OH Metro Area",281669,21066,94071,113232,36917,16383,2007,47898,63454,37.2,46.1,16.7
16,3100000US10420,10420,"Akron, OH Metro Area",281731,19035,100229,108332,38548,15587,2008,50036,65801,36.4,45.1,18.5
17,3100000US10420,10420,"Akron, OH Metro Area",281769,23447,97811,108215,36339,15957,2009,47482,60668,36.8,48.1,15.1
18,310M100US10420,10420,"Akron, OH Metro Area",281523,22621,92537,114311,35021,17033,2010,46521,60782,38.0,45.6,16.4
19,310M100US10420,10420,"Akron, OH Metro Area",274696,22332,98938,101762,35249,16415,2011,47032,62438,38.4,45.1,16.5
20,310M100US10420,10420,"Akron, OH Metro Area",280887,24001,98798,110693,32826,14569,2012,49731,65187,35.5,46.2,18.3
21,310M200US10420,10420,"Akron, OH Metro Area",281324,22696,97785,108261,37798,14784,2013,49984,67507,35.2,45.7,19.1
22,310M200US10420,10420,"Akron, OH Metro Area",283364,23065,96377,110920,37946,15056,2014,50538,67821,35.1,44.9,20.0
23,310M200US10420,10420,"Akron, OH Metro Area",282456,23662,95766,109671,35513,17844,2015,51580,70288,34.5,43.2,22.3
24,310M300US10420,10420,"Akron, OH Metro Area",284670,23386,99761,106473,36824,18226,2016,51598,70083,34.6,45.3,20.1
25,310M300US10420,10420,"Akron, OH Metro Area",289282,22538,96678,111274,39726,19066,2017,56106,75838,31.0,46.1,22.9
26,3100000US10500,10500,"Albany, GA Metro Area",59384,7093,18516,20546,9969,3260,2005,41213,53167,42.9,46.4,10.7
27,3100000US10500,10500,"Albany, GA Metro Area",61158,6536,20069,21296,8594,4663,2006,35515,49529,49.3,38.7,12.0
28,3100000US10500,10500,"Albany, GA Metro Area",60777,6970,21026,19730,8575,4476,2007,36402,51200,48.5,41.4,10.1
29,3100000US10500,10500,"Albany, GA Metro Area",60893,6073,23282,18448,8971,4119,2008,38989,55456,46.6,40.5,12.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4780,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228797,20889,82387,82541,30549,12431,2014,42228,55386,40.8,46.1,13.1
4781,310M200US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228692,19021,84761,80942,29705,14263,2015,43127,58927,40.5,45.2,14.3
4782,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",228427,18240,77746,90016,29474,12951,2016,44981,60428,39.3,45.5,15.2
4783,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",231423,19650,80585,84501,31681,15006,2017,45382,61534,38.8,45.2,16.0
4784,3100000US49700,49700,"Yuba City, CA Metro Area",52227,3357,14393,20791,9055,4631,2005,43885,57402,39.5,45.6,14.9
4785,3100000US49700,49700,"Yuba City, CA Metro Area",54586,3263,14675,23173,8943,4532,2006,45287,58743,39.0,46.3,14.7
4786,3100000US49700,49700,"Yuba City, CA Metro Area",55450,3069,15247,20818,10470,5846,2007,47777,61585,36.5,45.9,17.6
4787,3100000US49700,49700,"Yuba City, CA Metro Area",56215,2834,16089,22777,10431,4084,2008,50746,62749,37.9,45.9,16.2
4788,3100000US49700,49700,"Yuba City, CA Metro Area",55805,3650,16914,22542,8250,4449,2009,47327,59121,38.6,47.4,14.0
4789,310M100US49700,49700,"Yuba City, CA Metro Area",55241,3617,15422,21761,9984,4457,2010,46314,58860,37.4,47.6,15.0
4790,310M100US49700,49700,"Yuba City, CA Metro Area",55418,3570,16337,23920,7997,3594,2011,46509,59409,34.5,51.1,14.4
4791,310M100US49700,49700,"Yuba City, CA Metro Area",56101,3513,17458,20694,9763,4673,2012,45646,61441,37.3,46.5,16.2
4792,310M200US49700,49700,"Yuba City, CA Metro Area",56806,4441,17103,21752,9031,4479,2013,46773,60686,38.9,45.4,15.7
4793,310M200US49700,49700,"Yuba City, CA Metro Area",57366,3685,16936,22494,9868,4383,2014,48115,63704,35.7,46.3,18.0
4794,310M200US49700,49700,"Yuba City, CA Metro Area",58262,4644,16747,20779,10317,5775,2015,51185,66463,36.1,43.1,20.8
4795,310M300US49700,49700,"Yuba City, CA Metro Area",59044,4283,16322,23647,9416,5376,2016,50775,68476,35.3,44.2,20.5
4796,310M300US49700,49700,"Yuba City, CA Metro Area",58173,4464,16032,21443,10366,5868,2017,58727,71091,28.9,48.1,23.0
4797,3100000US49740,49740,"Yuma, AZ Metro Area",66877,4837,27992,21841,8160,4047,2005,35956,46071,48.4,44.0,7.6
4798,3100000US49740,49740,"Yuma, AZ Metro Area",69922,3305,27133,25359,9838,4287,2006,37457,48815,46.8,44.3,8.9
4799,3100000US49740,49740,"Yuma, AZ Metro Area",70173,4518,27454,26309,7894,3998,2007,40733,51917,42.2,47.2,10.6
4800,3100000US49740,49740,"Yuma, AZ Metro Area",69370,4352,30508,23886,7480,3144,2008,38930,48924,44.8,44.9,10.3
4801,3100000US49740,49740,"Yuma, AZ Metro Area",71680,4098,28691,24628,9675,4588,2009,38681,49011,45.6,44.9,9.5
4802,310M100US49740,49740,"Yuma, AZ Metro Area",67750,3930,24325,27102,8398,3995,2010,42240,51511,41.7,47.2,11.1
4803,310M100US49740,49740,"Yuma, AZ Metro Area",71490,4551,25458,25084,11838,4559,2011,38390,51435,45.3,42.7,12.0
4804,310M100US49740,49740,"Yuma, AZ Metro Area",70895,3341,26914,27702,8550,4388,2012,39485,49642,43.7,47.0,9.3
4805,310M200US49740,49740,"Yuma, AZ Metro Area",69744,3823,26238,25709,9109,4865,2013,41666,55512,41.7,46.3,12.0
4806,310M200US49740,49740,"Yuma, AZ Metro Area",70593,4768,25179,28219,8073,4354,2014,40008,54402,44.2,44.1,11.7
4807,310M200US49740,49740,"Yuma, AZ Metro Area",71751,4876,29399,25679,8055,3742,2015,40539,52633,44.3,43.6,12.1
4808,310M300US49740,49740,"Yuma, AZ Metro Area",73072,4385,27443,25501,10557,5186,2016,43518,56872,39.4,48.7,11.9
4809,310M300US49740,49740,"Yuma, AZ Metro Area",74620,3785,26320,27297,12090,5128,2017,46798,60110,38.6,45.6,15.8