In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()

'C:\\Users\\jho337\\Dropbox\\TCRP A-43\\Task 3 Multi City Evaluation\\Work'

In [10]:
df=pd.read_excel('../Factors and Ridership Data/Final Datasets/UZA_MSA_Conversion.xlsx', encoding='utf-8')
df
#UZA to MSA conversion

,UA,UANAME,CBSA,MNAME,MEMI,POPPT,HUPT,AREAPT,AREALANDPT,UAPOP,...,MAREA,MAREALAND,UAPOPPCT,UAHUPCT,UAAREAPCT,UAAREALANDPCT,MPOPPCT,MHUPCT,MAREAPCT,MAREALANDPCT
0,37,"Abbeville, LA Urban Cluster",10020,"Abbeville, LA Micro Area",2.0,19268,8216,28218638,27918141,19824.0,...,3.993942e+09,3.038572e+09,97.20,97.12,95.58,95.54,33.22,32.56,0.71,0.92
1,37,"Abbeville, LA Urban Cluster",35340,"New Iberia, LA Micro Area",2.0,556,244,1304730,1304730,19824.0,...,2.669056e+09,1.486940e+09,2.80,2.88,4.42,4.46,0.76,0.82,0.05,0.09
2,64,"Abbeville, SC Urban Cluster",99999,Not in a metro/micro area,NaN,5243,2578,11334983,11315197,5243.0,...,NaN,NaN,100.00,100.00,100.00,100.00,NaN,NaN,NaN,NaN
3,91,"Abbotsford, WI Urban Cluster",48140,"Wausau, WI Metro Area",1.0,1103,428,2102170,2102170,3966.0,...,4.082627e+09,4.001488e+09,27.81,26.49,39.10,39.19,0.82,0.74,0.05,0.05
4,91,"Abbotsford, WI Urban Cluster",99999,Not in a metro/micro area,NaN,2863,1188,3274492,3261271,3966.0,...,NaN,NaN,72.19,73.51,60.90,60.81,NaN,NaN,NaN,NaN
5,118,"Aberdeen, MS Urban Cluster",99999,Not in a metro/micro area,NaN,4666,2050,7469348,7416616,4666.0,...,NaN,NaN,100.00,100.00,100.00,100.00,NaN,NaN,NaN,NaN
6,145,"Aberdeen, SD Urban Cluster",10100,"Aberdeen, SD Micro Area",2.0,25977,12114,33250044,33002447,25977.0,...,7.464394e+09,7.352814e+09,100.00,100.00,100.00,100.00,63.98,64.88,0.45,0.45
7,172,"Aberdeen, WA Urban Cluster",10140,"Aberdeen, WA Micro Area",2.0,29856,13139,41927640,39997951,29856.0,...,5.761184e+09,4.926226e+09,100.00,100.00,100.00,100.00,41.01,37.36,0.73,0.81
8,199,"Aberdeen--Bel Air South--Bel Air North, MD Urb...",12580,"Baltimore-Towson, MD Metro Area",1.0,203902,79657,323630662,314194303,213751.0,...,8.041975e+09,6.737801e+09,95.39,95.15,92.61,92.51,7.52,7.04,4.02,4.66
9,199,"Aberdeen--Bel Air South--Bel Air North, MD Urb...",37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...",1.0,9849,4064,25821092,25432161,213751.0,...,1.261348e+10,1.191939e+10,4.61,4.85,7.39,7.49,0.17,0.17,0.20,0.21
10,226,"Abernathy, TX Urban Cluster",31180,"Lubbock, TX Metro Area",1.0,701,277,961817,949245,2785.0,...,4.668178e+09,4.651093e+09,25.17,24.64,31.39,31.11,0.25,0.23,0.02,0.02
11,226,"Abernathy, TX Urban Cluster",38380,"Plainview, TX Micro Area",2.0,2084,847,2101864,2101864,2785.0,...,2.602362e+09,2.602116e+09,74.83,75.36,68.61,68.89,5.75,6.26,0.08,0.08
12,253,"Abilene, KS Urban Cluster",99999,Not in a metro/micro area,NaN,7054,3238,8775140,8773263,7054.0,...,NaN,NaN,100.00,100.00,100.00,100.00,NaN,NaN,NaN,NaN
13,280,"Abilene, TX Urbanized Area",10180,"Abilene, TX Metro Area",1.0,110421,46732,142744247,141756054,110421.0,...,7.142425e+09,7.105575e+09,100.00,100.00,100.00,100.00,66.82,67.03,2.00,1.99
14,334,"Abingdon, IL Urban Cluster",23660,"Galesburg, IL Micro Area",2.0,3389,1483,3731303,3731303,3389.0,...,3.270801e+09,3.260277e+09,100.00,100.00,100.00,100.00,4.80,4.67,0.11,0.11
15,388,"Ada, OH Urban Cluster",99999,Not in a metro/micro area,NaN,5945,1906,4769036,4769036,5945.0,...,NaN,NaN,100.00,100.00,100.00,100.00,NaN,NaN,NaN,NaN
16,415,"Ada, OK Urban Cluster",10220,"Ada, OK Micro Area",2.0,17400,8086,31003046,30913906,17400.0,...,1.878324e+09,1.865918e+09,100.00,100.00,100.00,100.00,46.41,48.73,1.65,1.66
17,450,"Adams, NY Urban Cluster",48060,"Watertown-Fort Drum, NY Micro Area",2.0,2542,1100,5121210,5107296,2542.0,...,4.810181e+09,3.285632e+09,100.00,100.00,100.00,100.00,2.19,1.90,0.11,0.16
18,469,"Adel, GA Urban Cluster",99999,Not in a metro/micro area,NaN,6986,2990,15838911,15634050,6986.0,...,NaN,NaN,100.00,100.00,100.00,100.00,NaN,NaN,NaN,NaN
19,496,"Adel, IA Urban Cluster",19780,"Des Moines-West Des Moines, IA Metro Area",1.0,3170,1317,4624127,4624127,3170.0,...,7.541568e+09,7.468736e+09,100.00,100.00,100.00,100.00,0.56,0.55,0.06,0.06
20,550,"Adjuntas, PR Urban Cluster",10260,"Adjuntas, PR Micro Area",2.0,10947,4563,19974164,19817979,11122.0,...,1.737774e+08,1.727257e+08,98.43,98.40,96.98,96.95,56.19,56.16,11.49,11.47
21,550,"Adjuntas, PR Urban Cluster",38660,"Ponce, PR Metro Area",1.0,175,74,622743,622743,11122.0,...,8.748038e+08,5.456481e+08,1.57,1.60,3.02,3.05,0.07,0.07,0.07,0.11
22,577,"Adrian, MI Urban Cluster",10300,"Adrian, MI Micro Area",2.0,44823,18178,62834329,62219496,44823.0,...,1.972039e+09,1.941338e+09,100.00,100.00,100.00,100.00,44.87,41.83,3.19,3.20
23,604,"Agat, GU Urban Cluster",99999,Not in a metro/micro area,NaN,10093,3133,12597712,12594773,10093.0,...,NaN,NaN,100.00,100.00,100.00,100.00,NaN,NaN,NaN,NaN
24,631,"Aguadilla--Isabela--San Sebasti疣, PR Urbanized...",10260,"Adjuntas, PR Micro Area",2.0,54,26,184849,184849,306196.0,...,1.737774e+08,1.727257e+08,0.02,0.02,0.03,0.03,0.28,0.32,0.11,0.11
25,631,"Aguadilla--Isabela--San Sebasti疣, PR Urbanized...",10380,"Aguadilla-Isabela-San Sebasti疣, PR Metro Area",1.0,279465,127130,558261998,557617494,306196.0,...,1.283410e+09,9.284416e+08,91.27,91.84,89.95,89.98,91.24,91.56,43.50,60.06
26,631,"Aguadilla--Isabela--San Sebasti疣, PR Urbanized...",41980,"San Juan-Caguas-Guaynabo, PR Metro Area",1.0,5965,2440,17256274,17238343,306196.0,...,5.223033e+09,4.117857e+09,1.95,1.76,2.78,2.78,0.24,0.23,0.33,0.42
27,631,"Aguadilla--Isabela--San Sebasti疣, PR Urbanized...",46580,"Utuado, PR Micro Area",2.0,17593,7588,35758690,35594245,306196.0,...,2.980276e+08,2.940398e+08,5.75,5.48,5.76,5.74,53.07,53.47,12.00,12.11
28,631,"Aguadilla--Isabela--San Sebasti疣, PR Urbanized...",99999,Not in a metro/micro area,NaN,3119,1247,9156710,9081514,306196.0,...,NaN,NaN,1.02,0.90,1.48,1.47,NaN,NaN,NaN,NaN
29,658,"Ahoskie, NC Urban Cluster",99999,Not in a metro/micro area,NaN,4951,2267,7551326,7551326,4951.0,...,NaN,NaN,100.00,100.00,100.00,100.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5137,99999,Not in a 2010 urban area,48460,"West Plains, MO Micro Area",2.0,29158,12848,2383536145,2380626025,NaN,...,2.404476e+09,2.401562e+09,NaN,NaN,NaN,NaN,72.17,71.29,99.13,99.13
5138,99999,Not in a 2010 urban area,48500,"West Point, MS Micro Area",2.0,11461,5246,1060082969,1044831452,NaN,...,1.077449e+09,1.062094e+09,NaN,NaN,NaN,NaN,55.54,57.15,98.39,98.37
5139,99999,Not in a 2010 urban area,48540,"Wheeling, WV-OH Metro Area",1.0,64967,28424,2360834429,2319946104,NaN,...,2.492738e+09,2.443342e+09,NaN,NaN,NaN,NaN,43.91,40.87,94.71,94.95
5140,99999,Not in a 2010 urban area,48580,"Whitewater, WI Micro Area",2.0,34959,19117,1362970772,1312784742,NaN,...,1.493279e+09,1.437771e+09,NaN,NaN,NaN,NaN,34.20,37.10,91.27,91.31
5141,99999,Not in a 2010 urban area,48620,"Wichita, KS Metro Area",1.0,90724,35985,10182262677,10111722530,NaN,...,1.082958e+10,1.074604e+10,NaN,NaN,NaN,NaN,14.56,13.68,94.02,94.10
5142,99999,Not in a 2010 urban area,48660,"Wichita Falls, TX Metro Area",1.0,30105,12129,6765978450,6625602394,NaN,...,6.928964e+09,6.784751e+09,NaN,NaN,NaN,NaN,19.90,18.71,97.65,97.65
5143,99999,Not in a 2010 urban area,48700,"Williamsport, PA Metro Area",1.0,42121,20072,3118294248,3081696682,NaN,...,3.221518e+09,3.182045e+09,NaN,NaN,NaN,NaN,36.28,38.23,96.80,96.85
5144,99999,Not in a 2010 urban area,48740,"Willimantic, CT Micro Area",2.0,58931,24519,1226241280,1207662983,NaN,...,1.350523e+09,1.328430e+09,NaN,NaN,NaN,NaN,49.76,49.96,90.80,90.91
5145,99999,Not in a 2010 urban area,48780,"Williston, ND Micro Area",2.0,7271,3745,5544281974,5361916313,NaN,...,5.562968e+09,5.380445e+09,NaN,NaN,NaN,NaN,32.46,35.79,99.66,99.66
5146,99999,Not in a 2010 urban area,48820,"Willmar, MN Micro Area",2.0,18807,9111,2188034561,2026967510,NaN,...,2.233481e+09,2.063662e+09,NaN,NaN,NaN,NaN,44.53,46.78,97.97,98.22
5147,99999,Not in a 2010 urban area,48900,"Wilmington, NC Metro Area",1.0,86544,53199,5445933491,4419178127,NaN,...,5.984978e+09,4.942480e+09,NaN,NaN,NaN,NaN,23.89,25.87,90.99,89.41
5148,99999,Not in a 2010 urban area,48940,"Wilmington, OH Micro Area",2.0,22970,9373,1042804565,1033793384,NaN,...,1.067839e+09,1.058488e+09,NaN,NaN,NaN,NaN,54.64,51.69,97.66,97.67
5149,99999,Not in a 2010 urban area,48980,"Wilson, NC Micro Area",2.0,31406,13364,902961983,888671165,NaN,...,9.679627e+08,9.535671e+08,NaN,NaN,NaN,NaN,38.66,37.63,93.28,93.19
5150,99999,Not in a 2010 urban area,49020,"Winchester, VA-WV Metro Area",1.0,59023,28315,2673057667,2656794191,NaN,...,2.769704e+09,2.753099e+09,NaN,NaN,NaN,NaN,45.94,49.76,96.51,96.50
5151,99999,Not in a 2010 urban area,49060,"Winfield, KS Micro Area",2.0,11256,5039,2892764062,2875610755,NaN,...,2.932971e+09,2.915680e+09,NaN,NaN,NaN,NaN,31.00,31.43,98.63,98.63
5152,99999,Not in a 2010 urban area,49100,"Winona, MN Micro Area",2.0,17772,6978,1623004240,1585274633,NaN,...,1.661690e+09,1.621865e+09,NaN,NaN,NaN,NaN,34.53,33.61,97.67,97.74
5153,99999,Not in a 2010 urban area,49180,"Winston-Salem, NC Metro Area",1.0,123151,55717,3098490596,3061164677,NaN,...,3.814845e+09,3.770865e+09,NaN,NaN,NaN,NaN,25.78,25.99,81.22,81.18
5154,99999,Not in a 2010 urban area,49260,"Woodward, OK Micro Area",2.0,8737,3434,3205662907,3196075922,NaN,...,3.227492e+09,3.217798e+09,NaN,NaN,NaN,NaN,43.51,38.85,99.32,99.32
5155,99999,Not in a 2010 urban area,49300,"Wooster, OH Micro Area",2.0,58406,21060,1344712811,1340249501,NaN,...,1.442148e+09,1.437258e+09,NaN,NaN,NaN,NaN,51.00,45.94,93.24,93.25
5156,99999,Not in a 2010 urban area,49340,"Worcester, MA Metro Area",1.0,146856,56607,2988167723,2857390876,NaN,...,4.090094e+09,3.912877e+09,NaN,NaN,NaN,NaN,18.39,17.32,73.06,73.03
5157,99999,Not in a 2010 urban area,49380,"Worthington, MN Micro Area",2.0,8762,3874,1854833570,1838686228,NaN,...,1.871415e+09,1.852117e+09,NaN,NaN,NaN,NaN,40.99,45.39,99.11,99.27
5158,99999,Not in a 2010 urban area,49420,"Yakima, WA Metro Area",1.0,57206,20303,10947041994,10906519936,NaN,...,1.116615e+10,1.112502e+10,NaN,NaN,NaN,NaN,23.52,23.75,98.04,98.04
5159,99999,Not in a 2010 urban area,49460,"Yankton, SD Micro Area",2.0,7801,3342,1364186978,1335557716,NaN,...,1.378437e+09,1.349807e+09,NaN,NaN,NaN,NaN,34.77,34.62,98.97,98.94
5160,99999,Not in a 2010 urban area,49500,"Yauco, PR Metro Area",1.0,16515,7439,600104749,371638935,NaN,...,7.262148e+08,4.976135e+08,NaN,NaN,NaN,NaN,15.39,16.30,82.63,74.68
5161,99999,Not in a 2010 urban area,49540,"Yazoo City, MS Micro Area",2.0,12519,5519,2397351800,2368200872,NaN,...,2.419738e+09,2.390421e+09,NaN,NaN,NaN,NaN,44.61,54.78,99.07,99.07
5162,99999,Not in a 2010 urban area,49620,"York-Hanover, PA Metro Area",1.0,107527,43500,1830327418,1814797612,NaN,...,2.358761e+09,2.341819e+09,NaN,NaN,NaN,NaN,24.72,24.35,77.60,77.50
5163,99999,Not in a 2010 urban area,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",1.0,145452,62123,3831968245,3728411975,NaN,...,4.518127e+09,4.409440e+09,NaN,NaN,NaN,NaN,25.71,23.92,84.81,84.56
5164,99999,Not in a 2010 urban area,49700,"Yuba City, CA Metro Area",1.0,32940,13842,3130955934,3085188247,NaN,...,3.243435e+09,3.196690e+09,NaN,NaN,NaN,NaN,19.74,22.51,96.53,96.51
5165,99999,Not in a 2010 urban area,49740,"Yuma, AZ Metro Area",1.0,20416,9315,14116006923,14103190623,NaN,...,1.429443e+10,1.428117e+10,NaN,NaN,NaN,NaN,10.43,10.60,98.75,98.75
5166,99999,Not in a 2010 urban area,49780,"Zanesville, OH Micro Area",2.0,40483,17105,1663126039,1643984189,NaN,...,1.741982e+09,1.721251e+09,NaN,NaN,NaN,NaN,47.03,44.93,95.47,95.51

In [16]:
df=df.sort_values(by=['UAPOPPCT','UANAME','MNAME'],ascending=False)

In [22]:
sorted_df=df.drop_duplicates('UANAME')
#taking the rows with highest UAPOPPCT for each UANAME

In [29]:
sorted_df=sorted_df[sorted_df['MNAME']!='Not in a metro/micro area']

In [36]:
sorted_df=sorted_df.iloc[:,[0,1,2,3,9,13]]

In [37]:
sorted_df['metro_micro']=sorted_df['MNAME'].apply(lambda x: "Micro Area" in x)

In [41]:
sorted_df=sorted_df[sorted_df['metro_micro']==False]

In [42]:
sorted_df.to_csv('../Factors and Ridership Data/Final Datasets/UZA_Conversion.csv')

In [43]:
df=pd.read_csv('../Factors and Ridership Data/Employment/lma_code.csv', encoding='utf-8')
df

,record,lma_code,lma_fips,lma_title
0,1,MC0110700000000,10700,"Albertville, AL Micropolitan Statistical Area"
1,2,MC0110760000000,10760,"Alexander City, AL Micropolitan Statistical Area"
2,3,MT0111500000000,11500,"Anniston-Oxford-Jacksonville, AL Metropolitan ..."
3,4,MC0112120000000,12120,"Atmore, AL Micropolitan Statistical Area"
4,5,MT0112220000000,12220,"Auburn-Opelika, AL Metropolitan Statistical Area"
5,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical..."
6,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical..."
7,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical..."
8,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical..."
9,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical..."
10,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical..."
11,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical..."
12,13,CN0101100000000,11,"Bullock County, AL"
13,14,CN0101300000000,13,"Butler County, AL"
14,15,CN0101900000000,19,"Cherokee County, AL"
15,16,CN0102300000000,23,"Choctaw County, AL"
16,17,CN0102500000000,25,"Clarke County, AL"
17,18,CN0102700000000,27,"Clay County, AL"
18,19,CN0102900000000,29,"Cleburne County, AL"
19,20,MT1317980000000,17980,"Columbus, GA-AL Metropolitan Statistical Area"
20,21,CN0103500000000,35,"Conecuh County, AL"
21,22,CN0103900000000,39,"Covington County, AL"
22,23,CN0104100000000,41,"Crenshaw County, AL"
23,24,MC0118980000000,18980,"Cullman, AL Micropolitan Statistical Area"
24,25,MT0119300000000,19300,"Daphne-Fairhope-Foley, AL Metropolitan Statist..."
25,26,MT0119460000000,19460,"Decatur, AL Metropolitan Statistical Area"
26,27,MT0119460000000,19460,"Decatur, AL Metropolitan Statistical Area"
27,28,MT0120020000000,20020,"Dothan, AL Metropolitan Statistical Area"
28,29,MT0120020000000,20020,"Dothan, AL Metropolitan Statistical Area"
29,30,MT0120020000000,20020,"Dothan, AL Metropolitan Statistical Area"
...,...,...,...,...
4713,4714,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4714,4715,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4715,4716,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4716,4717,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4717,4718,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4718,4719,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4719,4720,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4720,4721,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4721,4722,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4722,4723,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4723,4724,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4724,4725,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4725,4726,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4726,4727,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4727,4728,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4728,4729,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4729,4730,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4730,4731,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4731,4732,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4732,4733,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4733,4734,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4734,4735,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4735,4736,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4736,4737,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4737,4738,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4738,4739,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4739,4740,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4740,4741,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat..."
4741,4742,MC7242180000000,42180,"Santa Isabel, PR Micropolitan Statistical Area"
4742,4743,CN7214700000000,147,"Vieques Municipio, PR"

In [44]:
df['two_digit']=df['lma_code'].apply(lambda x: x[0:2])

In [46]:
df=df[df['two_digit']=='MT']

In [61]:
df

,record,lma_code,lma_fips,lma_title,two_digit
2,3,MT0111500000000,11500,"Anniston-Oxford-Jacksonville, AL Metropolitan ...",MT
4,5,MT0112220000000,12220,"Auburn-Opelika, AL Metropolitan Statistical Area",MT
5,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT
6,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT
7,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT
8,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT
9,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT
10,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT
11,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT
19,20,MT1317980000000,17980,"Columbus, GA-AL Metropolitan Statistical Area",MT
24,25,MT0119300000000,19300,"Daphne-Fairhope-Foley, AL Metropolitan Statist...",MT
25,26,MT0119460000000,19460,"Decatur, AL Metropolitan Statistical Area",MT
26,27,MT0119460000000,19460,"Decatur, AL Metropolitan Statistical Area",MT
27,28,MT0120020000000,20020,"Dothan, AL Metropolitan Statistical Area",MT
28,29,MT0120020000000,20020,"Dothan, AL Metropolitan Statistical Area",MT
29,30,MT0120020000000,20020,"Dothan, AL Metropolitan Statistical Area",MT
33,34,MT0122520000000,22520,"Florence-Muscle Shoals, AL Metropolitan Statis...",MT
34,35,MT0122520000000,22520,"Florence-Muscle Shoals, AL Metropolitan Statis...",MT
37,38,MT0123460000000,23460,"Gadsden, AL Metropolitan Statistical Area",MT
39,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT
40,41,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT
45,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT
47,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT
48,49,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT
49,50,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT
50,51,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT
60,61,MT0146220000000,46220,"Tuscaloosa, AL Metropolitan Statistical Area",MT
61,62,MT0146220000000,46220,"Tuscaloosa, AL Metropolitan Statistical Area",MT
62,63,MT0146220000000,46220,"Tuscaloosa, AL Metropolitan Statistical Area",MT
69,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT
...,...,...,...,...,...
4711,4712,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4712,4713,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4713,4714,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4714,4715,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4715,4716,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4716,4717,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4717,4718,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4718,4719,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4719,4720,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4720,4721,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4721,4722,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4722,4723,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4723,4724,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4724,4725,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4725,4726,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4726,4727,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4727,4728,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4728,4729,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4729,4730,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4730,4731,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4731,4732,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4732,4733,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4733,4734,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4734,4735,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4735,4736,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4736,4737,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4737,4738,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4738,4739,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4739,4740,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT
4740,4741,MT7241980000000,41980,"San Juan-Carolina-Caguas, PR Metropolitan Stat...",MT

In [62]:
df['Area_Code']=df['lma_code'].apply(lambda x: 'LAU'+x)

C:\Users\jho337\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [64]:
df.to_csv('Area_Code.csv')

In [66]:
x="LAUMT021126000000003"
len(x[:-2])

18

In [50]:
len("LAU"+"MT0111500000000"+'03')

20

In [57]:
employment=pd.read_csv('../Factors and Ridership Data/Employment/employment.csv', encoding='utf-8')
employment

,Series ID,Data Type,Jan 2002,Feb 2002,Mar 2002,Apr 2002,May 2002,Jun 2002,Jul 2002,Aug 2002,...,Mar 2019,Apr 2019,May 2019,Jun 2019,Jul 2019,Aug 2019,Sep 2019,Oct 2019,Nov 2019,Dec 2019
0,LAUMT021126000000003,Unemployment Rate,6.3,6.7,6.7,6.5,6.2,6.4,6.0,5.8,...,6.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LAUMT021126000000004,Unemployment,11059.0,11606.0,11669.0,11222.0,10727.0,11454.0,10497.0,10008.0,...,12457.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LAUMT021126000000005,Employment,164075.0,162486.0,162329.0,161677.0,162537.0,166256.0,163164.0,162352.0,...,183879.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LAUMT021126000000006,Total Labor Force,175134.0,174092.0,173998.0,172899.0,173264.0,177710.0,173661.0,172360.0,...,196336.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LAUMT011382000000003,Unemployment Rate,5.2,5.4,5.1,4.5,4.4,5.4,5.2,5.4,...,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,LAUMT011382000000004,Unemployment,27274.0,28075.0,26660.0,23184.0,22945.0,28159.0,27154.0,28192.0,...,18875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,LAUMT011382000000005,Employment,494684.0,496008.0,497251.0,496340.0,496893.0,496239.0,497292.0,496204.0,...,535594.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,523911.0,519524.0,519838.0,524398.0,524446.0,524396.0,...,554469.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,LAUMT012662000000003,Unemployment Rate,5.2,5.1,4.9,4.1,4.0,4.9,5.5,4.8,...,3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,LAUMT012662000000004,Unemployment,9275.0,9182.0,8879.0,7460.0,7289.0,9072.0,10047.0,8906.0,...,7434.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,LAUMT012662000000005,Employment,170800.0,171510.0,172107.0,173275.0,173521.0,174202.0,173173.0,175288.0,...,219105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,LAUMT012662000000006,Total Labor Force,180075.0,180692.0,180986.0,180735.0,180810.0,183274.0,183220.0,184194.0,...,226539.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,LAUMT013366000000003,Unemployment Rate,7.2,6.9,6.5,5.7,5.7,6.8,6.7,6.9,...,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,LAUMT013366000000004,Unemployment,12858.0,12424.0,11701.0,10363.0,10330.0,12507.0,12212.0,12622.0,...,8619.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,LAUMT013366000000005,Employment,166757.0,168202.0,169707.0,170013.0,170352.0,170906.0,170251.0,169757.0,...,181170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,LAUMT013366000000006,Total Labor Force,179615.0,180626.0,181408.0,180376.0,180682.0,183413.0,182463.0,182379.0,...,189789.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,LAUMT013386000000003,Unemployment Rate,5.5,5.5,5.2,4.5,4.6,5.7,5.4,5.6,...,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LAUMT013386000000004,Unemployment,8817.0,8900.0,8409.0,7193.0,7373.0,9161.0,8866.0,9169.0,...,6444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,LAUMT013386000000005,Employment,152734.0,153151.0,153160.0,153450.0,153288.0,152850.0,154155.0,154166.0,...,167730.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,LAUMT013386000000006,Total Labor Force,161551.0,162051.0,161569.0,160643.0,160661.0,162011.0,163021.0,163335.0,...,174174.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,LAUMT053078000000003,Unemployment Rate,5.4,5.3,5.0,4.9,4.9,5.2,5.3,4.7,...,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,LAUMT053078000000004,Unemployment,16379.0,16371.0,15647.0,15230.0,15287.0,16610.0,16795.0,14887.0,...,11059.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,LAUMT053078000000005,Employment,286984.0,293072.0,294541.0,296662.0,297315.0,302157.0,302051.0,298937.0,...,345459.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,LAUMT053078000000006,Total Labor Force,303363.0,309443.0,310188.0,311892.0,312602.0,318767.0,318846.0,313824.0,...,356518.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,LAUMT042238000000003,Unemployment Rate,6.0,5.6,5.7,5.1,4.7,5.9,5.9,5.7,...,5.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,LAUMT042238000000004,Unemployment,3838.0,3591.0,3634.0,3343.0,3112.0,4025.0,4106.0,3759.0,...,4369.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,LAUMT042238000000005,Employment,59659.0,60345.0,60264.0,61778.0,62480.0,64566.0,65169.0,62536.0,...,72397.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,LAUMT042238000000006,Total Labor Force,63497.0,63936.0,63898.0,65121.0,65592.0,68591.0,69275.0,66295.0,...,76766.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,LAUMT061254000000003,Unemployment Rate,10.7,11.0,11.6,10.2,8.7,9.4,9.2,8.4,...,10.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,LAUMT061254000000004,Unemployment,31924.0,32697.0,34629.0,30943.0,26520.0,29204.0,28506.0,26113.0,...,39268.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,LAUMT174042000000005,Employment,150153.0,151390.0,151303.0,151163.0,152188.0,153374.0,152276.0,152019.0,...,156704.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
635,LAUMT174042000000006,Total Labor Force,162930.0,164146.0,163457.0,162183.0,162544.0,164888.0,163941.0,163460.0,...,167802.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
636,LAUMT174410000000003,Unemployment Rate,4.9,4.7,4.5,4.1,4.1,4.8,4.8,4.6,...,5.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
637,LAUMT174410000000004,Unemployment,5378.0,5234.0,4940.0,4508.0,4528.0,5438.0,5431.0,5221.0,...,5606.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,LAUMT174410000000005,Employment,105079.0,105794.0,105961.0,106340.0,106882.0,107436.0,106778.0,108939.0,...,104973.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,LAUMT174410000000006,Total Labor Force,110457.0,111028.0,110901.0,110848.0,111410.0,112874.0,112209.0,114160.0,...,110579.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,LAUMT161426000000003,Unemployment Rate,6.1,6.0,5.8,5.4,4.6,4.9,4.8,4.8,...,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,LAUMT161426000000004,Unemployment,15992.0,15900.0,15133.0,13962.0,12071.0,12953.0,12696.0,12493.0,...,10918.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,LAUMT161426000000005,Employment,245580.0,247504.0,248041.0,246591.0,249615.0,251204.0,252326.0,249914.0,...,359395.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
643,LAUMT161426000000006,Total Labor Force,261572.0,263404.0,263174.0,260553.0,261686.0,264157.0,265022.0,262407.0,...,370313.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644,LAUMT191118000000003,Unemployment Rate,2.7,2.5,2.6,2.4,2.2,2.9,2.8,2.7,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,LAUMT191118000000004,Unemployment,1251.0,1227.0,1257.0,1183.0,1084.0,1367.0,1266.0,1250.0,...,892.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,LAUMT191118000000005,Employment,45248.0,46920.0,47260.0,47485.0,47870.0,46197.0,44594.0,45030.0,...,59565.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,LAUMT191118000000006,Total Labor Force,46499.0,48147.0,48517.0,48668.0,48954.0,47564.0,45860.0,46280.0,...,60457.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
648,LAUMT191630000000003,Unemployment Rate,5.0,4.9,4.8,4.3,3.9,4.3,4.1,4.8,...,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,LAUMT191630000000004,Unemployment,6917.0,6824.0,6703.0,6155.0,5537.0,6157.0,5817.0,6709.0,...,4217.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,LAUMT191630000000005,Employment,131607.0,133503.0,134296.0,135694.0,135676.0,136026.0,135102.0,133527.0,...,140703.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,LAUMT191630000000006,Total Labor Force,138524.0,140327.0,140999.0,141849.0,141213.0,142183.0,140919.0,140236.0,...,144920.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,LAUMT191978000000003,Unemployment Rate,4.1,4.0,4.0,3.5,3.1,3.6,3.4,3.4,...,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
653,LAUMT191978000000004,Unemployment,11575.0,11473.0,11489.0,10144.0,9170.0,10774.0,9979.0,10008.0,...,10044.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,LAUMT191978000000005,Employment,270878.0,274572.0,276368.0,280244.0,283308.0,287048.0,287401.0,284793.0,...,352279.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
655,LAUMT191978000000006,Total Labor Force,282453.0,286045.0,287857.0,290388.0,292478.0,297822.0,297380.0,294801.0,...,362323.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656,LAUMT192698000000003,Unemployment Rate,3.2,3.0,2.9,2.7,2.5,3.1,2.9,2.9,...,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
657,LAUMT192698000000004,Unemployment,2597.0,2490.0,2480.0,2338.0,2120.0,2567.0,2401.0,2459.0,...,1844.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,LAUMT192698000000005,Employment,79482.0,81297.0,82121.0,82751.0,82827.0,81220.0,81658.0,81297.0,...,96830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,LAUMT192698000000006,Total Labor Force,82079.0,83787.0,84601.0,85089.0,84947.0,83787.0,84059.0,83756.0,...,98674.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,LAUMT171934000000003,Unemployment Rate,6.4,5.8,5.7,5.0,4.7,5.0,4.8,4.8,...,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
661,LAUMT171934000000004,Unemployment,12383.0,11278.0,11148.0,9822.0,9270.0,10057.0,9556.0,9470.0,...,9489.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662,LAUMT171934000000005,Employment,181275.0,183811.0,185426.0,186679.0,188385.0,191263.0,189999.0,188194.0,...,184247.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
663,LAUMT171934000000006,Total Labor Force,193658.0,195089.0,196574.0,196501.0,197655.0,201320.0,199555.0,197664.0,...,193736.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
employment=employment.dropna(axis=1)

In [59]:
employment

,Series ID,Data Type,Jan 2002,Feb 2002,Mar 2002,Apr 2002,May 2002,Jun 2002,Jul 2002,Aug 2002,...,Jun 2018,Jul 2018,Aug 2018,Sep 2018,Oct 2018,Nov 2018,Dec 2018,Jan 2019,Feb 2019,Mar 2019
0,LAUMT021126000000003,Unemployment Rate,6.3,6.7,6.7,6.5,6.2,6.4,6.0,5.8,...,6.2,5.7,5.4,5.6,5.6,5.6,5.6,6.3,6.5,6.3
1,LAUMT021126000000004,Unemployment,11059.0,11606.0,11669.0,11222.0,10727.0,11454.0,10497.0,10008.0,...,12423.0,11348.0,10598.0,11023.0,11106.0,11379.0,11233.0,12520.0,12683.0,12457.0
2,LAUMT021126000000005,Employment,164075.0,162486.0,162329.0,161677.0,162537.0,166256.0,163164.0,162352.0,...,188330.0,188599.0,185862.0,186304.0,188090.0,190043.0,189822.0,185166.0,183324.0,183879.0
3,LAUMT021126000000006,Total Labor Force,175134.0,174092.0,173998.0,172899.0,173264.0,177710.0,173661.0,172360.0,...,200753.0,199947.0,196460.0,197327.0,199196.0,201422.0,201055.0,197686.0,196007.0,196336.0
4,LAUMT011382000000003,Unemployment Rate,5.2,5.4,5.1,4.5,4.4,5.4,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
5,LAUMT011382000000004,Unemployment,27274.0,28075.0,26660.0,23184.0,22945.0,28159.0,27154.0,28192.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
6,LAUMT011382000000005,Employment,494684.0,496008.0,497251.0,496340.0,496893.0,496239.0,497292.0,496204.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
7,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,523911.0,519524.0,519838.0,524398.0,524446.0,524396.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
8,LAUMT012662000000003,Unemployment Rate,5.2,5.1,4.9,4.1,4.0,4.9,5.5,4.8,...,4.2,3.8,3.7,3.3,3.3,2.9,3.1,3.8,3.4,3.3
9,LAUMT012662000000004,Unemployment,9275.0,9182.0,8879.0,7460.0,7289.0,9072.0,10047.0,8906.0,...,9267.0,8494.0,8111.0,7264.0,7441.0,6598.0,6829.0,8448.0,7568.0,7434.0
10,LAUMT012662000000005,Employment,170800.0,171510.0,172107.0,173275.0,173521.0,174202.0,173173.0,175288.0,...,213681.0,214487.0,212309.0,212953.0,217187.0,218310.0,216689.0,215197.0,217754.0,219105.0
11,LAUMT012662000000006,Total Labor Force,180075.0,180692.0,180986.0,180735.0,180810.0,183274.0,183220.0,184194.0,...,222948.0,222981.0,220420.0,220217.0,224628.0,224908.0,223518.0,223645.0,225322.0,226539.0
12,LAUMT013366000000003,Unemployment Rate,7.2,6.9,6.5,5.7,5.7,6.8,6.7,6.9,...,5.4,5.2,4.9,4.4,4.3,3.9,4.2,5.2,5.0,4.5
13,LAUMT013366000000004,Unemployment,12858.0,12424.0,11701.0,10363.0,10330.0,12507.0,12212.0,12622.0,...,10227.0,9817.0,9102.0,8194.0,8147.0,7367.0,7938.0,9788.0,9377.0,8619.0
14,LAUMT013366000000005,Employment,166757.0,168202.0,169707.0,170013.0,170352.0,170906.0,170251.0,169757.0,...,178600.0,178300.0,176710.0,178010.0,180239.0,180591.0,180178.0,178267.0,179920.0,181170.0
15,LAUMT013366000000006,Total Labor Force,179615.0,180626.0,181408.0,180376.0,180682.0,183413.0,182463.0,182379.0,...,188827.0,188117.0,185812.0,186204.0,188386.0,187958.0,188116.0,188055.0,189297.0,189789.0
16,LAUMT013386000000003,Unemployment Rate,5.5,5.5,5.2,4.5,4.6,5.7,5.4,5.6,...,4.5,4.2,4.1,3.7,3.7,3.4,3.6,4.3,3.9,3.7
17,LAUMT013386000000004,Unemployment,8817.0,8900.0,8409.0,7193.0,7373.0,9161.0,8866.0,9169.0,...,7913.0,7298.0,7111.0,6315.0,6430.0,5773.0,6105.0,7311.0,6707.0,6444.0
18,LAUMT013386000000005,Employment,152734.0,153151.0,153160.0,153450.0,153288.0,152850.0,154155.0,154166.0,...,166600.0,166385.0,164598.0,164738.0,165929.0,166073.0,165761.0,164532.0,166761.0,167730.0
19,LAUMT013386000000006,Total Labor Force,161551.0,162051.0,161569.0,160643.0,160661.0,162011.0,163021.0,163335.0,...,174513.0,173683.0,171709.0,171053.0,172359.0,171846.0,171866.0,171843.0,173468.0,174174.0
20,LAUMT053078000000003,Unemployment Rate,5.4,5.3,5.0,4.9,4.9,5.2,5.3,4.7,...,3.6,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1
21,LAUMT053078000000004,Unemployment,16379.0,16371.0,15647.0,15230.0,15287.0,16610.0,16795.0,14887.0,...,12776.0,12906.0,11763.0,11341.0,10672.0,10347.0,11539.0,13812.0,13780.0,11059.0
22,LAUMT053078000000005,Employment,286984.0,293072.0,294541.0,296662.0,297315.0,302157.0,302051.0,298937.0,...,345647.0,350872.0,345914.0,343927.0,344888.0,343621.0,340771.0,337077.0,341941.0,345459.0
23,LAUMT053078000000006,Total Labor Force,303363.0,309443.0,310188.0,311892.0,312602.0,318767.0,318846.0,313824.0,...,358423.0,363778.0,357677.0,355268.0,355560.0,353968.0,352310.0,350889.0,355721.0,356518.0
24,LAUMT042238000000003,Unemployment Rate,6.0,5.6,5.7,5.1,4.7,5.9,5.9,5.7,...,5.6,5.9,5.5,5.1,5.3,5.3,6.2,7.5,6.1,5.7
25,LAUMT042238000000004,Unemployment,3838.0,3591.0,3634.0,3343.0,3112.0,4025.0,4106.0,3759.0,...,4329.0,4524.0,4310.0,4076.0,4152.0,4115.0,4819.0,5819.0,4669.0,4369.0
26,LAUMT042238000000005,Employment,59659.0,60345.0,60264.0,61778.0,62480.0,64566.0,65169.0,62536.0,...,73430.0,72642.0,74341.0,75221.0,74656.0,73772.0,72679.0,72207.0,72175.0,72397.0
27,LAUMT042238000000006,Total Labor Force,63497.0,63936.0,63898.0,65121.0,65592.0,68591.0,69275.0,66295.0,...,77759.0,77166.0,78651.0,79297.0,78808.0,77887.0,77498.0,78026.0,76844.0,76766.0
28,LAUMT061254000000003,Unemployment Rate,10.7,11.0,11.6,10.2,8.7,9.4,9.2,8.4,...,8.4,8.3,7.3,6.5,6.5,6.5,7.5,9.1,9.3,10.1
29,LAUMT061254000000004,Unemployment,31924.0,32697.0,34629.0,30943.0,26520.0,29204.0,28506.0,26113.0,...,32752.0,32117.0,28690.0,25317.0,25417.0,25161.0,28821.0,35806.0,36656.0,39268.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,LAUMT174042000000005,Employment,150153.0,151390.0,151303.0,151163.0,152188.0,153374.0,152276.0,152019.0,...,159972.0,159876.0,156954.0,157855.0,158759.0,155267.0,157680.0,155538.0,157008.0,156704.0
635,LAUMT174042000000006,Total Labor Force,162930.0,164146.0,163457.0,162183.0,162544.0,164888.0,163941.0,163460.0,...,169236.0,169002.0,166203.0,166075.0,167798.0,171319.0,168473.0,167408.0,167811.0,167802.0
636,LAUMT174410000000003,Unemployment Rate,4.9,4.7,4.5,4.1,4.1,4.8,4.8,4.6,...,4.5,4.3,4.4,4.0,4.2,4.2,5.0,5.7,5.1,5.1
637,LAUMT174410000000004,Unemployment,5378.0,5234.0,4940.0,4508.0,4528.0,5438.0,5431.0,5221.0,...,5025.0,4858.0,4962.0,4424.0,4715.0,4646.0,5557.0,6212.0,5635.0,5606.0
638,LAUMT174410000000005,Employment,105079.0,105794.0,105961.0,106340.0,106882.0,107436.0,106778.0,108939.0,...,107368.0,107809.0,108355.0,107178.0,106812.0,106812.0,105700.0,103407.0,104537.0,104973.0
639,LAUMT174410000000006,Total Labor Force,110457.0,111028.0,110901.0,110848.0,111410.0,112874.0,112209.0,114160.0,...,112393.0,112667.0,113317.0,111602.0,111527.0,111458.0,111257.0,109619.0,110172.0,110579.0
640,LAUMT161426000000003,Unemployment Rate,6.1,6.0,5.8,5.4,4.6,4.9,4.8,4.8,...,2.5,2.5,2.3,2.2,2.2,2.5,2.7,3.7,3.3,2.9
641,LAUMT161426000000004,Unemployment,15992.0,15900.0,15133.0,13962.0,12071.0,12953.0,12696.0,12493.0,...,9104.0,9089.0,8493.0,7929.0,7968.0,9259.0,9702.0,13662.0,12189.0,10918.0
642,LAUMT161426000000005,Employment,245580.0,247504.0,248041.0,246591.0,249615.0,251204.0,252326.0,249914.0,...,354662.0,357093.0,355391.0,354929.0,353694.0,356136.0,356280.0,354258.0,358262.0,359395.0
643,LAUMT161426000000006,Total Labor Force,261572.0,263404.0,263174.0,260553.0,261686.0,264157.0,265022.0,262407.0,...,363766.0,366182.0,363884.0,362858.0,361662.0,365395.0,365982.0,367920.0,370451.0,370313.0
644,LAUMT191118000000003,Unemployment Rate,2.7,2.5,2.6,2.4,2.2,2.9,2.8,2.7,...,2.1,1.8,1.7,1.4,1.1,1.2,1.5,1.9,1.4,1.5
645,LAUMT191118000000004,Unemployment,1251.0,1227.0,1257.0,1183.0,1084.0,1367.0,1266.0,1250.0,...,1122.0,995.0,937.0,828.0,634.0,717.0,868.0,1109.0,857.0,892.0
646,LAUMT191118000000005,Employment,45248.0,46920.0,47260.0,47485.0,47870.0,46197.0,44594.0,45030.0,...,53447.0,54019.0,54955.0,58342.0,59323.0,58893.0,57702.0,56379.0,59405.0,59565.0
647,LAUMT191118000000006,Total Labor Force,46499.0,48147.0,48517.0,48668.0,48954.0,47564.0,45860.0,46280.0,...,54569.0,55014.0,55892.0,59170.0,59957.0,59610.0,58570.0,57488.0,60262.0,60457.0
648,LAUMT191630000000003,Unemployment Rate,5.0,4.9,4.8,4.3,3.9,4.3,4.1,4.8,...,2.8,2.6,2.6,2.3,2.1,2.2,2.7,3.5,2.9,2.9
649,LAUMT191630000000004,Unemployment,6917.0,6824.0,6703.0,6155.0,5537.0,6157.0,5817.0,6709.0,...,4021.0,3770.0,3760.0,3332.0,2988.0,3102.0,3903.0,5000.0,4171.0,4217.0
650,LAUMT191630000000005,Employment,131607.0,133503.0,134296.0,135694.0,135676.0,136026.0,135102.0,133527.0,...,141882.0,141264.0,139405.0,139422.0,140344.0,139382.0,138267.0,138115.0,139627.0,140703.0
651,LAUMT191630000000006,Total Labor Force,138524.0,140327.0,140999.0,141849.0,141213.0,142183.0,140919.0,140236.0,...,145903.0,145034.0,143165.0,142754.0,143332.0,142484.0,142170.0,143115.0,143798.0,144920.0
652,LAUMT191978000000003,Unemployment Rate,4.1,4.0,4.0,3.5,3.1,3.6,3.4,3.4,...,2.5,2.3,2.3,2.0,1.9,1.9,2.4,3.2,2.7,2.8
653,LAUMT191978000000004,Unemployment,11575.0,11473.0,11489.0,10144.0,9170.0,10774.0,9979.0,10008.0,...,8901.0,8332.0,8073.0,7190.0,6693.0,6602.0,8573.0,11272.0,9739.0,10044.0
654,LAUMT191978000000005,Employment,270878.0,274572.0,276368.0,280244.0,283308.0,287048.0,287401.0,284793.0,...,348321.0,352004.0,348040.0,344540.0,349207.0,346848.0,345447.0,346095.0,349668.0,352279.0
655,LAUMT191978000000006,Total Labor Force,282453.0,286045.0,287857.0,290388.0,292478.0,297822.0,297380.0,294801.0,...,357222.0,360336.0,356113.0,351730.0,355900.0,353450.0,354020.0,357367.0,359407.0,362323.0
656,LAUMT192698000000003,Unemployment Rate,3.2,3.0,2.9,2.7,2.5,3.1,2.9,2.9,...,2.2,2.0,2.0,1.7,1.5,1.5,1.9,2.3,1.8,1.9
657,LAUMT192698000000004,Unemployment,2597.0,2490.0,2480.0,2338.0,2120.0,2567.0,2401.0,2459.0,...,2162.0,1987.0,1938.0,1696.0,1426.0,1476.0,1782.0,2193.0,1795.0,1844.0
658,LAUMT192698000000005,Employment,79482.0,81297.0,82121.0,82751.0,82827.0,81220.0,81658.0,81297.0,...,94716.0,95470.0,95352.0,95259.0,96358.0,95717.0,94253.0,94477.0,96018.0,96830.0
659,LAUMT192698000000006,Total Labor Force,82079.0,83787.0,84601.0,85089.0,84947.0,83787.0,84059.0,83756.0,...,96878.0,97457.0,97290.0,96955.0,97784.0,97193.0,96035.0,96670.0,97813.0,98674.0
660,LAUMT171934000000003,Unemployment Rate,6.4,5.8,5.7,5.0,4.7,5.0,4.8,4.8,...,4.2,3.9,4.0,3.9,4.0,3.7,4.7,5.5,4.8,4.9
661,LAUMT171934000000004,Unemployment,12383.0,11278.0,11148.0,9822.0,9270.0,10057.0,9556.0,9470.0,...,8102.0,7589.0,7717.0,7479.0,7701.0,7129.0,8983.0,10555.0,9222.0,9489.0
662,LAUMT171934000000005,Employment,181275.0,183811.0,185426.0,186679.0,188385.0,191263.0,189999.0,188194.0,...,186143.0,186946.0,183769.0,183879.0,185585.0,184805.0,183311.0,181247.0,182372.0,184247.0
663,LAUMT171934000000006,Total Labor Force,193658.0,195089.0,196574.0,196501.0,197655.0,201320.0,199555.0,197664.0,...,194245.0,194535.0,191486.0,191358.0,193286.0,191934.0,192294.0,191802.0,191594.0,193736.0

In [67]:
employment['Area_Code']=employment['Series ID'].apply(lambda x:x[:-2])
employment

C:\Users\jho337\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Series ID,Data Type,Jan 2002,Feb 2002,Mar 2002,Apr 2002,May 2002,Jun 2002,Jul 2002,Aug 2002,...,Jul 2018,Aug 2018,Sep 2018,Oct 2018,Nov 2018,Dec 2018,Jan 2019,Feb 2019,Mar 2019,Area_Code
0,LAUMT021126000000003,Unemployment Rate,6.3,6.7,6.7,6.5,6.2,6.4,6.0,5.8,...,5.7,5.4,5.6,5.6,5.6,5.6,6.3,6.5,6.3,LAUMT0211260000000
1,LAUMT021126000000004,Unemployment,11059.0,11606.0,11669.0,11222.0,10727.0,11454.0,10497.0,10008.0,...,11348.0,10598.0,11023.0,11106.0,11379.0,11233.0,12520.0,12683.0,12457.0,LAUMT0211260000000
2,LAUMT021126000000005,Employment,164075.0,162486.0,162329.0,161677.0,162537.0,166256.0,163164.0,162352.0,...,188599.0,185862.0,186304.0,188090.0,190043.0,189822.0,185166.0,183324.0,183879.0,LAUMT0211260000000
3,LAUMT021126000000006,Total Labor Force,175134.0,174092.0,173998.0,172899.0,173264.0,177710.0,173661.0,172360.0,...,199947.0,196460.0,197327.0,199196.0,201422.0,201055.0,197686.0,196007.0,196336.0,LAUMT0211260000000
4,LAUMT011382000000003,Unemployment Rate,5.2,5.4,5.1,4.5,4.4,5.4,5.2,5.4,...,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4,LAUMT0113820000000
5,LAUMT011382000000004,Unemployment,27274.0,28075.0,26660.0,23184.0,22945.0,28159.0,27154.0,28192.0,...,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0,LAUMT0113820000000
6,LAUMT011382000000005,Employment,494684.0,496008.0,497251.0,496340.0,496893.0,496239.0,497292.0,496204.0,...,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0,LAUMT0113820000000
7,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,523911.0,519524.0,519838.0,524398.0,524446.0,524396.0,...,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0,LAUMT0113820000000
8,LAUMT012662000000003,Unemployment Rate,5.2,5.1,4.9,4.1,4.0,4.9,5.5,4.8,...,3.8,3.7,3.3,3.3,2.9,3.1,3.8,3.4,3.3,LAUMT0126620000000
9,LAUMT012662000000004,Unemployment,9275.0,9182.0,8879.0,7460.0,7289.0,9072.0,10047.0,8906.0,...,8494.0,8111.0,7264.0,7441.0,6598.0,6829.0,8448.0,7568.0,7434.0,LAUMT0126620000000
10,LAUMT012662000000005,Employment,170800.0,171510.0,172107.0,173275.0,173521.0,174202.0,173173.0,175288.0,...,214487.0,212309.0,212953.0,217187.0,218310.0,216689.0,215197.0,217754.0,219105.0,LAUMT0126620000000
11,LAUMT012662000000006,Total Labor Force,180075.0,180692.0,180986.0,180735.0,180810.0,183274.0,183220.0,184194.0,...,222981.0,220420.0,220217.0,224628.0,224908.0,223518.0,223645.0,225322.0,226539.0,LAUMT0126620000000
12,LAUMT013366000000003,Unemployment Rate,7.2,6.9,6.5,5.7,5.7,6.8,6.7,6.9,...,5.2,4.9,4.4,4.3,3.9,4.2,5.2,5.0,4.5,LAUMT0133660000000
13,LAUMT013366000000004,Unemployment,12858.0,12424.0,11701.0,10363.0,10330.0,12507.0,12212.0,12622.0,...,9817.0,9102.0,8194.0,8147.0,7367.0,7938.0,9788.0,9377.0,8619.0,LAUMT0133660000000
14,LAUMT013366000000005,Employment,166757.0,168202.0,169707.0,170013.0,170352.0,170906.0,170251.0,169757.0,...,178300.0,176710.0,178010.0,180239.0,180591.0,180178.0,178267.0,179920.0,181170.0,LAUMT0133660000000
15,LAUMT013366000000006,Total Labor Force,179615.0,180626.0,181408.0,180376.0,180682.0,183413.0,182463.0,182379.0,...,188117.0,185812.0,186204.0,188386.0,187958.0,188116.0,188055.0,189297.0,189789.0,LAUMT0133660000000
16,LAUMT013386000000003,Unemployment Rate,5.5,5.5,5.2,4.5,4.6,5.7,5.4,5.6,...,4.2,4.1,3.7,3.7,3.4,3.6,4.3,3.9,3.7,LAUMT0133860000000
17,LAUMT013386000000004,Unemployment,8817.0,8900.0,8409.0,7193.0,7373.0,9161.0,8866.0,9169.0,...,7298.0,7111.0,6315.0,6430.0,5773.0,6105.0,7311.0,6707.0,6444.0,LAUMT0133860000000
18,LAUMT013386000000005,Employment,152734.0,153151.0,153160.0,153450.0,153288.0,152850.0,154155.0,154166.0,...,166385.0,164598.0,164738.0,165929.0,166073.0,165761.0,164532.0,166761.0,167730.0,LAUMT0133860000000
19,LAUMT013386000000006,Total Labor Force,161551.0,162051.0,161569.0,160643.0,160661.0,162011.0,163021.0,163335.0,...,173683.0,171709.0,171053.0,172359.0,171846.0,171866.0,171843.0,173468.0,174174.0,LAUMT0133860000000
20,LAUMT053078000000003,Unemployment Rate,5.4,5.3,5.0,4.9,4.9,5.2,5.3,4.7,...,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1,LAUMT0530780000000
21,LAUMT053078000000004,Unemployment,16379.0,16371.0,15647.0,15230.0,15287.0,16610.0,16795.0,14887.0,...,12906.0,11763.0,11341.0,10672.0,10347.0,11539.0,13812.0,13780.0,11059.0,LAUMT0530780000000
22,LAUMT053078000000005,Employment,286984.0,293072.0,294541.0,296662.0,297315.0,302157.0,302051.0,298937.0,...,350872.0,345914.0,343927.0,344888.0,343621.0,340771.0,337077.0,341941.0,345459.0,LAUMT0530780000000
23,LAUMT053078000000006,Total Labor Force,303363.0,309443.0,310188.0,311892.0,312602.0,318767.0,318846.0,313824.0,...,363778.0,357677.0,355268.0,355560.0,353968.0,352310.0,350889.0,355721.0,356518.0,LAUMT0530780000000
24,LAUMT042238000000003,Unemployment Rate,6.0,5.6,5.7,5.1,4.7,5.9,5.9,5.7,...,5.9,5.5,5.1,5.3,5.3,6.2,7.5,6.1,5.7,LAUMT0422380000000
25,LAUMT042238000000004,Unemployment,3838.0,3591.0,3634.0,3343.0,3112.0,4025.0,4106.0,3759.0,...,4524.0,4310.0,4076.0,4152.0,4115.0,4819.0,5819.0,4669.0,4369.0,LAUMT0422380000000
26,LAUMT042238000000005,Employment,59659.0,60345.0,60264.0,61778.0,62480.0,64566.0,65169.0,62536.0,...,72642.0,74341.0,75221.0,74656.0,73772.0,72679.0,72207.0,72175.0,72397.0,LAUMT0422380000000
27,LAUMT042238000000006,Total Labor Force,63497.0,63936.0,63898.0,65121.0,65592.0,68591.0,69275.0,66295.0,...,77166.0,78651.0,79297.0,78808.0,77887.0,77498.0,78026.0,76844.0,76766.0,LAUMT0422380000000
28,LAUMT061254000000003,Unemployment Rate,10.7,11.0,11.6,10.2,8.7,9.4,9.2,8.4,...,8.3,7.3,6.5,6.5,6.5,7.5,9.1,9.3,10.1,LAUMT0612540000000
29,LAUMT061254000000004,Unemployment,31924.0,32697.0,34629.0,30943.0,26520.0,29204.0,28506.0,26113.0,...,32117.0,28690.0,25317.0,25417.0,25161.0,28821.0,35806.0,36656.0,39268.0,LAUMT0612540000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,LAUMT174042000000005,Employment,150153.0,151390.0,151303.0,151163.0,152188.0,153374.0,152276.0,152019.0,...,159876.0,156954.0,157855.0,158759.0,155267.0,157680.0,155538.0,157008.0,156704.0,LAUMT1740420000000
635,LAUMT174042000000006,Total Labor Force,162930.0,164146.0,163457.0,162183.0,162544.0,164888.0,163941.0,163460.0,...,169002.0,166203.0,166075.0,167798.0,171319.0,168473.0,167408.0,167811.0,167802.0,LAUMT1740420000000
636,LAUMT174410000000003,Unemployment Rate,4.9,4.7,4.5,4.1,4.1,4.8,4.8,4.6,...,4.3,4.4,4.0,4.2,4.2,5.0,5.7,5.1,5.1,LAUMT1744100000000
637,LAUMT174410000000004,Unemployment,5378.0,5234.0,4940.0,4508.0,4528.0,5438.0,5431.0,5221.0,...,4858.0,4962.0,4424.0,4715.0,4646.0,5557.0,6212.0,5635.0,5606.0,LAUMT1744100000000
638,LAUMT174410000000005,Employment,105079.0,105794.0,105961.0,106340.0,106882.0,107436.0,106778.0,108939.0,...,107809.0,108355.0,107178.0,106812.0,106812.0,105700.0,103407.0,104537.0,104973.0,LAUMT1744100000000
639,LAUMT174410000000006,Total Labor Force,110457.0,111028.0,110901.0,110848.0,111410.0,112874.0,112209.0,114160.0,...,112667.0,113317.0,111602.0,111527.0,111458.0,111257.0,109619.0,110172.0,110579.0,LAUMT1744100000000
640,LAUMT161426000000003,Unemployment Rate,6.1,6.0,5.8,5.4,4.6,4.9,4.8,4.8,...,2.5,2.3,2.2,2.2,2.5,2.7,3.7,3.3,2.9,LAUMT1614260000000
641,LAUMT161426000000004,Unemployment,15992.0,15900.0,15133.0,13962.0,12071.0,12953.0,12696.0,12493.0,...,9089.0,8493.0,7929.0,7968.0,9259.0,9702.0,13662.0,12189.0,10918.0,LAUMT1614260000000
642,LAUMT161426000000005,Employment,245580.0,247504.0,248041.0,246591.0,249615.0,251204.0,252326.0,249914.0,...,357093.0,355391.0,354929.0,353694.0,356136.0,356280.0,354258.0,358262.0,359395.0,LAUMT1614260000000
643,LAUMT161426000000006,Total Labor Force,261572.0,263404.0,263174.0,260553.0,261686.0,264157.0,265022.0,262407.0,...,366182.0,363884.0,362858.0,361662.0,365395.0,365982.0,367920.0,370451.0,370313.0,LAUMT1614260000000
644,LAUMT191118000000003,Unemployment Rate,2.7,2.5,2.6,2.4,2.2,2.9,2.8,2.7,...,1.8,1.7,1.4,1.1,1.2,1.5,1.9,1.4,1.5,LAUMT1911180000000
645,LAUMT191118000000004,Unemployment,1251.0,1227.0,1257.0,1183.0,1084.0,1367.0,1266.0,1250.0,...,995.0,937.0,828.0,634.0,717.0,868.0,1109.0,857.0,892.0,LAUMT1911180000000
646,LAUMT191118000000005,Employment,45248.0,46920.0,47260.0,47485.0,47870.0,46197.0,44594.0,45030.0,...,54019.0,54955.0,58342.0,59323.0,58893.0,57702.0,56379.0,59405.0,59565.0,LAUMT1911180000000
647,LAUMT191118000000006,Total Labor Force,46499.0,48147.0,48517.0,48668.0,48954.0,47564.0,45860.0,46280.0,...,55014.0,55892.0,59170.0,59957.0,59610.0,58570.0,57488.0,60262.0,60457.0,LAUMT1911180000000
648,LAUMT191630000000003,Unemployment Rate,5.0,4.9,4.8,4.3,3.9,4.3,4.1,4.8,...,2.6,2.6,2.3,2.1,2.2,2.7,3.5,2.9,2.9,LAUMT1916300000000
649,LAUMT191630000000004,Unemployment,6917.0,6824.0,6703.0,6155.0,5537.0,6157.0,5817.0,6709.0,...,3770.0,3760.0,3332.0,2988.0,3102.0,3903.0,5000.0,4171.0,4217.0,LAUMT1916300000000
650,LAUMT191630000000005,Employment,131607.0,133503.0,134296.0,135694.0,135676.0,136026.0,135102.0,133527.0,...,141264.0,139405.0,139422.0,140344.0,139382.0,138267.0,138115.0,139627.0,140703.0,LAUMT1916300000000
651,LAUMT191630000000006,Total Labor Force,138524.0,140327.0,140999.0,141849.0,141213.0,142183.0,140919.0,140236.0,...,145034.0,143165.0,142754.0,143332.0,142484.0,142170.0,143115.0,143798.0,144920.0,LAUMT1916300000000
652,LAUMT191978000000003,Unemployment Rate,4.1,4.0,4.0,3.5,3.1,3.6,3.4,3.4,...,2.3,2.3,2.0,1.9,1.9,2.4,3.2,2.7,2.8,LAUMT1919780000000
653,LAUMT191978000000004,Unemployment,11575.0,11473.0,11489.0,10144.0,9170.0,10774.0,9979.0,10008.0,...,8332.0,8073.0,7190.0,6693.0,6602.0,8573.0,11272.0,9739.0,10044.0,LAUMT1919780000000
654,LAUMT191978000000005,Employment,270878.0,274572.0,276368.0,280244.0,283308.0,287048.0,287401.0,284793.0,...,352004.0,348040.0,344540.0,349207.0,346848.0,345447.0,346095.0,349668.0,352279.0,LAUMT1919780000000
655,LAUMT191978000000006,Total Labor Force,282453.0,286045.0,287857.0,290388.0,292478.0,297822.0,297380.0,294801.0,...,360336.0,356113.0,351730.0,355900.0,353450.0,354020.0,357367.0,359407.0,362323.0,LAUMT1919780000000
656,LAUMT192698000000003,Unemployment Rate,3.2,3.0,2.9,2.7,2.5,3.1,2.9,2.9,...,2.0,2.0,1.7,1.5,1.5,1.9,2.3,1.8,1.9,LAUMT1926980000000
657,LAUMT192698000000004,Unemployment,2597.0,2490.0,2480.0,2338.0,2120.0,2567.0,2401.0,2459.0,...,1987.0,1938.0,1696.0,1426.0,1476.0,1782.0,2193.0,1795.0,1844.0,LAUMT1926980000000
658,LAUMT192698000000005,Employment,79482.0,81297.0,82121.0,82751.0,82827.0,81220.0,81658.0,81297.0,...,95470.0,95352.0,95259.0,96358.0,95717.0,94253.0,94477.0,96018.0,96830.0,LAUMT1926980000000
659,LAUMT192698000000006,Total Labor Force,82079.0,83787.0,84601.0,85089.0,84947.0,83787.0,84059.0,83756.0,...,97457.0,97290.0,96955.0,97784.0,97193.0,96035.0,96670.0,97813.0,98674.0,LAUMT1926980000000
660,LAUMT171934000000003,Unemployment Rate,6.4,5.8,5.7,5.0,4.7,5.0,4.8,4.8,...,3.9,4.0,3.9,4.0,3.7,4.7,5.5,4.8,4.9,LAUMT1719340000000
661,LAUMT171934000000004,Unemployment,12383.0,11278.0,11148.0,9822.0,9270.0,10057.0,9556.0,9470.0,...,7589.0,7717.0,7479.0,7701.0,7129.0,8983.0,10555.0,9222.0,9489.0,LAUMT1719340000000
662,LAUMT171934000000005,Employment,181275.0,183811.0,185426.0,186679.0,188385.0,191263.0,189999.0,188194.0,...,186946.0,183769.0,183879.0,185585.0,184805.0,183311.0,181247.0,182372.0,184247.0,LAUMT1719340000000
663,LAUMT171934000000006,Total Labor Force,193658.0,195089.0,196574.0,196501.0,197655.0,201320.0,199555.0,197664.0,...,194535.0,191486.0,191358.0,193286.0,191934.0,192294.0,191802.0,191594.0,193736.0,LAUMT1719340000000

In [69]:
merged=pd.merge(df,employment,on='Area_Code')
merged

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Jan 2002,Feb 2002,...,Jun 2018,Jul 2018,Aug 2018,Sep 2018,Oct 2018,Nov 2018,Dec 2018,Jan 2019,Feb 2019,Mar 2019
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
1,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,27274.0,28075.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
2,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,494684.0,496008.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
3,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
4,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
5,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,27274.0,28075.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
6,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,494684.0,496008.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
7,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
8,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
9,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,27274.0,28075.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
10,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,494684.0,496008.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
11,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
12,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
13,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,27274.0,28075.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
14,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,494684.0,496008.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
15,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
16,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
17,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,27274.0,28075.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
18,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,494684.0,496008.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
19,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
20,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
21,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,27274.0,28075.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
22,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,494684.0,496008.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
23,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
24,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
25,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,27274.0,28075.0,...,23138.0,20721.0,20124.0,18060.0,18447.0,16618.0,17366.0,21438.0,19591.0,18875.0
26,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,494684.0,496008.0,...,525729.0,527122.0,522526.0,523524.0,530206.0,531460.0,531358.0,526601.0,531358.0,535594.0
27,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,521958.0,524083.0,...,548867.0,547843.0,542650.0,541584.0,548653.0,548078.0,548724.0,548039.0,550949.0,554469.0
28,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000003,Unemployment Rate,5.2,5.1,...,4.2,3.8,3.7,3.3,3.3,2.9,3.1,3.8,3.4,3.3
29,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000004,Unemployment,9275.0,9182.0,...,9267.0,8494.0,8111.0,7264.0,7441.0,6598.0,6829.0,8448.0,7568.0,7434.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3430,4593,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000005,Employment,154109.0,153987.0,...,172592.0,172641.0,171806.0,171504.0,171954.0,172101.0,171023.0,170071.0,170697.0,170806.0
3431,4593,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000006,Total Labor Force,163708.0,164450.0,...,178409.0,177883.0,176585.0,175294.0,175833.0,176011.0,175541.0,175671.0,176058.0,176099.0
3432,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3433,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,14214.0,15128.0,...,11216.0,9462.0,8448.0,7048.0,7515.0,7445.0,8018.0,9840.0,9358.0,9439.0
3434,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,321172.0,324926.0,...,381398.0,383588.0,377388.0,377935.0,378972.0,380192.0,377700.0,372409.0,377439.0,377704.0
3435,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,335386.0,340054.0,...,392614.0,393050.0,385836.0,384983.0,386487.0,387637.0,385718.0,382249.0,386797.0,387143.0
3436,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3437,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,14214.0,15128.0,...,11216.0,9462.0,8448.0,7048.0,7515.0,7445.0,8018.0,9840.0,9358.0,9439.0
3438,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,321172.0,324926.0,...,381398.0,383588.0,377388.0,377935.0,378972.0,380192.0,377700.0,372409.0,377439.0,377704.0
3439,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,335386.0,340054.0,...,392614.0,393050.0,385836.0,384983.0,386487.0,387637.0,385718.0,382249.0,386797.0,387143.0
3440,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3441,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,14214.0,15128.0,...,11216.0,9462.0,8448.0,7048.0,7515.0,7445.0,8018.0,9840.0,9358.0,9439.0
3442,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,321172.0,324926.0,...,381398.0,383588.0,377388.0,377935.0,378972.0,380192.0,377700.0,372409.0,377439.0,377704.0
3443,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,335386.0,340054.0,...,392614.0,393050.0,385836.0,384983.0,386487.0,387637.0,385718.0,382249.0,386797.0,387143.0
3444,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3445,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,14214.0,15128.0,...,11216.0,9462.0,8448.0,7048.0,7515.0,7445.0,8018.0,9840.0,9358.0,9439.0
3446,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,321172.0,324926.0,...,381398.0,383588.0,377388.0,377935.0,378972.0,380192.0,377700.0,372409.0,377439.0,377704.0
3447,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,335386.0,340054.0,...,392614.0,393050.0,385836.0,384983.0,386487.0,387637.0,385718.0,382249.0,386797.0,387143.0
3448,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000003,Unemployment Rate,5.4,5.8,...,3.4,3.0,2.9,2.2,2.2,2.2,2.4,2.8,2.6,2.7
3449,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000004,Unemployment,4941.0,5322.0,...,3203.0,2819.0,2646.0,1997.0,2068.0,2040.0,2243.0,2625.0,2440.0,2501.0
3450,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000005,Employment,86420.0,86630.0,...,90377.0,91366.0,89931.0,90100.0,90205.0,90169.0,89930.0,89686.0,90437.0,90583.0
3451,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000006,Total Labor Force,91361.0,91952.0,...,93580.0,94185.0,92577.0,92097.0,92273.0,92209.0,92173.0,92311.0,92877.0,93084.0
3452,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000003,Unemployment Rate,7.0,7.4,...,4.1,4.0,3.7,3.0,2.9,3.0,3.3,4.1,4.0,3.9
3453,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000004,Unemployment,7000.0,7411.0,...,4170.0,4030.0,3720.0,3012.0,2876.0,2909.0,3193.0,4026.0,3964.0,3920.0
3454,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000005,Employment,92355.0,92710.0,...,96894.0,97727.0,96721.0,95880.0,95805.0,95656.0,94992.0,94733.0,95505.0,95580.0
3455,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000006,Total Labor Force,99355.0,100121.0,...,101064.0,101757.0,100441.0,98892.0,98681.0,98565.0,98185.0,98759.0,99469.0,99500.0
3456,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000003,Unemployment Rate,5.3,6.0,...,3.1,2.6,2.4,2.0,2.1,2.1,2.3,2.7,2.5,2.6
3457,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000004,Unemployment,3369.0,3869.0,...,1989.0,1682.0,1534.0,1245.0,1290.0,1325.0,1400.0,1654.0,1574.0,1614.0
3458,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000005,Employment,60406.0,60221.0,...,62993.0,62772.0,61963.0,61526.0,61241.0,60937.0,60472.0,60422.0,60737.0,60943.0
3459,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,63775.0,64090.0,...,64982.0,64454.0,63497.0,62771.0,62531.0,62262.0,61872.0,62076.0,62311.0,62557.0

In [128]:
unemployment_rate=merged[merged['Data Type']=='Unemployment Rate']
unemployment_rate

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Jan 2002,Feb 2002,...,Jun 2018,Jul 2018,Aug 2018,Sep 2018,Oct 2018,Nov 2018,Dec 2018,Jan 2019,Feb 2019,Mar 2019
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
4,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
8,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
12,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
16,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
20,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
24,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,5.2,5.4,...,4.2,3.8,3.7,3.3,3.4,3.0,3.2,3.9,3.6,3.4
28,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000003,Unemployment Rate,5.2,5.1,...,4.2,3.8,3.7,3.3,3.3,2.9,3.1,3.8,3.4,3.3
32,41,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000003,Unemployment Rate,5.2,5.1,...,4.2,3.8,3.7,3.3,3.3,2.9,3.1,3.8,3.4,3.3
36,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT,LAUMT0133660000000,LAUMT013366000000003,Unemployment Rate,7.2,6.9,...,5.4,5.2,4.9,4.4,4.3,3.9,4.2,5.2,5.0,4.5
40,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,5.5,5.5,...,4.5,4.2,4.1,3.7,3.7,3.4,3.6,4.3,3.9,3.7
44,49,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,5.5,5.5,...,4.5,4.2,4.1,3.7,3.7,3.4,3.6,4.3,3.9,3.7
48,50,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,5.5,5.5,...,4.5,4.2,4.1,3.7,3.7,3.4,3.6,4.3,3.9,3.7
52,51,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,5.5,5.5,...,4.5,4.2,4.1,3.7,3.7,3.4,3.6,4.3,3.9,3.7
56,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000003,Unemployment Rate,6.3,6.7,...,6.2,5.7,5.4,5.6,5.6,5.6,5.6,6.3,6.5,6.3
60,71,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000003,Unemployment Rate,6.3,6.7,...,6.2,5.7,5.4,5.6,5.6,5.6,5.6,6.3,6.5,6.3
64,98,MT0422380000000,22380,"Flagstaff, AZ Metropolitan Statistical Area",MT,LAUMT0422380000000,LAUMT042238000000003,Unemployment Rate,6.0,5.6,...,5.6,5.9,5.5,5.1,5.3,5.3,6.2,7.5,6.1,5.7
68,153,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,5.4,5.3,...,3.6,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1
72,154,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,5.4,5.3,...,3.6,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1
76,155,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,5.4,5.3,...,3.6,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1
80,156,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,5.4,5.3,...,3.6,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1
84,157,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,5.4,5.3,...,3.6,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1
88,158,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,5.4,5.3,...,3.6,3.5,3.3,3.2,3.0,2.9,3.3,3.9,3.9,3.1
92,189,MT0612540000000,12540,"Bakersfield, CA Metropolitan Statistical Area",MT,LAUMT0612540000000,LAUMT061254000000003,Unemployment Rate,10.7,11.0,...,8.4,8.3,7.3,6.5,6.5,6.5,7.5,9.1,9.3,10.1
96,191,MT0617020000000,17020,"Chico, CA Metropolitan Statistical Area",MT,LAUMT0617020000000,LAUMT061702000000003,Unemployment Rate,8.4,7.9,...,5.2,5.2,4.8,4.1,4.2,4.3,5.5,6.6,6.1,6.2
100,195,MT0620940000000,20940,"El Centro, CA Metropolitan Statistical Area",MT,LAUMT0620940000000,LAUMT062094000000003,Unemployment Rate,13.8,12.2,...,18.0,20.1,21.6,20.0,19.7,18.5,17.7,18.4,17.3,17.8
104,199,MT0625260000000,25260,"Hanford-Corcoran, CA Metropolitan Statistical ...",MT,LAUMT0625260000000,LAUMT062526000000003,Unemployment Rate,13.8,13.5,...,8.1,7.6,6.7,5.9,6.2,6.9,8.0,9.8,10.0,10.3
108,201,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000003,Unemployment Rate,6.6,6.2,...,4.4,4.7,4.6,4.2,4.2,4.1,4.1,4.5,4.0,4.1
112,202,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000003,Unemployment Rate,6.6,6.2,...,4.4,4.7,4.6,4.2,4.2,4.1,4.1,4.5,4.0,4.1
116,205,MT0632900000000,32900,"Merced, CA Metropolitan Statistical Area",MT,LAUMT0632900000000,LAUMT063290000000003,Unemployment Rate,13.4,13.6,...,8.5,8.4,7.3,6.0,6.2,6.8,8.3,10.3,10.6,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3340,4478,MT5313380000000,13380,"Bellingham, WA Metropolitan Statistical Area",MT,LAUMT5313380000000,LAUMT531338000000003,Unemployment Rate,8.6,8.2,...,4.6,4.5,4.5,4.1,4.3,4.6,5.1,5.5,5.9,5.2
3344,4479,MT5314740000000,14740,"Bremerton-Silverdale, WA Metropolitan Statisti...",MT,LAUMT5314740000000,LAUMT531474000000003,Unemployment Rate,7.8,7.6,...,4.4,4.3,4.3,4.1,4.3,4.5,4.9,5.3,5.3,5.2
3348,4485,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000003,Unemployment Rate,9.1,8.4,...,4.7,4.8,4.7,4.2,4.5,5.2,6.5,7.1,7.5,7.1
3352,4486,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000003,Unemployment Rate,9.1,8.4,...,4.7,4.8,4.7,4.2,4.5,5.2,6.5,7.1,7.5,7.1
3356,4490,MT5331020000000,31020,"Longview, WA Metropolitan Statistical Area",MT,LAUMT5331020000000,LAUMT533102000000003,Unemployment Rate,12.5,11.9,...,5.8,5.6,5.6,5.0,5.3,5.6,6.3,6.9,6.6,6.7
3360,4492,MT5334580000000,34580,"Mount Vernon-Anacortes, WA Metropolitan Statis...",MT,LAUMT5334580000000,LAUMT533458000000003,Unemployment Rate,10.0,9.5,...,4.9,4.8,4.8,4.4,4.7,5.0,5.6,6.3,6.8,5.9
3364,4495,MT5336500000000,36500,"Olympia-Tumwater, WA Metropolitan Statistical ...",MT,LAUMT5336500000000,LAUMT533650000000003,Unemployment Rate,7.5,7.3,...,4.6,4.5,4.5,4.1,4.3,4.6,5.0,5.4,5.5,5.4
3368,4503,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000003,Unemployment Rate,6.9,6.9,...,4.0,3.9,3.8,3.7,3.7,3.9,3.8,4.2,4.1,4.1
3372,4504,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000003,Unemployment Rate,6.9,6.9,...,4.0,3.9,3.8,3.7,3.7,3.9,3.8,4.2,4.1,4.1
3376,4505,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000003,Unemployment Rate,6.9,6.9,...,4.0,3.9,3.8,3.7,3.7,3.9,3.8,4.2,4.1,4.1
3380,4507,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000003,Unemployment Rate,9.9,9.7,...,5.0,4.9,5.0,4.5,4.6,4.9,5.9,6.8,6.5,6.8
3384,4508,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000003,Unemployment Rate,9.9,9.7,...,5.0,4.9,5.0,4.5,4.6,4.9,5.9,6.8,6.5,6.8
3388,4509,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000003,Unemployment Rate,9.9,9.7,...,5.0,4.9,5.0,4.5,4.6,4.9,5.9,6.8,6.5,6.8
3392,4513,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000003,Unemployment Rate,11.3,10.9,...,3.8,3.2,4.0,3.3,3.8,4.9,6.1,7.0,7.0,6.6
3396,4514,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000003,Unemployment Rate,11.3,10.9,...,3.8,3.2,4.0,3.3,3.8,4.9,6.1,7.0,7.0,6.6
3400,4515,MT5349420000000,49420,"Yakima, WA Metropolitan Statistical Area",MT,LAUMT5349420000000,LAUMT534942000000003,Unemployment Rate,14.0,12.3,...,5.0,5.0,5.6,4.2,4.9,6.6,8.6,9.8,9.9,9.2
3404,4572,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000003,Unemployment Rate,6.0,6.5,...,3.2,2.9,2.7,2.2,2.2,2.2,2.6,3.1,2.9,2.8
3408,4573,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000003,Unemployment Rate,6.0,6.5,...,3.2,2.9,2.7,2.2,2.2,2.2,2.6,3.1,2.9,2.8
3412,4586,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000003,Unemployment Rate,6.5,6.9,...,3.2,2.9,2.5,2.1,2.2,2.3,2.9,3.8,3.5,3.4
3416,4587,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000003,Unemployment Rate,6.5,6.9,...,3.2,2.9,2.5,2.1,2.2,2.3,2.9,3.8,3.5,3.4
3420,4591,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000003,Unemployment Rate,5.9,6.4,...,3.3,2.9,2.7,2.2,2.2,2.2,2.6,3.2,3.0,3.0
3424,4592,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000003,Unemployment Rate,5.9,6.4,...,3.3,2.9,2.7,2.2,2.2,2.2,2.6,3.2,3.0,3.0
3428,4593,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000003,Unemployment Rate,5.9,6.4,...,3.3,2.9,2.7,2.2,2.2,2.2,2.6,3.2,3.0,3.0
3432,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3436,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3440,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3444,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,4.2,4.4,...,2.9,2.4,2.2,1.8,1.9,1.9,2.1,2.6,2.4,2.4
3448,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000003,Unemployment Rate,5.4,5.8,...,3.4,3.0,2.9,2.2,2.2,2.2,2.4,2.8,2.6,2.7
3452,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000003,Unemployment Rate,7.0,7.4,...,4.1,4.0,3.7,3.0,2.9,3.0,3.3,4.1,4.0,3.9
3456,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000003,Unemployment Rate,5.3,6.0,...,3.1,2.6,2.4,2.0,2.1,2.1,2.3,2.7,2.5,2.6

In [129]:
unemployment_labor=merged[merged['Data Type']=='Unemployment ']
employment_labor=merged[merged['Data Type']=='Employment']
total_labor=merged[merged['Data Type']=='Total Labor Force']

In [77]:
test=unemployment_rate.head()

In [79]:
test2=pd.melt(test, id_vars=list(test)[0:8], value_vars=list(merged)[9:],var_name='Month-Year',
       value_name='Unemployment_Rate')

In [82]:
test2['Month-Year']=test2['Month-Year'].apply(lambda x: x.replace("\\n",""))
test2

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Month-Year,Unemployment_Rate
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
1,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
2,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
3,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
4,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
5,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1
6,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1
7,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1
8,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1
9,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1
10,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5
11,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5
12,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5
13,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5
14,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5
15,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4
16,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4
17,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4
18,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4
19,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4
20,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4
21,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4
22,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4
23,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4
24,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4
25,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2
26,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2
27,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2
28,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2
29,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2
...,...,...,...,...,...,...,...,...,...,...
1000,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4
1001,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4
1002,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4
1003,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4
1004,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4
1005,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0
1006,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0
1007,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0
1008,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0
1009,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0
1010,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2
1011,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2
1012,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2
1013,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2
1014,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2
1015,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9
1016,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9
1017,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9
1018,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9
1019,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9
1020,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6
1021,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6
1022,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6
1023,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6
1024,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6
1025,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4
1026,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4
1027,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4
1028,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4
1029,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4

In [83]:
import datetime
test2['DateTime']=pd.to_datetime(test2['Month-Year'])
test2

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Month-Year,Unemployment_Rate,DateTime
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4,2002-02-01
1,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4,2002-02-01
2,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4,2002-02-01
3,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4,2002-02-01
4,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4,2002-02-01
5,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1,2002-03-01
6,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1,2002-03-01
7,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1,2002-03-01
8,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1,2002-03-01
9,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2002,5.1,2002-03-01
10,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5,2002-04-01
11,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5,2002-04-01
12,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5,2002-04-01
13,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5,2002-04-01
14,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Apr\n2002,4.5,2002-04-01
15,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4,2002-05-01
16,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4,2002-05-01
17,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4,2002-05-01
18,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4,2002-05-01
19,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,May\n2002,4.4,2002-05-01
20,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4,2002-06-01
21,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4,2002-06-01
22,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4,2002-06-01
23,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4,2002-06-01
24,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jun\n2002,5.4,2002-06-01
25,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2,2002-07-01
26,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2,2002-07-01
27,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2,2002-07-01
28,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2,2002-07-01
29,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jul\n2002,5.2,2002-07-01
...,...,...,...,...,...,...,...,...,...,...,...
1000,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4,2018-10-01
1001,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4,2018-10-01
1002,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4,2018-10-01
1003,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4,2018-10-01
1004,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Oct\n2018,3.4,2018-10-01
1005,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0,2018-11-01
1006,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0,2018-11-01
1007,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0,2018-11-01
1008,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0,2018-11-01
1009,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Nov\n2018,3.0,2018-11-01
1010,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2,2018-12-01
1011,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2,2018-12-01
1012,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2,2018-12-01
1013,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2,2018-12-01
1014,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Dec\n2018,3.2,2018-12-01
1015,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9,2019-01-01
1016,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9,2019-01-01
1017,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9,2019-01-01
1018,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9,2019-01-01
1019,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Jan\n2019,3.9,2019-01-01
1020,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6,2019-02-01
1021,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6,2019-02-01
1022,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6,2019-02-01
1023,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6,2019-02-01
1024,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2019,3.6,2019-02-01
1025,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4,2019-03-01
1026,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4,2019-03-01
1027,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4,2019-03-01
1028,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4,2019-03-01
1029,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Mar\n2019,3.4,2019-03-01

In [130]:
df_unemployment=pd.melt(unemployment_rate, id_vars=list(unemployment_rate)[0:8], value_vars=list(unemployment_rate)[9:],var_name='Month-Year',
       value_name='Unemployment_Rate')
df_unemployment

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Month-Year,Unemployment_Rate
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
1,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
2,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
3,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
4,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
5,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
6,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000003,Unemployment Rate,Feb\n2002,5.4
7,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000003,Unemployment Rate,Feb\n2002,5.1
8,41,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000003,Unemployment Rate,Feb\n2002,5.1
9,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT,LAUMT0133660000000,LAUMT013366000000003,Unemployment Rate,Feb\n2002,6.9
10,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,Feb\n2002,5.5
11,49,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,Feb\n2002,5.5
12,50,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,Feb\n2002,5.5
13,51,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000003,Unemployment Rate,Feb\n2002,5.5
14,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000003,Unemployment Rate,Feb\n2002,6.7
15,71,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000003,Unemployment Rate,Feb\n2002,6.7
16,98,MT0422380000000,22380,"Flagstaff, AZ Metropolitan Statistical Area",MT,LAUMT0422380000000,LAUMT042238000000003,Unemployment Rate,Feb\n2002,5.6
17,153,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,Feb\n2002,5.3
18,154,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,Feb\n2002,5.3
19,155,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,Feb\n2002,5.3
20,156,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,Feb\n2002,5.3
21,157,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,Feb\n2002,5.3
22,158,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000003,Unemployment Rate,Feb\n2002,5.3
23,189,MT0612540000000,12540,"Bakersfield, CA Metropolitan Statistical Area",MT,LAUMT0612540000000,LAUMT061254000000003,Unemployment Rate,Feb\n2002,11.0
24,191,MT0617020000000,17020,"Chico, CA Metropolitan Statistical Area",MT,LAUMT0617020000000,LAUMT061702000000003,Unemployment Rate,Feb\n2002,7.9
25,195,MT0620940000000,20940,"El Centro, CA Metropolitan Statistical Area",MT,LAUMT0620940000000,LAUMT062094000000003,Unemployment Rate,Feb\n2002,12.2
26,199,MT0625260000000,25260,"Hanford-Corcoran, CA Metropolitan Statistical ...",MT,LAUMT0625260000000,LAUMT062526000000003,Unemployment Rate,Feb\n2002,13.5
27,201,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000003,Unemployment Rate,Feb\n2002,6.2
28,202,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000003,Unemployment Rate,Feb\n2002,6.2
29,205,MT0632900000000,32900,"Merced, CA Metropolitan Statistical Area",MT,LAUMT0632900000000,LAUMT063290000000003,Unemployment Rate,Feb\n2002,13.6
...,...,...,...,...,...,...,...,...,...,...
178160,4478,MT5313380000000,13380,"Bellingham, WA Metropolitan Statistical Area",MT,LAUMT5313380000000,LAUMT531338000000003,Unemployment Rate,Mar\n2019,5.2
178161,4479,MT5314740000000,14740,"Bremerton-Silverdale, WA Metropolitan Statisti...",MT,LAUMT5314740000000,LAUMT531474000000003,Unemployment Rate,Mar\n2019,5.2
178162,4485,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000003,Unemployment Rate,Mar\n2019,7.1
178163,4486,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000003,Unemployment Rate,Mar\n2019,7.1
178164,4490,MT5331020000000,31020,"Longview, WA Metropolitan Statistical Area",MT,LAUMT5331020000000,LAUMT533102000000003,Unemployment Rate,Mar\n2019,6.7
178165,4492,MT5334580000000,34580,"Mount Vernon-Anacortes, WA Metropolitan Statis...",MT,LAUMT5334580000000,LAUMT533458000000003,Unemployment Rate,Mar\n2019,5.9
178166,4495,MT5336500000000,36500,"Olympia-Tumwater, WA Metropolitan Statistical ...",MT,LAUMT5336500000000,LAUMT533650000000003,Unemployment Rate,Mar\n2019,5.4
178167,4503,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000003,Unemployment Rate,Mar\n2019,4.1
178168,4504,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000003,Unemployment Rate,Mar\n2019,4.1
178169,4505,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000003,Unemployment Rate,Mar\n2019,4.1
178170,4507,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000003,Unemployment Rate,Mar\n2019,6.8
178171,4508,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000003,Unemployment Rate,Mar\n2019,6.8
178172,4509,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000003,Unemployment Rate,Mar\n2019,6.8
178173,4513,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000003,Unemployment Rate,Mar\n2019,6.6
178174,4514,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000003,Unemployment Rate,Mar\n2019,6.6
178175,4515,MT5349420000000,49420,"Yakima, WA Metropolitan Statistical Area",MT,LAUMT5349420000000,LAUMT534942000000003,Unemployment Rate,Mar\n2019,9.2
178176,4572,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000003,Unemployment Rate,Mar\n2019,2.8
178177,4573,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000003,Unemployment Rate,Mar\n2019,2.8
178178,4586,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000003,Unemployment Rate,Mar\n2019,3.4
178179,4587,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000003,Unemployment Rate,Mar\n2019,3.4
178180,4591,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000003,Unemployment Rate,Mar\n2019,3.0
178181,4592,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000003,Unemployment Rate,Mar\n2019,3.0
178182,4593,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000003,Unemployment Rate,Mar\n2019,3.0
178183,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,Mar\n2019,2.4
178184,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,Mar\n2019,2.4
178185,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,Mar\n2019,2.4
178186,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000003,Unemployment Rate,Mar\n2019,2.4
178187,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000003,Unemployment Rate,Mar\n2019,2.7
178188,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000003,Unemployment Rate,Mar\n2019,3.9
178189,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000003,Unemployment Rate,Mar\n2019,2.6

In [131]:
df_unemployment_labor=pd.melt(unemployment_labor, id_vars=list(unemployment_labor)[0:8], value_vars=list(unemployment_labor)[9:],var_name='Month-Year',
       value_name='Unemployment_Labor')
df_unemployment_labor

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Month-Year,Unemployment_Labor
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
1,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
2,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
3,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
4,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
5,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
6,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
7,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000004,Unemployment,Feb\n2002,9182.0
8,41,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000004,Unemployment,Feb\n2002,9182.0
9,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT,LAUMT0133660000000,LAUMT013366000000004,Unemployment,Feb\n2002,12424.0
10,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000004,Unemployment,Feb\n2002,8900.0
11,49,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000004,Unemployment,Feb\n2002,8900.0
12,50,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000004,Unemployment,Feb\n2002,8900.0
13,51,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000004,Unemployment,Feb\n2002,8900.0
14,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000004,Unemployment,Feb\n2002,11606.0
15,71,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000004,Unemployment,Feb\n2002,11606.0
16,98,MT0422380000000,22380,"Flagstaff, AZ Metropolitan Statistical Area",MT,LAUMT0422380000000,LAUMT042238000000004,Unemployment,Feb\n2002,3591.0
17,153,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000004,Unemployment,Feb\n2002,16371.0
18,154,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000004,Unemployment,Feb\n2002,16371.0
19,155,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000004,Unemployment,Feb\n2002,16371.0
20,156,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000004,Unemployment,Feb\n2002,16371.0
21,157,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000004,Unemployment,Feb\n2002,16371.0
22,158,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000004,Unemployment,Feb\n2002,16371.0
23,189,MT0612540000000,12540,"Bakersfield, CA Metropolitan Statistical Area",MT,LAUMT0612540000000,LAUMT061254000000004,Unemployment,Feb\n2002,32697.0
24,191,MT0617020000000,17020,"Chico, CA Metropolitan Statistical Area",MT,LAUMT0617020000000,LAUMT061702000000004,Unemployment,Feb\n2002,7668.0
25,195,MT0620940000000,20940,"El Centro, CA Metropolitan Statistical Area",MT,LAUMT0620940000000,LAUMT062094000000004,Unemployment,Feb\n2002,6924.0
26,199,MT0625260000000,25260,"Hanford-Corcoran, CA Metropolitan Statistical ...",MT,LAUMT0625260000000,LAUMT062526000000004,Unemployment,Feb\n2002,6846.0
27,201,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000004,Unemployment,Feb\n2002,393401.0
28,202,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000004,Unemployment,Feb\n2002,393401.0
29,205,MT0632900000000,32900,"Merced, CA Metropolitan Statistical Area",MT,LAUMT0632900000000,LAUMT063290000000004,Unemployment,Feb\n2002,12820.0
...,...,...,...,...,...,...,...,...,...,...
178160,4478,MT5313380000000,13380,"Bellingham, WA Metropolitan Statistical Area",MT,LAUMT5313380000000,LAUMT531338000000004,Unemployment,Mar\n2019,6066.0
178161,4479,MT5314740000000,14740,"Bremerton-Silverdale, WA Metropolitan Statisti...",MT,LAUMT5314740000000,LAUMT531474000000004,Unemployment,Mar\n2019,6625.0
178162,4485,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000004,Unemployment,Mar\n2019,10251.0
178163,4486,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000004,Unemployment,Mar\n2019,10251.0
178164,4490,MT5331020000000,31020,"Longview, WA Metropolitan Statistical Area",MT,LAUMT5331020000000,LAUMT533102000000004,Unemployment,Mar\n2019,3162.0
178165,4492,MT5334580000000,34580,"Mount Vernon-Anacortes, WA Metropolitan Statis...",MT,LAUMT5334580000000,LAUMT533458000000004,Unemployment,Mar\n2019,3636.0
178166,4495,MT5336500000000,36500,"Olympia-Tumwater, WA Metropolitan Statistical ...",MT,LAUMT5336500000000,LAUMT533650000000004,Unemployment,Mar\n2019,7638.0
178167,4503,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000004,Unemployment,Mar\n2019,89628.0
178168,4504,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000004,Unemployment,Mar\n2019,89628.0
178169,4505,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000004,Unemployment,Mar\n2019,89628.0
178170,4507,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000004,Unemployment,Mar\n2019,18971.0
178171,4508,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000004,Unemployment,Mar\n2019,18971.0
178172,4509,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000004,Unemployment,Mar\n2019,18971.0
178173,4513,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000004,Unemployment,Mar\n2019,4273.0
178174,4514,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000004,Unemployment,Mar\n2019,4273.0
178175,4515,MT5349420000000,49420,"Yakima, WA Metropolitan Statistical Area",MT,LAUMT5349420000000,LAUMT534942000000004,Unemployment,Mar\n2019,12056.0
178176,4572,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000004,Unemployment,Mar\n2019,3704.0
178177,4573,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000004,Unemployment,Mar\n2019,3704.0
178178,4586,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000004,Unemployment,Mar\n2019,3173.0
178179,4587,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000004,Unemployment,Mar\n2019,3173.0
178180,4591,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000004,Unemployment,Mar\n2019,5293.0
178181,4592,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000004,Unemployment,Mar\n2019,5293.0
178182,4593,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000004,Unemployment,Mar\n2019,5293.0
178183,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,Mar\n2019,9439.0
178184,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,Mar\n2019,9439.0
178185,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,Mar\n2019,9439.0
178186,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,Mar\n2019,9439.0
178187,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000004,Unemployment,Mar\n2019,2501.0
178188,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000004,Unemployment,Mar\n2019,3920.0
178189,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000004,Unemployment,Mar\n2019,1614.0

In [132]:
df_employment_labor=pd.melt(employment_labor, id_vars=list(employment_labor)[0:8], value_vars=list(employment_labor)[9:],var_name='Month-Year',
       value_name='employment_Labor')
df_employment_labor

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Month-Year,employment_Labor
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,Feb\n2002,496008.0
1,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,Feb\n2002,496008.0
2,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,Feb\n2002,496008.0
3,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,Feb\n2002,496008.0
4,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,Feb\n2002,496008.0
5,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,Feb\n2002,496008.0
6,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000005,Employment,Feb\n2002,496008.0
7,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000005,Employment,Feb\n2002,171510.0
8,41,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000005,Employment,Feb\n2002,171510.0
9,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT,LAUMT0133660000000,LAUMT013366000000005,Employment,Feb\n2002,168202.0
10,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000005,Employment,Feb\n2002,153151.0
11,49,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000005,Employment,Feb\n2002,153151.0
12,50,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000005,Employment,Feb\n2002,153151.0
13,51,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000005,Employment,Feb\n2002,153151.0
14,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000005,Employment,Feb\n2002,162486.0
15,71,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000005,Employment,Feb\n2002,162486.0
16,98,MT0422380000000,22380,"Flagstaff, AZ Metropolitan Statistical Area",MT,LAUMT0422380000000,LAUMT042238000000005,Employment,Feb\n2002,60345.0
17,153,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000005,Employment,Feb\n2002,293072.0
18,154,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000005,Employment,Feb\n2002,293072.0
19,155,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000005,Employment,Feb\n2002,293072.0
20,156,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000005,Employment,Feb\n2002,293072.0
21,157,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000005,Employment,Feb\n2002,293072.0
22,158,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000005,Employment,Feb\n2002,293072.0
23,189,MT0612540000000,12540,"Bakersfield, CA Metropolitan Statistical Area",MT,LAUMT0612540000000,LAUMT061254000000005,Employment,Feb\n2002,265129.0
24,191,MT0617020000000,17020,"Chico, CA Metropolitan Statistical Area",MT,LAUMT0617020000000,LAUMT061702000000005,Employment,Feb\n2002,89457.0
25,195,MT0620940000000,20940,"El Centro, CA Metropolitan Statistical Area",MT,LAUMT0620940000000,LAUMT062094000000005,Employment,Feb\n2002,49954.0
26,199,MT0625260000000,25260,"Hanford-Corcoran, CA Metropolitan Statistical ...",MT,LAUMT0625260000000,LAUMT062526000000005,Employment,Feb\n2002,43828.0
27,201,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000005,Employment,Feb\n2002,5915360.0
28,202,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000005,Employment,Feb\n2002,5915360.0
29,205,MT0632900000000,32900,"Merced, CA Metropolitan Statistical Area",MT,LAUMT0632900000000,LAUMT063290000000005,Employment,Feb\n2002,81672.0
...,...,...,...,...,...,...,...,...,...,...
178160,4478,MT5313380000000,13380,"Bellingham, WA Metropolitan Statistical Area",MT,LAUMT5313380000000,LAUMT531338000000005,Employment,Mar\n2019,109494.0
178161,4479,MT5314740000000,14740,"Bremerton-Silverdale, WA Metropolitan Statisti...",MT,LAUMT5314740000000,LAUMT531474000000005,Employment,Mar\n2019,119976.0
178162,4485,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000005,Employment,Mar\n2019,134526.0
178163,4486,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000005,Employment,Mar\n2019,134526.0
178164,4490,MT5331020000000,31020,"Longview, WA Metropolitan Statistical Area",MT,LAUMT5331020000000,LAUMT533102000000005,Employment,Mar\n2019,43866.0
178165,4492,MT5334580000000,34580,"Mount Vernon-Anacortes, WA Metropolitan Statis...",MT,LAUMT5334580000000,LAUMT533458000000005,Employment,Mar\n2019,58183.0
178166,4495,MT5336500000000,36500,"Olympia-Tumwater, WA Metropolitan Statistical ...",MT,LAUMT5336500000000,LAUMT533650000000005,Employment,Mar\n2019,135128.0
178167,4503,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000005,Employment,Mar\n2019,2081952.0
178168,4504,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000005,Employment,Mar\n2019,2081952.0
178169,4505,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000005,Employment,Mar\n2019,2081952.0
178170,4507,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000005,Employment,Mar\n2019,260055.0
178171,4508,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000005,Employment,Mar\n2019,260055.0
178172,4509,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000005,Employment,Mar\n2019,260055.0
178173,4513,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000005,Employment,Mar\n2019,60775.0
178174,4514,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000005,Employment,Mar\n2019,60775.0
178175,4515,MT5349420000000,49420,"Yakima, WA Metropolitan Statistical Area",MT,LAUMT5349420000000,LAUMT534942000000005,Employment,Mar\n2019,118881.0
178176,4572,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000005,Employment,Mar\n2019,126665.0
178177,4573,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000005,Employment,Mar\n2019,126665.0
178178,4586,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000005,Employment,Mar\n2019,89946.0
178179,4587,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000005,Employment,Mar\n2019,89946.0
178180,4591,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000005,Employment,Mar\n2019,170806.0
178181,4592,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000005,Employment,Mar\n2019,170806.0
178182,4593,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000005,Employment,Mar\n2019,170806.0
178183,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,Mar\n2019,377704.0
178184,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,Mar\n2019,377704.0
178185,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,Mar\n2019,377704.0
178186,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000005,Employment,Mar\n2019,377704.0
178187,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000005,Employment,Mar\n2019,90583.0
178188,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000005,Employment,Mar\n2019,95580.0
178189,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000005,Employment,Mar\n2019,60943.0

In [133]:
df_total_labor=pd.melt(total_labor, id_vars=list(total_labor)[0:8], value_vars=list(total_labor)[9:],var_name='Month-Year',
       value_name='Total_Labor')
df_total_labor

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Month-Year,Total_Labor
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0
1,7,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0
2,8,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0
3,9,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0
4,10,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0
5,11,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0
6,12,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0
7,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000006,Total Labor Force,Feb\n2002,180692.0
8,41,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000006,Total Labor Force,Feb\n2002,180692.0
9,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT,LAUMT0133660000000,LAUMT013366000000006,Total Labor Force,Feb\n2002,180626.0
10,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000006,Total Labor Force,Feb\n2002,162051.0
11,49,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000006,Total Labor Force,Feb\n2002,162051.0
12,50,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000006,Total Labor Force,Feb\n2002,162051.0
13,51,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000006,Total Labor Force,Feb\n2002,162051.0
14,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000006,Total Labor Force,Feb\n2002,174092.0
15,71,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000006,Total Labor Force,Feb\n2002,174092.0
16,98,MT0422380000000,22380,"Flagstaff, AZ Metropolitan Statistical Area",MT,LAUMT0422380000000,LAUMT042238000000006,Total Labor Force,Feb\n2002,63936.0
17,153,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000006,Total Labor Force,Feb\n2002,309443.0
18,154,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000006,Total Labor Force,Feb\n2002,309443.0
19,155,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000006,Total Labor Force,Feb\n2002,309443.0
20,156,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000006,Total Labor Force,Feb\n2002,309443.0
21,157,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000006,Total Labor Force,Feb\n2002,309443.0
22,158,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000006,Total Labor Force,Feb\n2002,309443.0
23,189,MT0612540000000,12540,"Bakersfield, CA Metropolitan Statistical Area",MT,LAUMT0612540000000,LAUMT061254000000006,Total Labor Force,Feb\n2002,297826.0
24,191,MT0617020000000,17020,"Chico, CA Metropolitan Statistical Area",MT,LAUMT0617020000000,LAUMT061702000000006,Total Labor Force,Feb\n2002,97125.0
25,195,MT0620940000000,20940,"El Centro, CA Metropolitan Statistical Area",MT,LAUMT0620940000000,LAUMT062094000000006,Total Labor Force,Feb\n2002,56878.0
26,199,MT0625260000000,25260,"Hanford-Corcoran, CA Metropolitan Statistical ...",MT,LAUMT0625260000000,LAUMT062526000000006,Total Labor Force,Feb\n2002,50674.0
27,201,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000006,Total Labor Force,Feb\n2002,6308761.0
28,202,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000006,Total Labor Force,Feb\n2002,6308761.0
29,205,MT0632900000000,32900,"Merced, CA Metropolitan Statistical Area",MT,LAUMT0632900000000,LAUMT063290000000006,Total Labor Force,Feb\n2002,94492.0
...,...,...,...,...,...,...,...,...,...,...
178160,4478,MT5313380000000,13380,"Bellingham, WA Metropolitan Statistical Area",MT,LAUMT5313380000000,LAUMT531338000000006,Total Labor Force,Mar\n2019,115560.0
178161,4479,MT5314740000000,14740,"Bremerton-Silverdale, WA Metropolitan Statisti...",MT,LAUMT5314740000000,LAUMT531474000000006,Total Labor Force,Mar\n2019,126601.0
178162,4485,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000006,Total Labor Force,Mar\n2019,144777.0
178163,4486,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000006,Total Labor Force,Mar\n2019,144777.0
178164,4490,MT5331020000000,31020,"Longview, WA Metropolitan Statistical Area",MT,LAUMT5331020000000,LAUMT533102000000006,Total Labor Force,Mar\n2019,47028.0
178165,4492,MT5334580000000,34580,"Mount Vernon-Anacortes, WA Metropolitan Statis...",MT,LAUMT5334580000000,LAUMT533458000000006,Total Labor Force,Mar\n2019,61819.0
178166,4495,MT5336500000000,36500,"Olympia-Tumwater, WA Metropolitan Statistical ...",MT,LAUMT5336500000000,LAUMT533650000000006,Total Labor Force,Mar\n2019,142766.0
178167,4503,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000006,Total Labor Force,Mar\n2019,2171580.0
178168,4504,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000006,Total Labor Force,Mar\n2019,2171580.0
178169,4505,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000006,Total Labor Force,Mar\n2019,2171580.0
178170,4507,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000006,Total Labor Force,Mar\n2019,279026.0
178171,4508,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000006,Total Labor Force,Mar\n2019,279026.0
178172,4509,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000006,Total Labor Force,Mar\n2019,279026.0
178173,4513,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000006,Total Labor Force,Mar\n2019,65048.0
178174,4514,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000006,Total Labor Force,Mar\n2019,65048.0
178175,4515,MT5349420000000,49420,"Yakima, WA Metropolitan Statistical Area",MT,LAUMT5349420000000,LAUMT534942000000006,Total Labor Force,Mar\n2019,130937.0
178176,4572,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000006,Total Labor Force,Mar\n2019,130369.0
178177,4573,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000006,Total Labor Force,Mar\n2019,130369.0
178178,4586,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000006,Total Labor Force,Mar\n2019,93119.0
178179,4587,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000006,Total Labor Force,Mar\n2019,93119.0
178180,4591,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000006,Total Labor Force,Mar\n2019,176099.0
178181,4592,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000006,Total Labor Force,Mar\n2019,176099.0
178182,4593,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000006,Total Labor Force,Mar\n2019,176099.0
178183,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,Mar\n2019,387143.0
178184,4603,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,Mar\n2019,387143.0
178185,4604,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,Mar\n2019,387143.0
178186,4605,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,Mar\n2019,387143.0
178187,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000006,Total Labor Force,Mar\n2019,93084.0
178188,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000006,Total Labor Force,Mar\n2019,99500.0
178189,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0

In [134]:
df_total_labor=df_total_labor.drop_duplicates(['Series ID','Month-Year'])
df_unemployment_labor=df_unemployment_labor.drop_duplicates(['Series ID','Month-Year'])
df_employment_labor=df_employment_labor.drop_duplicates(['Series ID','Month-Year'])
df_unemployment=df_unemployment.drop_duplicates(['Series ID','Month-Year'])

In [148]:
df_unemployment_labor

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code,Series ID,Data Type,Month-Year,Unemployment_Labor
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000004,Unemployment,Feb\n2002,28075.0
7,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000004,Unemployment,Feb\n2002,9182.0
9,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT,LAUMT0133660000000,LAUMT013366000000004,Unemployment,Feb\n2002,12424.0
10,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000004,Unemployment,Feb\n2002,8900.0
14,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000004,Unemployment,Feb\n2002,11606.0
16,98,MT0422380000000,22380,"Flagstaff, AZ Metropolitan Statistical Area",MT,LAUMT0422380000000,LAUMT042238000000004,Unemployment,Feb\n2002,3591.0
17,153,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000004,Unemployment,Feb\n2002,16371.0
23,189,MT0612540000000,12540,"Bakersfield, CA Metropolitan Statistical Area",MT,LAUMT0612540000000,LAUMT061254000000004,Unemployment,Feb\n2002,32697.0
24,191,MT0617020000000,17020,"Chico, CA Metropolitan Statistical Area",MT,LAUMT0617020000000,LAUMT061702000000004,Unemployment,Feb\n2002,7668.0
25,195,MT0620940000000,20940,"El Centro, CA Metropolitan Statistical Area",MT,LAUMT0620940000000,LAUMT062094000000004,Unemployment,Feb\n2002,6924.0
26,199,MT0625260000000,25260,"Hanford-Corcoran, CA Metropolitan Statistical ...",MT,LAUMT0625260000000,LAUMT062526000000004,Unemployment,Feb\n2002,6846.0
27,201,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000004,Unemployment,Feb\n2002,393401.0
29,205,MT0632900000000,32900,"Merced, CA Metropolitan Statistical Area",MT,LAUMT0632900000000,LAUMT063290000000004,Unemployment,Feb\n2002,12820.0
30,206,MT0633700000000,33700,"Modesto, CA Metropolitan Statistical Area",MT,LAUMT0633700000000,LAUMT063370000000004,Unemployment,Feb\n2002,23170.0
31,209,MT0634900000000,34900,"Napa, CA Metropolitan Statistical Area",MT,LAUMT0634900000000,LAUMT063490000000004,Unemployment,Feb\n2002,3068.0
32,210,MT0637100000000,37100,"Oxnard-Thousand Oaks-Ventura, CA Metropolitan ...",MT,LAUMT0637100000000,LAUMT063710000000004,Unemployment,Feb\n2002,21709.0
33,213,MT0639820000000,39820,"Redding, CA Metropolitan Statistical Area",MT,LAUMT0639820000000,LAUMT063982000000004,Unemployment,Feb\n2002,6542.0
34,220,MT0641500000000,41500,"Salinas, CA Metropolitan Statistical Area",MT,LAUMT0641500000000,LAUMT064150000000004,Unemployment,Feb\n2002,26025.0
35,222,MT0641860000000,41860,"San Francisco-Oakland-Hayward, CA Metropolitan...",MT,LAUMT0641860000000,LAUMT064186000000004,Unemployment,Feb\n2002,135902.0
40,230,MT0642100000000,42100,"Santa Cruz-Watsonville, CA Metropolitan Statis...",MT,LAUMT0642100000000,LAUMT064210000000004,Unemployment,Feb\n2002,13392.0
41,231,MT0642200000000,42200,"Santa Maria-Santa Barbara, CA Metropolitan Sta...",MT,LAUMT0642200000000,LAUMT064220000000004,Unemployment,Feb\n2002,10973.0
42,232,MT0642220000000,42220,"Santa Rosa, CA Metropolitan Statistical Area",MT,LAUMT0642220000000,LAUMT064222000000004,Unemployment,Feb\n2002,12967.0
43,236,MT0644700000000,44700,"Stockton-Lodi, CA Metropolitan Statistical Area",MT,LAUMT0644700000000,LAUMT064470000000004,Unemployment,Feb\n2002,26557.0
44,241,MT0646700000000,46700,"Vallejo-Fairfield, CA Metropolitan Statistical...",MT,LAUMT0646700000000,LAUMT064670000000004,Unemployment,Feb\n2002,11337.0
45,243,MT0649700000000,49700,"Yuba City, CA Metropolitan Statistical Area",MT,LAUMT0649700000000,LAUMT064970000000004,Unemployment,Feb\n2002,7876.0
47,255,MT0817820000000,17820,"Colorado Springs, CO Metropolitan Statistical ...",MT,LAUMT0817820000000,LAUMT081782000000004,Unemployment,Feb\n2002,17648.0
49,274,MT0822660000000,22660,"Fort Collins, CO Metropolitan Statistical Area",MT,LAUMT0822660000000,LAUMT082266000000004,Unemployment,Feb\n2002,7336.0
50,453,MT2578100000000,78100,"Springfield, MA-CT Metropolitan NECTA",MT,LAUMT2578100000000,LAUMT257810000000004,Unemployment,Feb\n2002,17920.0
102,479,MT4237980000000,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...",MT,LAUMT4237980000000,LAUMT423798000000004,Unemployment,Feb\n2002,160074.0
113,481,MT1147900000000,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",MT,LAUMT1147900000000,LAUMT114790000000004,Unemployment,Feb\n2002,116170.0
...,...,...,...,...,...,...,...,...,...,...
178071,3939,MT4828660000000,28660,"Killeen-Temple, TX Metropolitan Statistical Area",MT,LAUMT4828660000000,LAUMT482866000000004,Unemployment,Mar\n2019,6750.0
178074,3951,MT4829700000000,29700,"Laredo, TX Metropolitan Statistical Area",MT,LAUMT4829700000000,LAUMT482970000000004,Unemployment,Mar\n2019,4481.0
178075,3963,MT4831180000000,31180,"Lubbock, TX Metropolitan Statistical Area",MT,LAUMT4831180000000,LAUMT483118000000004,Unemployment,Mar\n2019,5108.0
178078,4010,MT4841660000000,41660,"San Angelo, TX Metropolitan Statistical Area",MT,LAUMT4841660000000,LAUMT484166000000004,Unemployment,Mar\n2019,1715.0
178080,4012,MT4841700000000,41700,"San Antonio-New Braunfels, TX Metropolitan Sta...",MT,LAUMT4841700000000,LAUMT484170000000004,Unemployment,Mar\n2019,37577.0
178088,4049,MT4847380000000,47380,"Waco, TX Metropolitan Statistical Area",MT,LAUMT4847380000000,LAUMT484738000000004,Unemployment,Mar\n2019,4287.0
178090,4084,MT4941620000000,41620,"Salt Lake City, UT Metropolitan Statistical Area",MT,LAUMT4941620000000,LAUMT494162000000004,Unemployment,Mar\n2019,19482.0
178092,4134,MT5072400000000,72400,"Burlington-South Burlington, VT Metropolitan N...",MT,LAUMT5072400000000,LAUMT507240000000004,Unemployment,Mar\n2019,2226.0
178125,4351,MT5113980000000,13980,"Blacksburg-Christiansburg-Radford, VA Metropol...",MT,LAUMT5113980000000,LAUMT511398000000004,Unemployment,Mar\n2019,2874.0
178130,4376,MT5125500000000,25500,"Harrisonburg, VA Metropolitan Statistical Area",MT,LAUMT5125500000000,LAUMT512550000000004,Unemployment,Mar\n2019,1976.0
178132,4388,MT5131340000000,31340,"Lynchburg, VA Metropolitan Statistical Area",MT,LAUMT5131340000000,LAUMT513134000000004,Unemployment,Mar\n2019,4301.0
178137,4407,MT5140060000000,40060,"Richmond, VA Metropolitan Statistical Area",MT,LAUMT5140060000000,LAUMT514006000000004,Unemployment,Mar\n2019,21713.0
178154,4424,MT5140220000000,40220,"Roanoke, VA Metropolitan Statistical Area",MT,LAUMT5140220000000,LAUMT514022000000004,Unemployment,Mar\n2019,4774.0
178160,4478,MT5313380000000,13380,"Bellingham, WA Metropolitan Statistical Area",MT,LAUMT5313380000000,LAUMT531338000000004,Unemployment,Mar\n2019,6066.0
178161,4479,MT5314740000000,14740,"Bremerton-Silverdale, WA Metropolitan Statisti...",MT,LAUMT5314740000000,LAUMT531474000000004,Unemployment,Mar\n2019,6625.0
178162,4485,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000004,Unemployment,Mar\n2019,10251.0
178164,4490,MT5331020000000,31020,"Longview, WA Metropolitan Statistical Area",MT,LAUMT5331020000000,LAUMT533102000000004,Unemployment,Mar\n2019,3162.0
178165,4492,MT5334580000000,34580,"Mount Vernon-Anacortes, WA Metropolitan Statis...",MT,LAUMT5334580000000,LAUMT533458000000004,Unemployment,Mar\n2019,3636.0
178166,4495,MT5336500000000,36500,"Olympia-Tumwater, WA Metropolitan Statistical ...",MT,LAUMT5336500000000,LAUMT533650000000004,Unemployment,Mar\n2019,7638.0
178167,4503,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000004,Unemployment,Mar\n2019,89628.0
178170,4507,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000004,Unemployment,Mar\n2019,18971.0
178173,4513,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000004,Unemployment,Mar\n2019,4273.0
178175,4515,MT5349420000000,49420,"Yakima, WA Metropolitan Statistical Area",MT,LAUMT5349420000000,LAUMT534942000000004,Unemployment,Mar\n2019,12056.0
178176,4572,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000004,Unemployment,Mar\n2019,3704.0
178178,4586,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000004,Unemployment,Mar\n2019,3173.0
178180,4591,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000004,Unemployment,Mar\n2019,5293.0
178183,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000004,Unemployment,Mar\n2019,9439.0
178187,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000004,Unemployment,Mar\n2019,2501.0
178188,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000004,Unemployment,Mar\n2019,3920.0
178189,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000004,Unemployment,Mar\n2019,1614.0

In [149]:
new_df = pd.merge(df_total_labor, df_unemployment_labor,  how='left', 
                  left_on=['record','lma_code','lma_fips','lma_title','Area_Code','Month-Year'],
                 right_on=['record','lma_code','lma_fips','lma_title','Area_Code','Month-Year'])

In [150]:
new_df

,record,lma_code,lma_fips,lma_title,two_digit_x,Area_Code,Series ID_x,Data Type_x,Month-Year,Total_Labor,two_digit_y,Series ID_y,Data Type_y,Unemployment_Labor
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,MT,LAUMT011382000000004,Unemployment,28075.0
1,40,MT0126620000000,26620,"Huntsville, AL Metropolitan Statistical Area",MT,LAUMT0126620000000,LAUMT012662000000006,Total Labor Force,Feb\n2002,180692.0,MT,LAUMT012662000000004,Unemployment,9182.0
2,46,MT0133660000000,33660,"Mobile, AL Metropolitan Statistical Area",MT,LAUMT0133660000000,LAUMT013366000000006,Total Labor Force,Feb\n2002,180626.0,MT,LAUMT013366000000004,Unemployment,12424.0
3,48,MT0133860000000,33860,"Montgomery, AL Metropolitan Statistical Area",MT,LAUMT0133860000000,LAUMT013386000000006,Total Labor Force,Feb\n2002,162051.0,MT,LAUMT013386000000004,Unemployment,8900.0
4,70,MT0211260000000,11260,"Anchorage, AK Metropolitan Statistical Area",MT,LAUMT0211260000000,LAUMT021126000000006,Total Labor Force,Feb\n2002,174092.0,MT,LAUMT021126000000004,Unemployment,11606.0
5,98,MT0422380000000,22380,"Flagstaff, AZ Metropolitan Statistical Area",MT,LAUMT0422380000000,LAUMT042238000000006,Total Labor Force,Feb\n2002,63936.0,MT,LAUMT042238000000004,Unemployment,3591.0
6,153,MT0530780000000,30780,"Little Rock-North Little Rock-Conway, AR Metro...",MT,LAUMT0530780000000,LAUMT053078000000006,Total Labor Force,Feb\n2002,309443.0,MT,LAUMT053078000000004,Unemployment,16371.0
7,189,MT0612540000000,12540,"Bakersfield, CA Metropolitan Statistical Area",MT,LAUMT0612540000000,LAUMT061254000000006,Total Labor Force,Feb\n2002,297826.0,MT,LAUMT061254000000004,Unemployment,32697.0
8,191,MT0617020000000,17020,"Chico, CA Metropolitan Statistical Area",MT,LAUMT0617020000000,LAUMT061702000000006,Total Labor Force,Feb\n2002,97125.0,MT,LAUMT061702000000004,Unemployment,7668.0
9,195,MT0620940000000,20940,"El Centro, CA Metropolitan Statistical Area",MT,LAUMT0620940000000,LAUMT062094000000006,Total Labor Force,Feb\n2002,56878.0,MT,LAUMT062094000000004,Unemployment,6924.0
10,199,MT0625260000000,25260,"Hanford-Corcoran, CA Metropolitan Statistical ...",MT,LAUMT0625260000000,LAUMT062526000000006,Total Labor Force,Feb\n2002,50674.0,MT,LAUMT062526000000004,Unemployment,6846.0
11,201,MT0631080000000,31080,"Los Angeles-Long Beach-Anaheim, CA Metropolita...",MT,LAUMT0631080000000,LAUMT063108000000006,Total Labor Force,Feb\n2002,6308761.0,MT,LAUMT063108000000004,Unemployment,393401.0
12,205,MT0632900000000,32900,"Merced, CA Metropolitan Statistical Area",MT,LAUMT0632900000000,LAUMT063290000000006,Total Labor Force,Feb\n2002,94492.0,MT,LAUMT063290000000004,Unemployment,12820.0
13,206,MT0633700000000,33700,"Modesto, CA Metropolitan Statistical Area",MT,LAUMT0633700000000,LAUMT063370000000006,Total Labor Force,Feb\n2002,215086.0,MT,LAUMT063370000000004,Unemployment,23170.0
14,209,MT0634900000000,34900,"Napa, CA Metropolitan Statistical Area",MT,LAUMT0634900000000,LAUMT063490000000006,Total Labor Force,Feb\n2002,69662.0,MT,LAUMT063490000000004,Unemployment,3068.0
15,210,MT0637100000000,37100,"Oxnard-Thousand Oaks-Ventura, CA Metropolitan ...",MT,LAUMT0637100000000,LAUMT063710000000006,Total Labor Force,Feb\n2002,406546.0,MT,LAUMT063710000000004,Unemployment,21709.0
16,213,MT0639820000000,39820,"Redding, CA Metropolitan Statistical Area",MT,LAUMT0639820000000,LAUMT063982000000006,Total Labor Force,Feb\n2002,78615.0,MT,LAUMT063982000000004,Unemployment,6542.0
17,220,MT0641500000000,41500,"Salinas, CA Metropolitan Statistical Area",MT,LAUMT0641500000000,LAUMT064150000000006,Total Labor Force,Feb\n2002,202166.0,MT,LAUMT064150000000004,Unemployment,26025.0
18,222,MT0641860000000,41860,"San Francisco-Oakland-Hayward, CA Metropolitan...",MT,LAUMT0641860000000,LAUMT064186000000006,Total Labor Force,Feb\n2002,2264488.0,MT,LAUMT064186000000004,Unemployment,135902.0
19,230,MT0642100000000,42100,"Santa Cruz-Watsonville, CA Metropolitan Statis...",MT,LAUMT0642100000000,LAUMT064210000000006,Total Labor Force,Feb\n2002,147918.0,MT,LAUMT064210000000004,Unemployment,13392.0
20,231,MT0642200000000,42200,"Santa Maria-Santa Barbara, CA Metropolitan Sta...",MT,LAUMT0642200000000,LAUMT064220000000006,Total Labor Force,Feb\n2002,203221.0,MT,LAUMT064220000000004,Unemployment,10973.0
21,232,MT0642220000000,42220,"Santa Rosa, CA Metropolitan Statistical Area",MT,LAUMT0642220000000,LAUMT064222000000006,Total Labor Force,Feb\n2002,257675.0,MT,LAUMT064222000000004,Unemployment,12967.0
22,236,MT0644700000000,44700,"Stockton-Lodi, CA Metropolitan Statistical Area",MT,LAUMT0644700000000,LAUMT064470000000006,Total Labor Force,Feb\n2002,271577.0,MT,LAUMT064470000000004,Unemployment,26557.0
23,241,MT0646700000000,46700,"Vallejo-Fairfield, CA Metropolitan Statistical...",MT,LAUMT0646700000000,LAUMT064670000000006,Total Labor Force,Feb\n2002,200194.0,MT,LAUMT064670000000004,Unemployment,11337.0
24,243,MT0649700000000,49700,"Yuba City, CA Metropolitan Statistical Area",MT,LAUMT0649700000000,LAUMT064970000000006,Total Labor Force,Feb\n2002,63216.0,MT,LAUMT064970000000004,Unemployment,7876.0
25,255,MT0817820000000,17820,"Colorado Springs, CO Metropolitan Statistical ...",MT,LAUMT0817820000000,LAUMT081782000000006,Total Labor Force,Feb\n2002,283974.0,MT,LAUMT081782000000004,Unemployment,17648.0
26,274,MT0822660000000,22660,"Fort Collins, CO Metropolitan Statistical Area",MT,LAUMT0822660000000,LAUMT082266000000006,Total Labor Force,Feb\n2002,151123.0,MT,LAUMT082266000000004,Unemployment,7336.0
27,453,MT2578100000000,78100,"Springfield, MA-CT Metropolitan NECTA",MT,LAUMT2578100000000,LAUMT257810000000006,Total Labor Force,Feb\n2002,366322.0,MT,LAUMT257810000000004,Unemployment,17920.0
28,479,MT4237980000000,37980,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...",MT,LAUMT4237980000000,LAUMT423798000000006,Total Labor Force,Feb\n2002,2895631.0,MT,LAUMT423798000000004,Unemployment,160074.0
29,481,MT1147900000000,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",MT,LAUMT1147900000000,LAUMT114790000000006,Total Labor Force,Feb\n2002,2753752.0,MT,LAUMT114790000000004,Unemployment,116170.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34166,3939,MT4828660000000,28660,"Killeen-Temple, TX Metropolitan Statistical Area",MT,LAUMT4828660000000,LAUMT482866000000006,Total Labor Force,Mar\n2019,178422.0,MT,LAUMT482866000000004,Unemployment,6750.0
34167,3951,MT4829700000000,29700,"Laredo, TX Metropolitan Statistical Area",MT,LAUMT4829700000000,LAUMT482970000000006,Total Labor Force,Mar\n2019,118470.0,MT,LAUMT482970000000004,Unemployment,4481.0
34168,3963,MT4831180000000,31180,"Lubbock, TX Metropolitan Statistical Area",MT,LAUMT4831180000000,LAUMT483118000000006,Total Labor Force,Mar\n2019,164347.0,MT,LAUMT483118000000004,Unemployment,5108.0
34169,4010,MT4841660000000,41660,"San Angelo, TX Metropolitan Statistical Area",MT,LAUMT4841660000000,LAUMT484166000000006,Total Labor Force,Mar\n2019,56146.0,MT,LAUMT484166000000004,Unemployment,1715.0
34170,4012,MT4841700000000,41700,"San Antonio-New Braunfels, TX Metropolitan Sta...",MT,LAUMT4841700000000,LAUMT484170000000006,Total Labor Force,Mar\n2019,1208355.0,MT,LAUMT484170000000004,Unemployment,37577.0
34171,4049,MT4847380000000,47380,"Waco, TX Metropolitan Statistical Area",MT,LAUMT4847380000000,LAUMT484738000000006,Total Labor Force,Mar\n2019,126423.0,MT,LAUMT484738000000004,Unemployment,4287.0
34172,4084,MT4941620000000,41620,"Salt Lake City, UT Metropolitan Statistical Area",MT,LAUMT4941620000000,LAUMT494162000000006,Total Labor Force,Mar\n2019,653688.0,MT,LAUMT494162000000004,Unemployment,19482.0
34173,4134,MT5072400000000,72400,"Burlington-South Burlington, VT Metropolitan N...",MT,LAUMT5072400000000,LAUMT507240000000006,Total Labor Force,Mar\n2019,125874.0,MT,LAUMT507240000000004,Unemployment,2226.0
34174,4351,MT5113980000000,13980,"Blacksburg-Christiansburg-Radford, VA Metropol...",MT,LAUMT5113980000000,LAUMT511398000000006,Total Labor Force,Mar\n2019,91087.0,MT,LAUMT511398000000004,Unemployment,2874.0
34175,4376,MT5125500000000,25500,"Harrisonburg, VA Metropolitan Statistical Area",MT,LAUMT5125500000000,LAUMT512550000000006,Total Labor Force,Mar\n2019,66255.0,MT,LAUMT512550000000004,Unemployment,1976.0
34176,4388,MT5131340000000,31340,"Lynchburg, VA Metropolitan Statistical Area",MT,LAUMT5131340000000,LAUMT513134000000006,Total Labor Force,Mar\n2019,123558.0,MT,LAUMT513134000000004,Unemployment,4301.0
34177,4407,MT5140060000000,40060,"Richmond, VA Metropolitan Statistical Area",MT,LAUMT5140060000000,LAUMT514006000000006,Total Labor Force,Mar\n2019,680912.0,MT,LAUMT514006000000004,Unemployment,21713.0
34178,4424,MT5140220000000,40220,"Roanoke, VA Metropolitan Statistical Area",MT,LAUMT5140220000000,LAUMT514022000000006,Total Labor Force,Mar\n2019,159111.0,MT,LAUMT514022000000004,Unemployment,4774.0
34179,4478,MT5313380000000,13380,"Bellingham, WA Metropolitan Statistical Area",MT,LAUMT5313380000000,LAUMT531338000000006,Total Labor Force,Mar\n2019,115560.0,MT,LAUMT531338000000004,Unemployment,6066.0
34180,4479,MT5314740000000,14740,"Bremerton-Silverdale, WA Metropolitan Statisti...",MT,LAUMT5314740000000,LAUMT531474000000006,Total Labor Force,Mar\n2019,126601.0,MT,LAUMT531474000000004,Unemployment,6625.0
34181,4485,MT5328420000000,28420,"Kennewick-Richland, WA Metropolitan Statistica...",MT,LAUMT5328420000000,LAUMT532842000000006,Total Labor Force,Mar\n2019,144777.0,MT,LAUMT532842000000004,Unemployment,10251.0
34182,4490,MT5331020000000,31020,"Longview, WA Metropolitan Statistical Area",MT,LAUMT5331020000000,LAUMT533102000000006,Total Labor Force,Mar\n2019,47028.0,MT,LAUMT533102000000004,Unemployment,3162.0
34183,4492,MT5334580000000,34580,"Mount Vernon-Anacortes, WA Metropolitan Statis...",MT,LAUMT5334580000000,LAUMT533458000000006,Total Labor Force,Mar\n2019,61819.0,MT,LAUMT533458000000004,Unemployment,3636.0
34184,4495,MT5336500000000,36500,"Olympia-Tumwater, WA Metropolitan Statistical ...",MT,LAUMT5336500000000,LAUMT533650000000006,Total Labor Force,Mar\n2019,142766.0,MT,LAUMT533650000000004,Unemployment,7638.0
34185,4503,MT5342660000000,42660,"Seattle-Tacoma-Bellevue, WA Metropolitan Stati...",MT,LAUMT5342660000000,LAUMT534266000000006,Total Labor Force,Mar\n2019,2171580.0,MT,LAUMT534266000000004,Unemployment,89628.0
34186,4507,MT5344060000000,44060,"Spokane-Spokane Valley, WA Metropolitan Statis...",MT,LAUMT5344060000000,LAUMT534406000000006,Total Labor Force,Mar\n2019,279026.0,MT,LAUMT534406000000004,Unemployment,18971.0
34187,4513,MT5348300000000,48300,"Wenatchee, WA Metropolitan Statistical Area",MT,LAUMT5348300000000,LAUMT534830000000006,Total Labor Force,Mar\n2019,65048.0,MT,LAUMT534830000000004,Unemployment,4273.0
34188,4515,MT5349420000000,49420,"Yakima, WA Metropolitan Statistical Area",MT,LAUMT5349420000000,LAUMT534942000000006,Total Labor Force,Mar\n2019,130937.0,MT,LAUMT534942000000004,Unemployment,12056.0
34189,4572,MT5511540000000,11540,"Appleton, WI Metropolitan Statistical Area",MT,LAUMT5511540000000,LAUMT551154000000006,Total Labor Force,Mar\n2019,130369.0,MT,LAUMT551154000000004,Unemployment,3704.0
34190,4586,MT5520740000000,20740,"Eau Claire, WI Metropolitan Statistical Area",MT,LAUMT5520740000000,LAUMT552074000000006,Total Labor Force,Mar\n2019,93119.0,MT,LAUMT552074000000004,Unemployment,3173.0
34191,4591,MT5524580000000,24580,"Green Bay, WI Metropolitan Statistical Area",MT,LAUMT5524580000000,LAUMT552458000000006,Total Labor Force,Mar\n2019,176099.0,MT,LAUMT552458000000004,Unemployment,5293.0
34192,4602,MT5531540000000,31540,"Madison, WI Metropolitan Statistical Area",MT,LAUMT5531540000000,LAUMT553154000000006,Total Labor Force,Mar\n2019,387143.0,MT,LAUMT553154000000004,Unemployment,9439.0
34193,4619,MT5536780000000,36780,"Oshkosh-Neenah, WI Metropolitan Statistical Area",MT,LAUMT5536780000000,LAUMT553678000000006,Total Labor Force,Mar\n2019,93084.0,MT,LAUMT553678000000004,Unemployment,2501.0
34194,4624,MT5539540000000,39540,"Racine, WI Metropolitan Statistical Area",MT,LAUMT5539540000000,LAUMT553954000000006,Total Labor Force,Mar\n2019,99500.0,MT,LAUMT553954000000004,Unemployment,3920.0
34195,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,MT,LAUMT554310000000004,Unemployment,1614.0

In [113]:
list(df_unemployment_labor)

['record',
 'lma_code',
 'lma_fips',
 'lma_title',
 'two_digit',
 'Area_Code',
 'Series ID',
 'Data Type',
 'Month-Year',
 'Unemployment_Labor']

In [115]:
df_unemployment_labor=df_unemployment_labor.drop(columns=['lma_code','lma_fips','lma_title','two_digit',
                                                'Series ID','Data Type','Month-Year'])

In [117]:
df_uemployment_labor=df_employment_labor.drop(columns=['lma_code','lma_fips','lma_title','two_digit',
                                                'Series ID','Data Type','Month-Year'])
df_unemployment=df_unemployment.drop(columns=['lma_code','lma_fips','lma_title','two_digit',
                                                'Series ID','Data Type','Month-Year'])

In [151]:
df_unemployment.to_csv('df_unemployment.csv')
df_unemployment_labor.to_csv('df_unemployment_labor.csv')
df_employment_labor.to_csv('df_emoyment_labor.csv')
df_total_labor.to_csv('df_total_labor.csv')

In [127]:
df_unemployment_labor[df_unemployment_labor['record']==6]

        record           Area_Code  Unemployment_Labor
0            6  LAUMT0113820000000             28075.0
865          6  LAUMT0113820000000             26660.0
1730         6  LAUMT0113820000000             23184.0
2595         6  LAUMT0113820000000             22945.0
3460         6  LAUMT0113820000000             28159.0
4325         6  LAUMT0113820000000             27154.0
5190         6  LAUMT0113820000000             28192.0
6055         6  LAUMT0113820000000             26288.0
6920         6  LAUMT0113820000000             25820.0
7785         6  LAUMT0113820000000             26638.0
8650         6  LAUMT0113820000000             25885.0
9515         6  LAUMT0113820000000             27297.0
10380        6  LAUMT0113820000000             27181.0
11245        6  LAUMT0113820000000             25135.0
12110        6  LAUMT0113820000000             23796.0
12975        6  LAUMT0113820000000             25322.0
13840        6  LAUMT0113820000000             31589.0
14705        6  LAUMT0113820000000             28401.0
15570        6  LAUMT0113820000000             29276.0
16435        6  LAUMT0113820000000             27161.0
17300        6  LAUMT0113820000000             28013.0
18165        6  LAUMT0113820000000             27877.0
19030        6  LAUMT0113820000000             25891.0
19895        6  LAUMT0113820000000             27941.0
20760        6  LAUMT0113820000000             27521.0
21625        6  LAUMT0113820000000             27235.0
22490        6  LAUMT0113820000000             23832.0
23355        6  LAUMT0113820000000             24681.0
24220        6  LAUMT0113820000000             28491.0
25085        6  LAUMT0113820000000             27280.0
...        ...                 ...                 ...
152240       6  LAUMT0113820000000             30113.0
153105       6  LAUMT0113820000000             27226.0
153970       6  LAUMT0113820000000             26992.0
154835       6  LAUMT0113820000000             29587.0
155700       6  LAUMT0113820000000             28448.0
156565       6  LAUMT0113820000000             24447.0
157430       6  LAUMT0113820000000             20398.0
158295       6  LAUMT0113820000000             19693.0
159160       6  LAUMT0113820000000             23868.0
160025       6  LAUMT0113820000000             22326.0
160890       6  LAUMT0113820000000             21111.0
161755       6  LAUMT0113820000000             18383.0
162620       6  LAUMT0113820000000             18572.0
163485       6  LAUMT0113820000000             17708.0
164350       6  LAUMT0113820000000             17620.0
165215       6  LAUMT0113820000000             20918.0
166080       6  LAUMT0113820000000             21521.0
166945       6  LAUMT0113820000000             19718.0
167810       6  LAUMT0113820000000             16986.0
168675       6  LAUMT0113820000000             17431.0
169540       6  LAUMT0113820000000             23138.0
170405       6  LAUMT0113820000000             20721.0
171270       6  LAUMT0113820000000             20124.0
172135       6  LAUMT0113820000000             18060.0
173000       6  LAUMT0113820000000             18447.0
173865       6  LAUMT0113820000000             16618.0
174730       6  LAUMT0113820000000             17366.0
175595       6  LAUMT0113820000000             21438.0
176460       6  LAUMT0113820000000             19591.0
177325       6  LAUMT0113820000000             18875.0

[206 rows x 3 columns]

In [123]:
merged_1=pd.merge(df_total_labor,df_unemployment_labor,on='record')
merged_1

,record,lma_code,lma_fips,lma_title,two_digit,Area_Code_x,Series ID,Data Type,Month-Year,Total_Labor,Area_Code_y,Unemployment_Labor
0,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,28075.0
1,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,26660.0
2,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,23184.0
3,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,22945.0
4,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,28159.0
5,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27154.0
6,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,28192.0
7,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,26288.0
8,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,25820.0
9,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,26638.0
10,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,25885.0
11,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27297.0
12,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27181.0
13,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,25135.0
14,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,23796.0
15,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,25322.0
16,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,31589.0
17,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,28401.0
18,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,29276.0
19,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27161.0
20,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,28013.0
21,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27877.0
22,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,25891.0
23,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27941.0
24,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27521.0
25,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27235.0
26,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,23832.0
27,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,24681.0
28,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,28491.0
29,6,MT0113820000000,13820,"Birmingham-Hoover, AL Metropolitan Statistical...",MT,LAUMT0113820000000,LAUMT011382000000006,Total Labor Force,Feb\n2002,524083.0,LAUMT0113820000000,27280.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7044346,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1831.0
7044347,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1831.0
7044348,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1756.0
7044349,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,2089.0
7044350,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,2232.0
7044351,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1932.0
7044352,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1688.0
7044353,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1629.0
7044354,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,2015.0
7044355,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1855.0
7044356,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1695.0
7044357,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1470.0
7044358,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1398.0
7044359,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1407.0
7044360,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1391.0
7044361,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1699.0
7044362,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1889.0
7044363,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1804.0
7044364,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1496.0
7044365,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1496.0
7044366,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1989.0
7044367,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1682.0
7044368,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1534.0
7044369,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1245.0
7044370,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1290.0
7044371,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1325.0
7044372,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1400.0
7044373,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1654.0
7044374,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1574.0
7044375,4630,MT5543100000000,43100,"Sheboygan, WI Metropolitan Statistical Area",MT,LAUMT5543100000000,LAUMT554310000000006,Total Labor Force,Mar\n2019,62557.0,LAUMT5543100000000,1614.0